#include "../Source/BalanceDSP.h"
#include <chrono>
#include <complex>
#include <cstdlib>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <limits>
#include <new>
#include <random>
#include <vector>

namespace allocationWatch {bool active=false;std::uint64_t count=0;}
void* operator new(std::size_t n){if(allocationWatch::active)++allocationWatch::count;if(auto* p=std::malloc(n?n:1))return p;throw std::bad_alloc();}
void* operator new[](std::size_t n){return ::operator new(n);}
void operator delete(void* p)noexcept{std::free(p);}void operator delete[](void* p)noexcept{std::free(p);}
void operator delete(void* p,std::size_t)noexcept{std::free(p);}void operator delete[](void* p,std::size_t)noexcept{std::free(p);}
namespace {
constexpr double pi=3.14159265358979323846;
std::uint64_t checks=0,failures=0,samplesProcessed=0,configurations=0;
double maximumResponseError=0,maximumStaticResponse=0,maximumAutomationErrorStep=0,preColorDb=0,postColorDb=0,maximumOutput=0;
void require(bool ok,const char* label){++checks;if(!ok){++failures;if(failures<35)std::cerr<<"FAIL: "<<label<<'\n';}}
void process(gill::BalanceDSP& d,float* const* p,int c,int n){allocationWatch::active=true;d.process(p,c,n);allocationWatch::active=false;if(c>0&&n>0)samplesProcessed+=static_cast<std::uint64_t>(c)*n;}
bool same(const gill::LearnBalanceProfile& a,const gill::LearnBalanceProfile& b){return a.version==b.version&&a.valid==b.valid&&a.sampleRate==b.sampleRate&&a.bandDb==b.bandDb&&a.validBands==b.validBands&&a.activeRmsDb==b.activeRmsDb;}
gill::LearnBalanceProfile profile(double fs=48000){gill::LearnBalanceProfile p;p.valid=true;p.sampleRate=fs;p.activeRmsDb=-20;for(std::size_t b=0;b<8;++b){p.bandDb[b]=-10-static_cast<float>(b)*2;p.validBands[b]=gill::BalanceDSP::centersHz[b]<=fs*.45;}p.bandDb[2]+=6;return p;}
double response(const std::array<float,8>& gains,double rate,double hz){std::complex<double> result(1,0);const auto z=std::exp(std::complex<double>(0,-2*pi*hz/rate));for(std::size_t b=0;b<8;++b){if(gill::BalanceDSP::centersHz[b]>rate*.45)continue;const double A=std::pow(10.,gains[b]/40.),w=2*pi*gill::BalanceDSP::centersHz[b]/rate,alpha=std::sin(w)/(2*.85),c=std::cos(w);result*=((1+alpha*A)-2*c*z+(1-alpha*A)*z*z)/((1+alpha/A)-2*c*z+(1-alpha/A)*z*z);}return 20*std::log10(std::max(1e-20,std::abs(result)));}
void constant(gill::BalanceDSP& d,int n,float value=0,int block=127){std::array<float,1024> x{};float* p[]{x.data()};for(int at=0;at<n;){const auto take=std::min({n-at,block,1024});x.fill(value);process(d,p,1,take);at+=take;}}
double fineResponse(const gill::FineBalanceView& view,double rate,double hz){if(!view.enabled)return 0;std::complex<double> result(1,0);const auto z=std::polar(1.,-2*pi*hz/rate);auto add=[&](double center,double db,double q){if(center<=0||center>rate*.45)return;const double A=std::pow(10.,db/40.),w=2*pi*center/rate,alpha=std::sin(w)/(2*q),co=std::cos(w);result*=((1+alpha*A)-2*co*z+(1-alpha*A)*z*z)/((1+alpha/A)-2*co*z+(1-alpha/A)*z*z);};for(int b=0;b<8;++b)add(gill::BalanceDSP::centersHz[b],view.dynamics[b],.9);for(int b=0;b<view.count;++b)add(view.frequency[b],view.gain[b],view.q[b]);return 20*std::log10(std::abs(result));}
float voice(double time,double rate,bool colored=false){double x=0;for(int h=1;h<=100&&h*100<rate*.44;++h){const double hz=h*100.,octave=std::log2(hz/400.),color=colored?std::pow(10.,6*std::exp(-octave*octave/0.4)/20):1;x+=std::sin(2*pi*hz*time+h*.73)*std::pow(h,-.85)*color;}return static_cast<float>(.045*x*(.65+.35*std::sin(2*pi*2*time)*std::sin(2*pi*2*time)));}
void vocal(gill::BalanceDSP& d,double fs,double seconds,bool colored=false,int block=127){std::array<float,2048> x{},y{};float* p[]{x.data(),y.data()};const auto count=static_cast<int>(std::lround(fs*seconds));for(int at=0;at<count;){const int n=std::min({count-at,block,2048});for(int i=0;i<n;++i)x[i]=y[i]=voice((at+i)/fs,fs,colored);process(d,p,2,n);at+=n;}}
void basicAndProfile(){for(double fs:{8000.,11025.,44100.,48000.,96000.,192000.,384000.}){gill::BalanceDSP d;d.prepare(fs,127,2);require(d.latencySamples()==0,"zero reported audio latency");d.setParameters(100,4);std::array<float,127> x{},y{};for(int i=0;i<127;++i)x[i]=y[i]=static_cast<float>(.2*std::sin(i*.1));const auto original=x;float* p[]{x.data(),y.data()};process(d,p,2,127);require(x==original&&y==original,"unlearned engine is exact unity, no arbitrary default curve");require(d.setLearnedProfile(profile(fs)),"valid profile imports at every supported rate");d.reset();d.setParameters(0,2);constant(d,static_cast<int>(fs*.15));x=original;y=original;process(d,p,2,127);require(x==original&&y==original,"amount zero is sample-exact unity after settling");const auto active=d.activeBands();const auto gains=d.currentGainsDb();for(std::size_t b=0;b<8;++b){require(active[b]==(gill::BalanceDSP::centersHz[b]<=fs*.45),"nominal unavailable center is disabled instead of moved below Nyquist");if(!active[b])require(gains[b]==0,"unavailable band has zero gain");}}
    gill::BalanceDSP d;d.prepare(48000,64,1);const auto good=profile();require(d.setLearnedProfile(good),"initial valid state imports");for(int f=0;f<8;++f){auto bad=good;if(f==0)bad.version=2;if(f==1)bad.sampleRate=std::numeric_limits<double>::quiet_NaN();if(f==2)bad.bandDb[2]=std::numeric_limits<float>::infinity();if(f==3)bad.activeRmsDb=99;if(f==4)bad.bandDb[2]=1;if(f==5)bad.validBands.fill(false);if(f==6)bad.sampleRate=8000;if(f==7)bad.bandDb[7]=-100;require(!d.setLearnedProfile(bad)&&same(d.learnedProfile(),good),"invalid profile rejected without altering prior state");}
    auto weak=good;weak.bandDb[7]=-44;weak.bandDb[6]=-40;weak.activeRmsDb=-35;require(d.setLearnedProfile(weak),"low energy profile import accepted conservatively");d.setParameters(100,3);const auto g=d.currentGainsDb();require(g[0]<=0&&g[1]<=0&&g[6]<=0&&g[7]<=0,"fundamentals and low-confidence treble cannot be boosted");d.reset();require(same(d.learnedProfile(),weak),"reset preserves complete profile");d.prepare(96000,1024,2);require(same(d.learnedProfile(),weak),"prepare preserves complete profile");require(d.setLearnedProfile({})&&d.learningState()==0,"explicit empty profile clears learning");
}
void learning(){
    for(double fs:{8000.,44100.,48000.,96000.}){gill::BalanceDSP d;d.prepare(fs,127,2);d.startLearning();constant(d,static_cast<int>(fs*1.5));require(d.learningState()==1&&d.learningProgress()==0,"silence does not progress learning");vocal(d,fs,5,true);require(d.learningState()==1&&d.learningProgress()>.49&&d.learningProgress()<.51,"five active seconds approximately half learning");vocal(d,fs,5.1,true);auto p=d.learnedProfile();require(d.learningState()==2&&d.learningProgress()==1&&p.valid,"ten active seconds produce ready usable profile");for(std::size_t b=0;b<8;++b)require(!p.validBands[b]||gill::BalanceDSP::centersHz[b]<=fs*.45,"learned profile stores only measurable supported band centers");const auto fixed=p;vocal(d,fs,.5,false);require(same(d.learnedProfile(),fixed),"ready profile never drifts with later audio");d.startLearning();constant(d,static_cast<int>(fs*.5));d.cancelLearning();require(same(d.learnedProfile(),fixed)&&d.learningState()==2,"cancel retains completed tonal profile");d.startLearning();d.reset();require(same(d.learnedProfile(),fixed)&&d.learningState()==2,"reset cancels partial attempt preserving prior profile");}
    gill::BalanceDSP d;d.prepare(8000,160,1);d.startLearning();constant(d,8000*30);require(d.learningState()==3&&!d.learnedProfile().valid,"silence-only learning fails with insufficient audio");d.setLearnedProfile(profile(8000));auto p=d.learnedProfile();d.startLearning();constant(d,8000*30);require(d.learningState()==3&&same(p,d.learnedProfile()),"failed relearn retains previous completed profile");
    d.setLearnedProfile({});d.startLearning();std::array<float,160> spike{};float* ptr[]{spike.data()};for(int i=0;i<500;++i){spike.fill(0);spike[20]=i%2?100:1;process(d,ptr,1,160);}require(d.learningProgress()==0,"isolated impulse and gross overload transient frames do not progress learning");
    gill::BalanceDSP a,b;a.prepare(8000,1,2);b.prepare(8000,2048,2);a.setParameters(0,0);b.setParameters(100,4);a.startLearning();b.startLearning();vocal(a,8000,10.1,true,1);vocal(b,8000,10.1,true,2048);require(same(a.learnedProfile(),b.learnedProfile()),"learning is independent of amount target and host block partitioning");
}
void frequencyCalibration(){for(double fs:{8000.,44100.,48000.,96000.,192000.,384000.})for(int target=0;target<5;++target){gill::BalanceDSP d;d.prepare(fs,257,1);d.setLearnedProfile(profile(fs));d.setParameters(100,target);const auto gains=d.currentGainsDb();for(int f=0;f<400;++f){const double hz=20*std::pow(fs*.49/20.,f/399.);const double v=response(gains,fs,hz);maximumStaticResponse=std::max(maximumStaticResponse,std::abs(v));require(std::abs(v)<=6.00001,"whole static cascade bounded to plus/minus six dB over dense frequency grid");}
        for(double hz:{100.,400.,1600.,3200.,6400.,12000.})if(hz<fs*.44){d.reset();std::array<float,512> x{};float* ptr[]{x.data()};double a=0,b=0;const int total=static_cast<int>(fs*.16),warm=static_cast<int>(fs*.10);for(int at=0;at<total;){const int n=std::min(512,total-at);std::array<float,512> dry{};for(int i=0;i<n;++i)dry[i]=x[i]=static_cast<float>(.1*std::sin(2*pi*hz*(at+i)/fs));process(d,ptr,1,n);for(int i=0;i<n;++i)if(at+i>=warm){a+=dry[i]*dry[i];b+=x[i]*x[i];}at+=n;}const double measured=10*std::log10(b/a),expected=response(gains,fs,hz),error=std::abs(measured-expected);maximumResponseError=std::max(maximumResponseError,error);require(error<.03,"real processed sine response agrees with independent complex transfer calculation within 0.03 dB");}}
}
void correctionAndStyles(){gill::BalanceDSP d;d.prepare(48000,128,1);d.setParameters(100,0);d.startLearning();vocal(d,48000,10.1,true);require(d.learningState()==2,"colored synthetic vocal successfully learns");constant(d,4800);auto gains=d.currentGainsDb();const auto learned=d.learnedProfile();preColorDb=learned.bandDb[2]-(learned.bandDb[1]+learned.bandDb[3])*.5;postColorDb=preColorDb+response(gains,48000,400)-(response(gains,48000,200)+response(gains,48000,800))*.5;require(preColorDb>.5&&std::abs(postColorDb)<std::abs(preColorDb),"natural correction reduces a measured low-mid bulge in colored synthetic vocal");std::array<std::array<float,8>,5> variants{};for(int target=0;target<5;++target){d.setParameters(100,target);constant(d,4800);variants[target]=d.currentGainsDb();require(same(d.learnedProfile(),learned),"style selection reuses unchanged learned profile");}for(int a=0;a<5;++a)for(int b=a+1;b<5;++b)require(variants[a]!=variants[b],"all five style targets produce distinct real EQ curves");require(response(variants[3],48000,9000)>response(variants[4],48000,9000)+1,"trap air is distinctly brighter than dark rap");
    gill::BalanceDSP restored;restored.prepare(48000,128,1);require(restored.setLearnedProfile(learned),"learned profile reimports");restored.setParameters(100,4);require(restored.currentGainsDb()==variants[4],"state roundtrip reproduces exact static filter gains");
    d.setParameters(100,2);std::array<float,256> x{};float* p[]{x.data()};for(int k=0;k<800;++k){for(int i=0;i<256;++i)x[i]=static_cast<float>(.1*std::sin(2*pi*400*(k*256+i)/48000));process(d,p,1,256);}const auto pre=d.preBandLevelsDb(),post=d.postBandLevelsDb();require(std::abs(pre[2]-20*std::log10(.1/std::sqrt(2.)))<.03,"actual pre meter measures band sine power in dBFS");require(std::abs((post[2]-pre[2])-response(d.currentGainsDb(),48000,400)-fineResponse(d.fineView(),48000,400))<.03,"actual post meter agrees with processed-band level change");
}
void stereoAndAutomation(){std::vector<float> input(24000);for(std::size_t i=0;i<input.size();++i)input[i]=static_cast<float>(.1*std::sin(.137*i));gill::BalanceDSP a,b;a.prepare(48000,1,2);b.prepare(48000,257,2);a.setLearnedProfile(profile());b.setLearnedProfile(profile());a.setParameters(88,3);b.setParameters(88,3);auto left=input,right=input,other=input;for(auto& x:right)x=-x;for(std::size_t i=0;i<left.size();++i){float* p[]{left.data()+i,right.data()+i};process(a,p,2,1);}for(std::size_t at=0;at<other.size();){const int n=static_cast<int>(std::min<std::size_t>(257,other.size()-at));float* p[]{other.data()+at};process(b,p,1,n);at+=n;}require(left==other,"block partition and equal input stereo versus mono output sample exact");for(std::size_t i=0;i<left.size();++i)require(right[i]==-left[i],"stereo filter uses same curve without interchannel crossfeed");
    gill::BalanceDSP iso;iso.prepare(48000,128,2);iso.setLearnedProfile(profile());std::array<float,128> x{},y{};x[0]=.5;float* ptr[]{x.data(),y.data()};process(iso,ptr,2,128);for(float v:y)require(v==0,"left impulse cannot leak into right output");
    gill::BalanceDSP fast;fast.prepare(48000,17,1);fast.setLearnedProfile(profile());double previousDifference=0;for(int block=0;block<10000;++block){fast.setParameters(block%2?100.f:0.f,block%5);std::array<float,17> wet{},dry{};for(int i=0;i<17;++i)wet[i]=dry[i]=static_cast<float>(.1*std::sin(2*pi*400*(block*17+i)/48000));float* p[]{wet.data()};process(fast,p,1,17);for(int i=0;i<17;++i){const double difference=wet[i]-dry[i];if(block>100)maximumAutomationErrorStep=std::max(maximumAutomationErrorStep,std::abs(difference-previousDifference));previousDifference=difference;require(std::isfinite(wet[i])&&std::abs(wet[i])<.5,"rapid amount/style automation remains bounded");}}require(maximumAutomationErrorStep<.01,"rapid automation has bounded adjacent error-sample change");fast.setParameters(0,2);constant(fast,9600);std::array<float,17> unity{};unity.fill(.123f);float* p[]{unity.data()};process(fast,p,1,17);for(float v:unity)require(v==.123f,"amount zero fully settles back to exact unity after rapid automation");
}
void stress(){std::mt19937 random(48323);std::uniform_real_distribution<float> unit(-1,1);const double rates[]{8000,44100,48000,96000,192000,384000};for(int k=0;k<10000;++k){gill::BalanceDSP d;const double fs=rates[k%6];d.prepare(fs,257,2);auto p=profile(fs);for(std::size_t b=0;b<8;++b)p.bandDb[b]=std::clamp(-20+unit(random)*19,-96.f,0.f);d.setLearnedProfile(p);d.setParameters((unit(random)+1)*50,k%5);if(k%47==0)d.startLearning();std::array<float,257> x{},y{};for(int i=0;i<257;++i){x[i]=unit(random)*.5f;y[i]=unit(random)*.5f;}if(k%11==0)x[11]=std::numeric_limits<float>::quiet_NaN();if(k%13==0)y[19]=std::numeric_limits<float>::infinity();if(k%17==0)x[31]=std::numeric_limits<float>::max();if(k%19==0)x[42]=std::numeric_limits<float>::denorm_min();float* ptr[]{x.data(),y.data()};process(d,ptr,2,257);for(int i=0;i<257;++i){require(std::isfinite(x[i])&&std::isfinite(y[i]),"10,000 actual audio configurations remain finite");maximumOutput=std::max({maximumOutput,std::abs(static_cast<double>(x[i])),std::abs(static_cast<double>(y[i]))});}for(float g:d.currentGainsDb())require(std::isfinite(g)&&g>=-6&&g<=6,"random gains remain bounded");require(d.learningProgress()>=0&&d.learningProgress()<=1,"learning meter bounded");++configurations;}
    gill::BalanceDSP d;d.prepare(384000,127,1);d.setLearnedProfile(profile());d.setParameters(std::numeric_limits<float>::quiet_NaN(),99);d.reset();std::array<float,127> zero{};float* p[]{zero.data()};for(int i=0;i<20;++i)process(d,p,1,127);for(float x:zero)require(x==0,"reset silence has no residue or denormals");process(d,nullptr,0,0);require(allocationWatch::count==0,"all instrumented process callbacks allocate no heap memory");
}
}
int main(){const auto start=std::chrono::steady_clock::now();basicAndProfile();learning();frequencyCalibration();correctionAndStyles();stereoAndAutomation();stress();const double elapsed=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();std::ofstream out("balance-dsp-report.json");out<<std::setprecision(12)<<"{\n\"suite\":\"GILLBALANCE DSP\",\"passed\":"<<(failures?"false":"true")<<",\"checks\":"<<checks<<",\"failures\":"<<failures<<",\"actual_audio_configurations\":"<<configurations<<",\"audio_channel_samples\":"<<samplesProcessed<<",\"process_heap_allocations\":"<<allocationWatch::count<<",\"maximum_response_error_db\":"<<maximumResponseError<<",\"maximum_static_response_magnitude_db\":"<<maximumStaticResponse<<",\"colored_vocal_local_bulge_before_db\":"<<preColorDb<<",\"colored_vocal_local_bulge_after_estimated_db\":"<<postColorDb<<",\"maximum_rapid_automation_error_sample_step\":"<<maximumAutomationErrorStep<<",\"maximum_random_output\":"<<maximumOutput<<",\"elapsed_seconds\":"<<elapsed<<",\"scope\":\"Deterministic synthetic audio and independent analytical checks; no real-speaker listening or trained reference model\"\n}\n";std::cout<<checks<<" checks, "<<failures<<" failures, "<<samplesProcessed<<" channel samples, "<<elapsed<<" seconds\n";return failures?1:0;}
