#include "PluginProcessor.h"
#include "PluginEditor.h"
juce::AudioProcessorValueTreeState::ParameterLayout GillNoteProcessor::layout(){juce::AudioProcessorValueTreeState::ParameterLayout p;p.add(std::make_unique<juce::AudioParameterChoice>(juce::ParameterID{"key",1},"KEY",juce::StringArray{"C","C#","D","D#","E","F","F#","G","G#","A","A#","B"},0));p.add(std::make_unique<juce::AudioParameterChoice>(juce::ParameterID{"scale",1},"SCALE",juce::StringArray{"CHROMATIC","MAJOR","MINOR"},0));p.add(std::make_unique<juce::AudioParameterBool>(juce::ParameterID{"formant",1},"PRESERVE FORMANTS",true));p.add(std::make_unique<juce::AudioParameterBool>(juce::ParameterID{"bypass",1},"BYPASS",false));p.add(gill::qualityParameter(0));return p;}
GillNoteProcessor::GillNoteProcessor():AudioProcessor(BusesProperties().withInput("INPUT",juce::AudioChannelSet::stereo(),true).withOutput("OUTPUT",juce::AudioChannelSet::stereo(),true)),apvts(*this,nullptr,"GILLNOTE",layout()){bypass=apvts.getRawParameterValue("bypass");setLatencySamples(0);}
float GillNoteProcessor::value(const char*id)const{auto*p=apvts.getRawParameterValue(id);return p?p->load():0;}
void GillNoteProcessor::setValue(const char*id,float v){if(auto*p=apvts.getParameter(id)){p->beginChangeGesture();p->setValueNotifyingHost(p->convertTo0to1(v));p->endChangeGesture();}}
void GillNoteProcessor::prepareToPlay(double fs,int){engine.prepare(fs,getTotalNumOutputChannels());setLatencySamples(0);}
bool GillNoteProcessor::isBusesLayoutSupported(const BusesLayout&b)const{return b.getMainInputChannelSet()==b.getMainOutputChannelSet()&&(b.getMainOutputChannelSet()==juce::AudioChannelSet::mono()||b.getMainOutputChannelSet()==juce::AudioChannelSet::stereo());}
void GillNoteProcessor::processBlock(juce::AudioBuffer<float>&b,juce::MidiBuffer&){process(b,bypass->load()>.5f);}void GillNoteProcessor::processBlockBypassed(juce::AudioBuffer<float>&b,juce::MidiBuffer&){process(b,true);}
void GillNoteProcessor::process(juce::AudioBuffer<float>&b,bool bypassed){juce::ScopedNoDenormals guard;for(int c=getTotalNumInputChannels();c<b.getNumChannels();++c)b.clear(c,0,b.getNumSamples());if(!b.getNumChannels())return;bool playing=false,valid=false;std::int64_t position=0;if(auto*h=getPlayHead())if(auto info=h->getPosition()){playing=info->getIsPlaying();if(auto samples=info->getTimeInSamples()){position=*samples;valid=true;}else if(auto seconds=info->getTimeInSeconds()){valid=std::isfinite(*seconds)&&std::abs(*seconds)<1.e9;if(valid)position=std::int64_t(std::llround(*seconds*engine.rateView.load()));}}engine.process(b,playing,valid,position,quality.mode()==gill::liveQuality,bypassed);}
void GillNoteProcessor::audition(double start){setValue("gillQuality",1);engine.audition(start);}
void GillNoteProcessor::getStateInformation(juce::MemoryBlock&block){auto t=apvts.copyState();auto saved=engine.saved();t.setProperty("schema",1,nullptr);t.setProperty("cache",saved.token,nullptr);t.setProperty("start",saved.start,nullptr);auto old=t.getChildWithName("NOTES");if(old.isValid())t.removeChild(old,nullptr);juce::ValueTree notes("NOTES");for(auto&n:saved.notes){juce::ValueTree e("NOTE");e.setProperty("id",n.id,nullptr);e.setProperty("a",n.start,nullptr);e.setProperty("b",n.end,nullptr);e.setProperty("detected",n.detected,nullptr);e.setProperty("target",n.target,nullptr);e.setProperty("strength",n.strength,nullptr);notes.appendChild(e,nullptr);}t.appendChild(notes,nullptr);if(auto xml=t.createXml())copyXmlToBinary(*xml,block);}
void GillNoteProcessor::setStateInformation(const void*data,int size){if(!data||size<1||size>4*1024*1024)return;auto xml=getXmlFromBinary(data,size);if(!xml||!xml->hasTagName("GILLNOTE"))return;auto t=juce::ValueTree::fromXml(*xml);if(int(t.getProperty("schema",0))!=1)return;for(auto child:t)if(child.hasType("PARAM")){auto*p=apvts.getParameter(child.getProperty("id").toString());double v=child.getProperty("value");if(!p||!std::isfinite(v)||v<p->getNormalisableRange().start||v>p->getNormalisableRange().end)return;}
 auto token=t.getProperty("cache").toString();double start=t.getProperty("start",0);if(!std::isfinite(start)||std::abs(start)>1.e9||(!token.isEmpty()&&!gill::note::Engine::validToken(token)))return;auto items=t.getChildWithName("NOTES");if(items.getNumChildren()>6000)return;std::vector<gill::note::Note>notes;double previous=0;int previousId=-1;for(auto e:items){gill::note::Note n;n.id=e.getProperty("id");n.start=e.getProperty("a");n.end=e.getProperty("b");n.detected=float(e.getProperty("detected"));n.target=float(e.getProperty("target"));n.strength=float(e.getProperty("strength"));if(n.id<=previousId||!std::isfinite(n.start)||!std::isfinite(n.end)||!std::isfinite(n.detected)||!std::isfinite(n.target)||!std::isfinite(n.strength)||n.start<previous||n.end<=n.start||n.end>300||n.detected<20||n.detected>110||std::abs(n.target-n.detected)>24||n.strength<0||n.strength>1)return;previous=n.end;previousId=n.id;notes.push_back(n);}apvts.replaceState(t);engine.preserveFormants=value("formant")>.5f;if(token.isEmpty())engine.clear();else engine.restore(token,start,notes);
}
juce::AudioProcessorEditor*GillNoteProcessor::createEditor(){return new GillNoteEditor(*this);}
