#include "PluginEditor.h"
#include "GillPlatform.h"
#include "BinaryData.h"
#include "../../GILLCommon/QualityUi.h"
#include "../../GILLCommon/MaterialUi.h"
namespace{
const juce::Colour ink(0xff293d31),sage(0xff6b8b73),cream(0xfff4efdf),dark(0xff243b31);
juce::Font font(float h,bool bold=false){return juce::Font(juce::FontOptions(gillInterfaceFontName(),h,bold?juce::Font::bold:juce::Font::plain));}
class Look:public juce::LookAndFeel_V4{
public:Look(){setColour(juce::Slider::textBoxTextColourId,ink);setColour(juce::Slider::textBoxBackgroundColourId,cream);setColour(juce::Slider::textBoxOutlineColourId,juce::Colours::transparentBlack);setColour(juce::ComboBox::backgroundColourId,cream);setColour(juce::ComboBox::textColourId,ink);setColour(juce::ComboBox::outlineColourId,sage);setColour(juce::ComboBox::arrowColourId,ink);setColour(juce::PopupMenu::backgroundColourId,cream);setColour(juce::PopupMenu::textColourId,ink);setColour(juce::PopupMenu::highlightedBackgroundColourId,sage);setColour(juce::TooltipWindow::backgroundColourId,cream);setColour(juce::TooltipWindow::textColourId,ink);}
    juce::Font getTextButtonFont(juce::TextButton&,int)override{return font(12,true);}juce::Font getComboBoxFont(juce::ComboBox&)override{return font(12,true);}
    void drawButtonBackground(juce::Graphics&g,juce::Button&b,const juce::Colour&,bool over,bool down)override{
        auto r=b.getLocalBounds().toFloat().reduced(1);const auto base=b.getToggleState()?sage:(b.getName()=="LEARN"?juce::Colour(0xffc9a675):cream);gill::material::panel(g,r,base,8,down);if(over){g.setColour(juce::Colours::white.withAlpha(.09f));g.fillRoundedRectangle(r,8);}b.setColour(juce::TextButton::textColourOffId,ink);b.setColour(juce::TextButton::textColourOnId,cream);
    }
    void drawRotarySlider(juce::Graphics&g,int x,int y,int w,int h,float v,float a,float z,juce::Slider&)override{gill::material::rotary(g,juce::Rectangle<float>(static_cast<float>(x),static_cast<float>(y),static_cast<float>(w),static_cast<float>(h)).reduced(4),v,a,z,sage);}
    void drawLinearSlider(juce::Graphics&g,int x,int y,int w,int h,float p,float,float,const juce::Slider::SliderStyle,juce::Slider&)override{const float cy=y+h*.5f;g.setColour(ink.withAlpha(.2f));g.fillRoundedRectangle(static_cast<float>(x),cy-2,static_cast<float>(w),4,2);g.setColour(sage);g.fillRoundedRectangle(static_cast<float>(x),cy-2,std::max(0.f,p-x),4,2);gill::material::disc(g,juce::Rectangle<float>(12,12).withCentre({p,cy}));}
};
struct Dial{juce::Slider slider;juce::Label label;std::unique_ptr<juce::AudioProcessorValueTreeState::SliderAttachment>attachment;
    Dial(GillCreativeProcessor&p,const char*id,const juce::String&caption,const juce::String&suffix){slider.setName(caption);slider.setComponentID(id);slider.setColour(juce::Slider::textBoxTextColourId,ink);slider.setColour(juce::Slider::textBoxBackgroundColourId,cream);slider.setColour(juce::Slider::textBoxOutlineColourId,sage.withAlpha(.35f));slider.setSliderStyle(juce::Slider::Rotary);slider.setTextBoxStyle(juce::Slider::TextBoxBelow,false,84,22);slider.setTextValueSuffix(suffix);auto*parameter=p.apvts.getParameter(id);slider.setDoubleClickReturnValue(true,parameter->convertFrom0to1(parameter->getDefaultValue()));attachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.apvts,id,slider);label.setText(caption,juce::dontSendNotification);label.setFont(font(11.5f,true));label.setColour(juce::Label::textColourId,ink);label.setJustificationType(juce::Justification::centred);}
};
class ExportDrag final:public juce::TextButton{
public:explicit ExportDrag(GillCreativeProcessor&v):juce::TextButton("DRAG WAV"),p(v){setComponentID("dragWav");setTooltip("DRAG THE RENDERED WAV INTO THE PLAYLIST AT THE CAPTURE START. THE FILE STAYS IN DOCUMENTS / JILL PLUGINS / AUDIO.");}
void mouseDown(const juce::MouseEvent&e)override{dragged=false;juce::TextButton::mouseDown(e);}
void mouseDrag(const juce::MouseEvent&e)override{if(!dragged&&e.getDistanceFromDragStart()>5){const auto file=p.renderer.file();if(file.existsAsFile()){dragged=juce::DragAndDropContainer::performExternalDragDropOfFiles({file.getFullPathName()},false,this);}}}
private:GillCreativeProcessor&p;bool dragged=false;
};
class Timeline:public juce::Component,public juce::SettableTooltipClient{
public:explicit Timeline(GillCreativeProcessor&v):p(v){setComponentID("creativeTimeline");setTooltip("MARKER ZIEHEN: ZEIT UND EFFEKTSTAERKE. IN / OUT UNTEN EDITIEREN DEN ORIGINALAUSSCHNITT. KEINE WORTERKENNUNG.");}
    void refresh(){if(!dragging)model=p.plan();selected=std::clamp(selected,0,std::max(0,model.count-1));repaint();}
    void paint(juce::Graphics&g)override{
        auto r=getLocalBounds().toFloat();gill::material::panel(g,r.reduced(1),dark,13,true);g.setFont(font(11,true));g.setColour(cream.withAlpha(.8f));
        const juce::String title=p.kind==CreativeKind::Phrase?"PHRASE ENDS / REVERB SEND":p.kind==CreativeKind::Director?"VOCAL MAP / OWN FX RACK":"CAPTURED VOICE / CHOP MAP";
        g.drawText(title,14,8,getWidth()-220,20,juce::Justification::left);g.drawText(juce::String(p.tempo.load(),1)+" BPM  /  0 SAMPLES",getWidth()-212,8,196,20,juce::Justification::right);
        auto a=area();for(int i=0;i<=8;++i){const float x=a.getX()+a.getWidth()*i/8;g.setColour(cream.withAlpha(.08f));g.drawVerticalLine(static_cast<int>(x),a.getY(),a.getBottom());}
        if(model.valid()){
            juce::Graphics::ScopedSaveState clip(g);g.reduceClipRegion(a.toNearestInt());juce::Path wave;for(int i=0;i<gill::creative::wavePoints;++i){const float x=xFor(static_cast<float>(i)*model.durationBeats/(gill::creative::wavePoints-1)),v=std::min(1.f,std::sqrt(model.waveform[i])*1.7f);g.setColour(cream.withAlpha(.23f));g.drawVerticalLine(static_cast<int>(x),a.getCentreY()-v*a.getHeight()*.35f,a.getCentreY()+v*a.getHeight()*.35f);}
            for(int i=0;i<model.count;++i){const auto&m=model.markers[i];const float start=xFor(m.startBeat),end=xFor(m.endBeat);if(end<a.getX()||start>a.getRight())continue;const float y=a.getBottom()-m.strength*a.getHeight();g.setColour(sage.withAlpha(i==selected?.35f:.15f));g.fillRoundedRectangle(start,a.getY(),std::max(3.f,end-start),a.getHeight(),3);g.setColour(i==selected?cream:sage.brighter(.4f));g.drawVerticalLine(static_cast<int>(end),a.getY(),a.getBottom());g.fillEllipse(end-5,y-5,10,10);g.setFont(font(10,true));if(end-start>24)g.drawText(juce::String(i+1),static_cast<int>(start)+3,static_cast<int>(a.getY())+2,24,15,juce::Justification::left);}
            g.setColour(cream.withAlpha(.55f));const float play=xFor(p.engine.currentPosition()*model.durationBeats);g.drawVerticalLine(static_cast<int>(play),a.getY(),a.getBottom());
        }else{g.setColour(cream.withAlpha(.65f));g.setFont(font(15));g.drawText(p.engine.learningState()==1?"LISTENING  "+juce::String(p.engine.duration(),1)+" S":"PLAY VOCAL + LEARN",a,juce::Justification::centred);}
        g.setFont(font(10,true));g.setColour(cream.withAlpha(.65f));g.drawText(model.valid()?juce::String(model.count)+" MARKERS / "+juce::String(model.durationSeconds,1)+" S":"MAX 5 MIN / WHEEL = ZOOM / DOUBLE CLICK = FULL SONG",14,getHeight()-21,getWidth()-28,15,juce::Justification::left);
    }
    void mouseDown(const juce::MouseEvent&e)override{if(!model.valid())return;float distance=1.e9f;for(int i=0;i<model.count;++i){const float d=std::abs(xFor(model.markers[i].endBeat)-e.position.x);if(d<distance){distance=d;selected=i;}}dragging=true;if(onSelect)onSelect();repaint();}
    void mouseDrag(const juce::MouseEvent&e)override{if(!dragging||!model.valid())return;auto&m=model.markers[selected];const auto a=area();const float end=(viewStart+std::clamp((e.position.x-a.getX())/a.getWidth(),0.f,1.f)*viewLength)*model.durationBeats;const float next=selected+1<model.count?model.markers[selected+1].startBeat-.01f:model.durationBeats;m.endBeat=std::clamp(end,m.startBeat+.01f,std::max(m.startBeat+.01f,next));m.strength=std::clamp((a.getBottom()-e.position.y)/a.getHeight(),0.f,1.f);repaint();}
    void mouseUp(const juce::MouseEvent&)override{if(dragging){dragging=false;p.editPlan(model,p.engine.isApplied());if(onSelect)onSelect();}}
    void mouseWheelMove(const juce::MouseEvent&e,const juce::MouseWheelDetails&w)override{const auto a=area();const float at=std::clamp((e.position.x-a.getX())/a.getWidth(),0.f,1.f);const float old=viewLength;viewLength=std::clamp(viewLength*(w.deltaY>0?.78f:1.28f),.02f,1.f);viewStart=std::clamp(viewStart+at*(old-viewLength),0.f,1.f-viewLength);repaint();}
    void mouseDoubleClick(const juce::MouseEvent&)override{viewStart=0;viewLength=1;repaint();}
    int selected=0;gill::creative::Plan model;std::function<void()>onSelect;
private:juce::Rectangle<float>area()const{return getLocalBounds().toFloat().reduced(15).withTrimmedTop(19).withTrimmedBottom(17);}float xFor(float beat)const{const auto a=area();return a.getX()+(beat/std::max(.01f,model.durationBeats)-viewStart)/viewLength*a.getWidth();}GillCreativeProcessor&p;bool dragging=false;float viewStart=0,viewLength=1;
};
}
struct GillCreativeEditor::Impl:private juce::Timer{
    GillCreativeEditor&owner;GillCreativeProcessor&p;Look look;juce::Image wood;Timeline timeline;gill::QualitySelector quality;
    juce::TextButton renderFx{"RENDER FX"},renderMix{"RENDER MIX"};ExportDrag dragWav;juce::TextButton learn{"LEARN"},apply{"APPLY"},undo{"UNDO"},preview{"PREVIEW"},bypass{"BYPASS"},previous{"<"},next{">"};std::array<juce::TextButton,3>variants;
    juce::ComboBox preset;juce::Label status;std::array<juce::Slider,3>trim;std::array<juce::Label,3>trimLabel;
    std::vector<std::unique_ptr<Dial>>dials;std::unique_ptr<juce::AudioProcessorValueTreeState::ButtonAttachment>bypassAttachment;bool updating=false;int width=720,height=460;
    Impl(GillCreativeEditor&o,GillCreativeProcessor&processor):owner(o),p(processor),timeline(p),quality(p.apvts,p),dragWav(p){
        if(p.kind==CreativeKind::Director){width=760;height=480;}owner.setLookAndFeel(&look);wood=juce::ImageCache::getFromMemory(BinaryData::core_reference_png,BinaryData::core_reference_pngSize);
        owner.addAndMakeVisible(timeline);owner.addAndMakeVisible(quality);owner.addAndMakeVisible(status);status.setFont(font(11,true));status.setColour(juce::Label::textColourId,ink);
        for(auto*button:{&learn,&apply,&undo,&preview,&bypass,&previous,&next,&renderFx,&renderMix}){button->setName(button->getButtonText());button->setComponentID(button->getButtonText().toLowerCase());owner.addAndMakeVisible(button);}
        owner.addAndMakeVisible(dragWav);renderFx.setComponentID("renderFx");renderMix.setComponentID("renderMix");renderFx.onClick=[this]{p.renderEffects(true);};renderMix.onClick=[this]{p.renderEffects(false);};renderFx.setTooltip("RENDER THE EFFECTS WITHOUT THE DRY VOCAL. INCLUDES TAILS. DRAG THE FINISHED WAV INTO YOUR PLAYLIST.");renderMix.setTooltip("RENDER THE COMPLETE VOCAL WITH THE CURRENT DRY/WET SETTINGS. ORIGINAL AUDIO IS KEPT.");
        learn.onClick=[this]{if(p.engine.learningState()==1||p.engine.learningState()==5)p.stopLearn();else p.startLearn();};apply.onClick=[this]{p.applyLearn();};undo.onClick=[this]{p.undoLearn();};preview.setClickingTogglesState(true);preview.onClick=[this]{p.audition(preview.getToggleState());};
        bypass.setClickingTogglesState(true);bypassAttachment=std::make_unique<juce::AudioProcessorValueTreeState::ButtonAttachment>(p.apvts,"bypass",bypass);
        const char*variantNames[3][3]={{"FOCUS","BLOOM","WIDE"},{"FRONT","LIFT","MOTION"},{"SINGLE","DOUBLE","TRIPLE"}};
        for(int i=0;i<3;++i){auto&b=variants[i];b.setButtonText(variantNames[static_cast<int>(p.kind)][i]);b.setName("VARIANT "+juce::String(i+1));b.setComponentID("variant"+juce::String(i));b.onClick=[this,i]{p.setValue("variant",static_cast<float>(i));p.audition(true);preview.setToggleState(true,juce::dontSendNotification);};owner.addAndMakeVisible(b);}
        auto add=[&](const char*id,const char*label,const char*suffix){auto dial=std::make_unique<Dial>(p,id,label,suffix);owner.addAndMakeVisible(dial->slider);owner.addAndMakeVisible(dial->label);dials.push_back(std::move(dial));};
        add("amount",p.kind==CreativeKind::Reply?"DENSITY":p.kind==CreativeKind::Director?"INTENSITY":"THROW"," %");add("length",p.kind==CreativeKind::Reply?"CHOP":"TAIL"," S");add("tone","TONE"," %");add("width","WIDTH"," %");add("mix","WET"," %");add("dry","DRY"," %");add("sensitivity","DETECT"," DB");
        const char*labels[]{p.kind==CreativeKind::Reply?"SOURCE IN":"START BEAT",p.kind==CreativeKind::Reply?"SOURCE OUT":"END BEAT","MARKER LEVEL"};for(int i=0;i<3;++i){trimLabel[i].setText(labels[i],juce::dontSendNotification);trimLabel[i].setFont(font(10,true));trimLabel[i].setColour(juce::Label::textColourId,ink);owner.addAndMakeVisible(trimLabel[i]);auto&s=trim[i];s.setColour(juce::Slider::textBoxTextColourId,ink);s.setColour(juce::Slider::textBoxBackgroundColourId,cream);s.setColour(juce::Slider::textBoxOutlineColourId,sage.withAlpha(.3f));s.setSliderStyle(juce::Slider::LinearHorizontal);s.setTextBoxStyle(juce::Slider::TextBoxRight,false,62,20);s.setName(labels[i]);s.setComponentID("marker"+juce::String(i));s.setRange(0,i==2?100:p.kind==CreativeKind::Reply?300:2000,.01);owner.addAndMakeVisible(s);s.onValueChange=[this,i]{if(updating||!timeline.model.valid())return;auto&model=timeline.model;auto&m=model.markers[timeline.selected];if(i==0){if(p.kind==CreativeKind::Reply)m.startSec=std::clamp(static_cast<float>(trim[i].getValue()),0.f,m.endSec-.01f);else m.startBeat=std::clamp(static_cast<float>(trim[i].getValue()),timeline.selected>0?model.markers[timeline.selected-1].endBeat:0.f,m.endBeat-.01f);}else if(i==1){if(p.kind==CreativeKind::Reply)m.endSec=std::clamp(static_cast<float>(trim[i].getValue()),m.startSec+.01f,model.durationSeconds);else m.endBeat=std::clamp(static_cast<float>(trim[i].getValue()),m.startBeat+.01f,timeline.selected+1<model.count?model.markers[timeline.selected+1].startBeat:model.durationBeats);}else m.strength=static_cast<float>(trim[i].getValue())/100;p.editPlan(model,p.engine.isApplied());};}
        timeline.onSelect=[this]{syncTrims();};preset.setName("PRESET");preset.setComponentID("preset");for(int i=0;i<p.getNumPrograms();++i)preset.addItem(p.getProgramName(i),i+1);preset.onChange=[this]{if(preset.getSelectedId()>0)p.selectPreset(preset.getSelectedId()-1);};owner.addAndMakeVisible(preset);previous.onClick=[this]{p.selectPreset((p.getCurrentProgram()+5)%6);preset.setSelectedId(p.getCurrentProgram()+1,juce::dontSendNotification);};next.onClick=[this]{p.selectPreset((p.getCurrentProgram()+1)%6);preset.setSelectedId(p.getCurrentProgram()+1,juce::dontSendNotification);};
        learn.setTooltip("LEARN ARMS RECORDING. PLAY THE WHOLE SONG (UP TO 5 MIN). STOP IN THE HOST OR HERE KEEPS THE TAKE. MARKERS ARE SIGNAL-BASED, NOT WORD TRANSCRIPTION.");apply.setTooltip("GEPRUEFTEN VERLAUF AKTIVIEREN. HOST-PPQ SYNCHRONISIERT DIE GELERNTEN MARKER.");undo.setTooltip("VORHERIGEN ANGEWENDETEN VERLAUF WIEDERHERSTELLEN. NEUES LEARN STARTET EINEN NEUEN TAKE.");preview.setTooltip("AUSWAHL VORHOEREN. PHRASE/DIRECTOR BRAUCHEN WEITERHIN DIE LAUFENDE ORIGINALVOCAL; REPLY SPIELT AUCH GESPEICHERTE CHOPS.");startTimerHz(20);timerCallback();
    }
    ~Impl(){stopTimer();owner.setLookAndFeel(nullptr);}
    void syncTrims(){updating=true;const auto&plan=timeline.model;const bool enabled=plan.valid();for(auto&s:trim)s.setEnabled(enabled);if(enabled){const auto&m=plan.markers[timeline.selected];trim[0].setValue(p.kind==CreativeKind::Reply?m.startSec:m.startBeat,juce::dontSendNotification);trim[1].setValue(p.kind==CreativeKind::Reply?m.endSec:m.endBeat,juce::dontSendNotification);trim[2].setValue(m.strength*100,juce::dontSendNotification);}updating=false;}
    void timerCallback()override{timeline.refresh();renderFx.setEnabled(p.canRender());renderMix.setEnabled(p.canRender());dragWav.setEnabled(!p.renderer.busy()&&p.renderer.file().existsAsFile());syncTrims();const int state=p.engine.learningState();preview.setToggleState(p.engine.isPreviewing(),juce::dontSendNotification);learn.setButtonText(state==1||state==5?"STOP":"LEARN");apply.setEnabled(state==2||state==3);undo.setEnabled(p.engine.isApplied());for(int i=0;i<3;++i)variants[i].setToggleState(static_cast<int>(p.value("variant"))==i,juce::dontSendNotification);preset.setSelectedId(p.presetMatches()?p.getCurrentProgram()+1:0,juce::dontSendNotification);preset.setTextWhenNothingSelected("CUSTOM");status.setText(p.renderer.busy()?"RENDER "+juce::String(p.renderer.progress.load()*100,0)+" %":p.renderer.status==3?p.renderer.error():p.archive.status()==4?p.archive.error():!p.rateSupported?"UNSUPPORTED RATE / BYPASS":state==1?"LEARNING "+juce::String(p.engine.duration(),1)+" S":state==5?"ARMED - PRESS PLAY":state==4?"NO VOICED AUDIO - LOWER DETECT":state==3?"APPLIED / HOST TIMELINE":state==2?"3 VARIANTS READY":"LEARN THE WHOLE SONG",juce::dontSendNotification);}
    void bounds(juce::Component&c,float x,float y,float w,float h){const float s=owner.getWidth()/static_cast<float>(width);c.setBounds(juce::Rectangle<float>(x*s,y*s,w*s,h*s).toNearestInt());}
    void resized(){const float extra=height-460.f;bounds(quality,width-232.f,20,110,26);bounds(bypass,width-106.f,19,85,29);bounds(timeline,22,65,width-44.f,132+extra);bounds(learn,22,210+extra,82,28);bounds(apply,112,210+extra,68,28);bounds(undo,188,210+extra,68,28);bounds(preview,264,210+extra,86,28);
        for(int i=0;i<3;++i)bounds(variants[i],width-310.f+i*98,210+extra,90,28);const float third=(width-44.f)/3;for(int i=0;i<3;++i){bounds(trimLabel[i],22+i*third,247+extra,third-10,15);bounds(trim[i],22+i*third,263+extra,third-10,22);}const float column=(width-44.f)/7;for(int i=0;i<7;++i){bounds(dials[i]->label,22+i*column,295+extra,column-4,18);bounds(dials[i]->slider,22+i*column,313+extra,column-4,88);}bounds(renderFx,22,height-56.f,86,23);bounds(renderMix,114,height-56.f,86,23);bounds(dragWav,206,height-56.f,86,23);bounds(status,302,height-56.f,width-324.f,23);bounds(previous,22,height-32.f,28,23);bounds(preset,58,height-32.f,width-116.f,23);bounds(next,width-50.f,height-32.f,28,23);}
    void paint(juce::Graphics&g){const float s=owner.getWidth()/static_cast<float>(width),w=static_cast<float>(owner.getWidth()),h=static_cast<float>(owner.getHeight());g.fillAll(juce::Colour(0xffc3a479));if(wood.isValid()){g.drawImage(wood,0,0,owner.getWidth(),owner.getHeight(),950,285,170,805);g.setColour(cream.withAlpha(.17f));g.fillAll();g.setOpacity(1.f);g.drawImage(wood,static_cast<int>(22*s),static_cast<int>(17*s),static_cast<int>(44*s),static_cast<int>(31*s),224,146,174,122);}g.setColour(juce::Colour(0xff715b3e).withAlpha(.6f));g.drawRoundedRectangle({3*s,3*s,w-6*s,h-6*s},14*s,4*s);g.setColour(cream.withAlpha(.65f));g.drawRoundedRectangle({7*s,7*s,w-14*s,h-14*s},11*s,s);g.setColour(ink);g.setFont(font(23*s));g.drawText(p.getName(),juce::Rectangle<float>(85*s,15*s,(width-340.f)*s,28*s),juce::Justification::left);g.setFont(font(10*s,true));g.drawText("GILLPRODUCTION / CREATIVE VOCAL TOOLS",juce::Rectangle<float>(86*s,42*s,330*s,14*s),juce::Justification::left);}
};
GillCreativeEditor::GillCreativeEditor(GillCreativeProcessor&p):AudioProcessorEditor(&p){impl=std::make_unique<Impl>(*this,p);setResizable(true,true);setResizeLimits(impl->width,impl->height,impl->width*2,impl->height*2);if(auto*c=getConstrainer())c->setFixedAspectRatio(static_cast<double>(impl->width)/impl->height);setSize(impl->width,impl->height);}
GillCreativeEditor::~GillCreativeEditor()=default;void GillCreativeEditor::paint(juce::Graphics&g){impl->paint(g);}void GillCreativeEditor::resized(){if(impl)impl->resized();}
