#include "../../GILLCommon/QualityTests.h"
#include "PluginProcessor.h"
#include <fstream>
#include <iostream>
#include <chrono>
#include <memory>
#include <random>
#include <set>
#include <typeinfo>
namespace{
int checks=0,failures=0,edits=0,presetsTested=0,configs=0;std::string product;std::vector<std::string>errors;
void check(bool ok,const std::string&s){++checks;std::cout<<(ok?"PASS ":"FAIL ")<<product<<" "<<s<<'\n';if(!ok){++failures;errors.push_back(product+" "+s);}}
void prepare(GillDynamicsProcessor&p,double fs=48000,int block=128,int channels=2){p.setPlayConfigDetails(channels,channels,fs,block);p.prepareToPlay(fs,block);}
float voice(int n,double fs,int c=0){const double t=n/fs,a=.17*(.65+.35*std::sin(2*juce::MathConstants<double>::pi*2.2*t));return static_cast<float>((a*std::sin(2*juce::MathConstants<double>::pi*220*t)+.09*std::sin(2*juce::MathConstants<double>::pi*2600*t)+.025*std::sin(2*juce::MathConstants<double>::pi*7100*t)+(n%997==0?.4:0))*(c==0?1:.84));}
std::vector<float>render(GillDynamicsProcessor&p,int samples,int block=128,bool bypass=false){std::vector<float>out;out.reserve(samples);juce::AudioBuffer<float>b(p.getTotalNumOutputChannels(),block);juce::MidiBuffer m;for(int at=0;at<samples;at+=block){const int n=std::min(block,samples-at);b.setSize(b.getNumChannels(),n,false,false,true);for(int c=0;c<b.getNumChannels();++c)for(int i=0;i<n;++i)b.setSample(c,i,voice(at+i,p.uiRate.load(),c));if(bypass)p.processBlockBypassed(b,m);else p.processBlock(b,m);out.insert(out.end(),b.getReadPointer(0),b.getReadPointer(0)+n);}return out;}
std::vector<float>vals(GillDynamicsProcessor&p){std::vector<float>r;for(auto&d:p.definitions)r.push_back(p.value(d.id));return r;}
void metadata(DynKind k){auto p=std::make_unique<GillDynamicsProcessor>(k);product=p->getName().toStdString();check(p->hasEditor()&&!p->acceptsMidi()&&p->getNumPrograms()==12&&p->getBypassParameter()==p->apvts.getParameter("bypass"),"metadata, bypass and12factory programs");bool all=true;std::vector<std::vector<float>>states;for(int i=0;i<12;++i){p->setCurrentProgram(i);all&=p->getCurrentProgram()==i&&p->presetMatches();states.push_back(vals(*p));++presetsTested;prepare(*p);auto out=render(*p,12000);all&=std::all_of(out.begin(),out.end(),[](float x){return std::isfinite(x)&&std::abs(x)<100;});++configs;}for(int i=0;i<12;++i)for(int j=i+1;j<12;++j)all&=states[i]!=states[j];check(all,"every preset is distinct and processes finite audio");p->setValue(p->definitions.front().id,p->definitions.front().lo+.37f*(p->definitions.front().hi-p->definitions.front().lo),false);juce::MemoryBlock s;p->getStateInformation(s);auto q=std::make_unique<GillDynamicsProcessor>(k);q->setStateInformation(s.getData(),static_cast<int>(s.getSize()));check(vals(*p)==vals(*q)&&q->getCurrentProgram()==p->getCurrentProgram(),"all parameters and custom program round-trip");prepare(*p);prepare(*q);check(render(*p,16000,127)==render(*q,16000,127),"recalled state produces identical processed audio");const auto old=vals(*q);const char junk[]{1,2,3,0};q->setStateInformation(junk,4);check(vals(*q)==old,"malformed state leaves current controls intact");auto xml=juce::AudioProcessor::getXmlFromBinary(s.getData(),static_cast<int>(s.getSize()));auto tree=juce::ValueTree::fromXml(*xml);tree.getChild(0).setProperty("value","NaN",nullptr);juce::MemoryBlock bad;juce::AudioProcessor::copyXmlToBinary(*tree.createXml(),bad);q->setStateInformation(bad.getData(),static_cast<int>(bad.getSize()));check(vals(*q)==old,"nonfinite parameter in state is rejected");}
void routes(DynKind k){product=std::make_unique<GillDynamicsProcessor>(k)->getName().toStdString();for(double fs:{8000.,32000.,44100.,48000.,96000.,192000.}){bool exact=true,finite=true;for(int ch:{1,2})for(int route=0;route<2;++route){auto p=std::make_unique<GillDynamicsProcessor>(k);p->setValue("bypass",1,false);prepare(*p,fs,257,ch);auto out=render(*p,12000,257,route==1);const int latency=p->getLatencySamples();for(int i=0;i<static_cast<int>(out.size());++i){const float ref=i<latency?0:voice(i-latency,fs);exact&=std::abs(out[i]-ref)<2.e-6f;finite&=std::isfinite(out[i]);}++configs;}check(exact&&finite,"native/host bypass aligns mono+stereo at "+std::to_string(static_cast<int>(fs)));}
    auto p=std::make_unique<GillDynamicsProcessor>(k);prepare(*p,192001);auto out=render(*p,12000);bool passthrough=!p->rateSupported.load();for(int i=0;i<12000;++i)passthrough&=std::abs(out[i]-(i<p->getLatencySamples()?0:voice(i-p->getLatencySamples(),p->uiRate.load())))<1.e-6f;check(passthrough,"unsupported rate explicitly bypasses without invalid audio");
}
struct Head:juce::AudioPlayHead{mutable int calls=0;double bpm=93;juce::Optional<PositionInfo>getPosition()const override{++calls;PositionInfo p;p.setBpm(bpm);p.setTimeInSamples(0);return p;}};
void automation(DynKind k){auto p=std::make_unique<GillDynamicsProcessor>(k);product=p->getName().toStdString();Head h;p->setPlayHead(&h);prepare(*p);check(h.calls==0,"prepare does not query host transport");std::mt19937 random(20260925);juce::AudioBuffer<float>b(2,127);juce::MidiBuffer m;bool valid=true;const auto start=std::chrono::steady_clock::now();for(int block=0;block<600;++block){if(block%7==0)for(auto&d:p->definitions)if(juce::String(d.id)!="bypass"&&juce::String(d.id)!="delta")p->setValue(d.id,d.lo+(d.hi-d.lo)*static_cast<float>(random()%1001)/1000,false);for(int c=0;c<2;++c)for(int n=0;n<127;++n)b.setSample(c,n,voice(block*127+n,48000,c));p->processBlock(b,m);for(int c=0;c<2;++c)for(int n=0;n<127;++n)valid&=std::isfinite(b.getSample(c,n))&&std::abs(b.getSample(c,n))<100;}const auto elapsed=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();check(valid,"all controls automated together keep audio finite");std::cout<<"BENCH "<<product<<" automation_seconds="<<elapsed<<" audio_seconds="<<(600.*127/48000)<<'\n';p->setPlayHead(nullptr);}
struct Components{
    std::vector<juce::Slider*>sliders;std::vector<juce::ComboBox*>combos;std::vector<juce::Button*>buttons;
    std::vector<juce::Component*>all;
    std::vector<juce::Component::SafePointer<juce::Component>>life;
    bool allAlive()const{return std::all_of(life.begin(),life.end(),[](const auto&component){return component!=nullptr;});}
    void scan(juce::Component&c){all.push_back(&c);life.emplace_back(&c);if(auto*s=dynamic_cast<juce::Slider*>(&c))sliders.push_back(s);if(auto*x=dynamic_cast<juce::ComboBox*>(&c))combos.push_back(x);if(auto*b=dynamic_cast<juce::Button*>(&c))buttons.push_back(b);for(auto*child:c.getChildren())scan(*child);}
};
struct HostListener final:juce::AudioProcessorListener{
    int begins=0,ends=0,changes=0;bool ordered=true;std::array<int,64>depth{};
    void audioProcessorParameterChanged(juce::AudioProcessor*,int,float)override{++changes;}
    void audioProcessorChanged(juce::AudioProcessor*,const ChangeDetails&)override{}
    void audioProcessorParameterChangeGestureBegin(juce::AudioProcessor*,int i)override{++begins;if(i>=0&&i<64)ordered=ordered&&++depth[static_cast<size_t>(i)]==1;}
    void audioProcessorParameterChangeGestureEnd(juce::AudioProcessor*,int i)override{++ends;if(i>=0&&i<64)ordered=ordered&&--depth[static_cast<size_t>(i)]==0;}
    bool closed()const{return ordered&&begins==ends&&std::all_of(depth.begin(),depth.end(),[](int d){return d==0;});}
};
juce::MouseEvent mouse(juce::Component&c,juce::Point<float>pt,juce::ModifierKeys mods=juce::ModifierKeys::leftButtonModifier,int clicks=1,bool dragged=false,juce::Point<float>start={}){static juce::int64 serial=juce::Time::getCurrentTime().toMilliseconds();const juce::Time now(++serial);return{juce::Desktop::getInstance().getMainMouseSource(),pt,mods,1,0,0,0,0,&c,&c,now,dragged?start:pt,now,clicks,dragged};}
void click(juce::Button&b){auto pt=b.getLocalBounds().getCentre().toFloat();juce::Component&c=b;c.mouseDown(mouse(c,pt));c.mouseUp(mouse(c,pt,juce::ModifierKeys()));++edits;}
void tick(){juce::Thread::sleep(45);juce::Timer::callPendingTimersSynchronously();}
template<class Predicate>bool waitUi(Predicate&&condition){for(int i=0;i<10;++i){if(condition())return true;tick();}return condition();}
void ui(DynKind k){auto p=std::make_unique<GillDynamicsProcessor>(k);product=p->getName().toStdString();prepare(*p);auto editor=std::unique_ptr<juce::AudioProcessorEditor>(p->createEditor());check(editor!=nullptr,"native editor constructs");if(!editor)return;editor->setVisible(true);Components c;c.scan(*editor);HostListener listener;p->addListener(&listener);std::set<std::string>covered;juce::ComboBox*preset=nullptr;
    if(k==DynKind::Buss){
        render(*p,24000);tick();
        juce::FileOutputStream out(juce::File::getCurrentWorkingDirectory().getChildFile("GILLBUSS-UI-800x330.png"));out.setPosition(0);out.truncate();juce::PNGImageFormat png;
        check(editor->getWidth()==800&&editor->getHeight()==330&&out.openedOk()&&png.writeImageToStream(editor->createComponentSnapshot(editor->getLocalBounds()),out),"compact BUSS editor renders before opening groups");
        juce::Button* drawer=nullptr;for(auto*button:c.buttons)if(button->getComponentID()=="groupDrawer")drawer=button;
        if(drawer)click(*drawer);tick();
        bool visible=drawer&&editor->getHeight()==570;for(auto*button:c.buttons){const auto id=button->getName();if(id.length()>2&&id[0]=='g'&&id[1]>='1'&&id[1]<='8'&&p->apvts.getParameter(id))visible=visible&&button->isVisible()&&button->getParentComponent()->getLocalBounds().contains(button->getBounds());}
        check(visible,"actual GROUPS drawer opens all shared controls before individual control tests");
        // setResizeLimits replaces JUCE's ResizableCornerComponent. The old
        // snapshot contains that deleted child; rebuilding keeps every live
        // control in coverage without dereferencing the stale resize handle.
        c=Components{};c.scan(*editor);
    }
    // Reproduce the original aggregate failure before allowing a timer refresh:
    // selecting the already-selected ID does not notify ComboBox listeners.
    for(auto*box:c.combos)if(box->getName()=="PRESET"&&!c.sliders.empty()){auto*first=c.sliders.front();auto*param=p->apvts.getParameter(first->getComponentID());if(param){first->setValue(param->convertFrom0to1(.31f),juce::sendNotificationSync);const bool modified=!p->presetMatches();const int id=box->getSelectedId();box->setSelectedId(id,juce::sendNotificationSync);std::cout<<"DIAG "<<product<<" original_same_preset_noop="<<(modified&&!p->presetMatches())<<" selected_id="<<id<<'\n';p->selectPreset(0,false);}}
    // Exercise the manual rate control with SYNC off. A host-owned tempo is tested separately.
    p->setValue("sync",0,false);tick();
    for(auto*s:c.sliders){const auto id=s->getComponentID();auto*param=p->apvts.getParameter(id);const auto label=id.toStdString();check(param!=nullptr&&!id.isEmpty(),label+" slider binds to an actual parameter");if(!param)continue;covered.insert(label);const auto&range=param->getNormalisableRange();check(s->getMinimum()==range.start&&s->getMaximum()==range.end&&s->isEnabled(),label+" slider exposes the full enabled parameter range");
        auto matches=[&]{return std::abs(param->getValue()-param->convertTo0to1(static_cast<float>(s->getValue())))<2.e-6f;};
        s->setValue(param->convertFrom0to1(.31f),juce::sendNotificationSync);++edits;check(matches(),label+" synchronous slider value reaches the processor");
        const auto layout=s->getLookAndFeel().getSliderLayout(*s);const auto center=layout.sliderBounds.toFloat().getCentre();const auto radius=std::min(layout.sliderBounds.getWidth(),layout.sliderBounds.getHeight())*.41f;const bool vertical=s->getSliderStyle()==juce::Slider::LinearVertical;const auto centre=center+(vertical?juce::Point<float>(0,radius):juce::Point<float>(-radius,0));const auto finish=center+(vertical?juce::Point<float>(0,-radius):juce::Point<float>(radius,0));const float dragBefore=p->value(id);int began=listener.begins,ended=listener.ends;if(s->getSliderStyle()!=juce::Slider::IncDecButtons){s->mouseDown(mouse(*s,centre));s->mouseDrag(mouse(*s,finish,juce::ModifierKeys::leftButtonModifier,1,true,centre));s->mouseUp(mouse(*s,finish,juce::ModifierKeys(),1,true,centre));++edits;check(p->value(id)!=dragBefore&&matches()&&listener.begins==began+1&&listener.ends==ended+1,label+" actual mouse drag changes parameter with one balanced gesture");}else{juce::Button*plus=nullptr;for(auto*child:s->getChildren())if(auto*b=dynamic_cast<juce::Button*>(child))if(b->getButtonText()=="+")plus=b;if(plus)click(*plus);check(plus&&p->value(id)>dragBefore,label+" actual increment button changes crossover");}
        p->setValue(id,param->convertFrom0to1(.4f),false);const float wheelBefore=p->value(id);began=listener.begins;ended=listener.ends;juce::MouseWheelDetails w{};w.deltaY=.2f;s->mouseWheelMove(mouse(*s,centre,juce::ModifierKeys()),w);++edits;check(p->value(id)>wheelBefore&&matches()&&listener.begins==began+1&&listener.ends==ended+1,label+" actual unpressed mouse wheel changes parameter with balanced gesture");
        const float keyBefore=p->value(id);began=listener.begins;ended=listener.ends;const bool handled=s->keyPressed(juce::KeyPress(juce::KeyPress::rightKey));++edits;check(handled&&p->value(id)>keyBefore&&matches()&&listener.begins==began+1&&listener.ends==ended+1,label+" arrow key changes parameter with balanced gesture");
        juce::Label*valueLabel=nullptr;for(auto*child:s->getChildren())if(auto*x=dynamic_cast<juce::Label*>(child))valueLabel=x;const float entered=range.snapToLegalValue(param->convertFrom0to1(.21f));if(valueLabel)valueLabel->setText(juce::String(entered,6),juce::sendNotificationSync);++edits;check(valueLabel&&std::abs(p->value(id)-entered)<std::max(.0001f,range.interval*.01f)&&matches(),label+" editable numeric value reaches the processor");
        p->setValue(id,range.end,false);s->mouseDoubleClick(mouse(*s,centre,juce::ModifierKeys::leftButtonModifier,2));++edits;check(std::abs(param->getValue()-param->getDefaultValue())<2.e-6f&&matches(),label+" actual double click restores the parameter default");
        if(s->getSliderStyle()==juce::Slider::IncDecButtons){
            for(auto*child:s->getChildren())if(auto*button=dynamic_cast<juce::Button*>(child)){
                p->setValue(id,param->convertFrom0to1(.7f),false);
                const auto pt=button->getLocalBounds().getCentre().toFloat();juce::Component& target=*button;
                target.mouseDown(mouse(target,pt));target.mouseUp(mouse(target,pt,juce::ModifierKeys()));
                const int beganChild=listener.begins,endedChild=listener.ends;
                p->setValue(id,param->convertFrom0to1(.7f),false);
                const float before=p->value(id);const bool startedAway=std::abs(param->getValue()-param->getDefaultValue())>2e-6f&&matches();
                target.mouseDown(mouse(target,pt,juce::ModifierKeys::leftButtonModifier,2));
                target.mouseDoubleClick(mouse(target,pt,juce::ModifierKeys::leftButtonModifier,2));
                target.mouseUp(mouse(target,pt,juce::ModifierKeys(),2));++edits;
                const bool defaultRestored=std::abs(param->getValue()-param->getDefaultValue())<2e-6f&&matches();
                const bool balanced=listener.begins>beganChild&&listener.begins-beganChild==listener.ends-endedChild&&listener.closed();
                std::cout<<"DIAG "<<product<<' '<<label<<' '<<button->getButtonText()<<" child_type="<<typeid(*button).name()<<" parent_is_slider="<<(button->getParentComponent()==s)<<" enabled="<<button->isEnabled()<<" reset_enabled="<<s->isDoubleClickReturnEnabled()<<" before="<<before<<" after="<<p->value(id)<<" default="<<s->getDoubleClickReturnValue()<<" began="<<(listener.begins-beganChild)<<" ended="<<(listener.ends-endedChild)<<" started_away="<<startedAway<<" restored="<<defaultRestored<<" balanced="<<balanced<<'\n';
                check(startedAway&&defaultRestored&&balanced,label+" real "+button->getButtonText().toStdString()+" child double click resets with balanced host gestures");
            }
        }
        began=listener.begins;ended=listener.ends;p->setValue(id,param->convertFrom0to1(.63f),false);check(matches()&&listener.begins==began&&listener.ends==ended,label+" host automation updates slider without echo gesture");
    }
    for(auto*b:c.combos){if(b->getName()=="PRESET"){preset=b;continue;}const auto id=b->getComponentID();auto*param=p->apvts.getParameter(id);check(param!=nullptr&&!id.isEmpty(),id.toStdString()+" choice binds to an actual parameter");if(!param)continue;covered.insert(id.toStdString());b->setSelectedItemIndex(b->getNumItems()-1,juce::sendNotificationSync);for(int index=0;index<b->getNumItems();++index){const int began=listener.begins,ended=listener.ends;b->setSelectedItemIndex(index,juce::sendNotificationSync);++edits;check(p->value(id)==index&&listener.begins==began+1&&listener.ends==ended+1,id.toStdString()+" choice "+b->getItemText(index).toStdString()+" reaches processor with balanced gesture");}}
    for(auto*b:c.buttons){const auto name=b->getName();if(b->getProperties().contains("choiceIndex")){const int index=b->getProperties()["choiceIndex"];const int began=listener.begins,ended=listener.ends;click(*b);check(waitUi([&]{return p->value(name)==index;})&&listener.begins==began+1&&listener.ends==ended+1,name.toStdString()+" actual segment selects choice with balanced gesture");covered.insert(name.toStdString());}if(p->apvts.getParameter(name)&&b->getClickingTogglesState()){covered.insert(name.toStdString());const auto before=p->value(name);const int began=listener.begins,ended=listener.ends;click(*b);const bool on=waitUi([&]{return p->value(name)!=before&&b->getToggleState()==(p->value(name)>.5f);});click(*b);const bool back=waitUi([&]{return p->value(name)==before&&b->getToggleState()==(before>.5f);});check(on&&back&&listener.begins==began+2&&listener.ends==ended+2,name.toStdString()+" actual button clicks toggle and restore with balanced gestures");}}
    const bool childrenAlive=c.allAlive();check(childrenAlive,"component inventory retains only live children after structural resize");
    if(!childrenAlive){p->removeListener(&listener);return;}
    for(auto*component:c.all)if(auto*l=dynamic_cast<juce::Label*>(component)){const auto id=l->getComponentID();if((id=="x"||id=="distance")&&l->isEditable()){const auto v=id=="x"?.3f:.6f;l->setText(juce::String(v*100,3),juce::sendNotificationSync);check(std::abs(p->value(id)-v)<.002f,id.toStdString()+" spatial numeric edit reaches processor");covered.insert(id.toStdString());}}
    bool complete=true;for(const auto&d:p->definitions)complete=complete&&covered.count(d.id)==1;check(complete&&covered.size()==p->definitions.size(),"every declared parameter has an individually exercised visible control");
    check(preset!=nullptr,"bottom factory preset selector exists");if(preset){if(!c.sliders.empty())c.sliders.front()->setValue(p->apvts.getParameter(c.sliders.front()->getComponentID())->convertFrom0to1(.83f),juce::sendNotificationSync);check(waitUi([&]{return preset->getText().contains("*")&&!p->presetMatches();}),"edited preset displays its custom marker after the real UI timer");const int current=p->getCurrentProgram();preset->setSelectedId(current+1,juce::sendNotificationSync);++edits;check(p->getCurrentProgram()==current&&p->presetMatches(),"selecting the visibly modified current preset restores factory values");
        for(int i=1;i<=12;++i){if(preset->getSelectedId()==i)preset->setSelectedId(i==12?1:12,juce::sendNotificationSync);preset->setSelectedId(i,juce::sendNotificationSync);++edits;check(p->getCurrentProgram()==i-1&&p->presetMatches(),"actual preset selection "+std::to_string(i)+" loads matching factory parameters");}}
    for(const char*text:{"<",">"}){juce::Button*arrow=nullptr;for(auto*b:c.buttons)if(b->getButtonText()==text)arrow=b;const int before=p->getCurrentProgram(),wanted=(before+(text[0]=='<'?11:1))%12;if(arrow)click(*arrow);check(arrow&&waitUi([&]{return p->getCurrentProgram()==wanted&&p->presetMatches()&&preset&&preset->getText()==p->getProgramName(wanted);}),std::string("actual preset ")+text+" button loads the adjacent program and updates the selector");}
    if(k==DynKind::Quad){
        juce::Component* graph=nullptr;for(auto*x:c.all)if(x->getComponentID()=="quadGraph")graph=x;check(graph!=nullptr,"live response graph exists");if(graph){p->selectPreset(11,false);prepare(*p);render(*p,24000);tick();auto point=[&](float hz){return juce::Point<float>(44+std::log(hz/20.f)/std::log(1000.f)*(graph->getWidth()-88),40);};for(const auto&entry:std::array<std::pair<const char*,float>,3>{{{"cross1",240},{"cross2",1800},{"cross3",7500}}}){const auto start=point(p->value(entry.first)),end=point(entry.second);const int began=listener.begins,ended=listener.ends;graph->mouseDown(mouse(*graph,start));graph->mouseDrag(mouse(*graph,end,juce::ModifierKeys::leftButtonModifier,1,true,start));graph->mouseUp(mouse(*graph,end,juce::ModifierKeys(),1,true,start));check(std::abs(p->value(entry.first)-entry.second)<=1&&listener.begins==began+1&&listener.ends==ended+1,std::string(entry.first)+" actual response handle changes intended frequency while audio is stopped");}}
    }
    if(k==DynKind::Stage){
        juce::Component*map=nullptr;for(auto*x:c.all)if(x->getComponentID()=="stageMap")map=x;
        check(map!=nullptr,"round spatial map exists");if(map){const auto start=map->getLocalBounds().getCentre().toFloat();const auto end=start+juce::Point<float>(map->getWidth()*.14f,-map->getHeight()*.15f);const int began=listener.begins,ended=listener.ends;const auto oldX=p->value("x"),oldD=p->value("distance");map->mouseDown(mouse(*map,start));map->mouseDrag(mouse(*map,end,juce::ModifierKeys::leftButtonModifier,1,true,start));map->mouseUp(mouse(*map,end,juce::ModifierKeys(),1,true,start));check(p->value("x")!=oldX&&p->value("distance")!=oldD&&listener.begins==began+2&&listener.ends==ended+2,"spatial drag changes both coordinates with two balanced gestures");}
    }
    check(listener.closed()&&listener.begins>0,"all UI host gestures are balanced, ordered and closed");p->removeListener(&listener);
    p->selectPreset(0,false);p->setValue("bypass",0,false);p->setValue("delta",0,false);prepare(*p);render(*p,96000);tick();const int w=editor->getWidth(),h=editor->getHeight();bool pngs=true;for(int mult:{1,2}){editor->setSize(w*mult,h*mult);tick();auto image=editor->createComponentSnapshot(editor->getLocalBounds());juce::File f=juce::File::getCurrentWorkingDirectory().getChildFile(p->getName()+"-UI-"+juce::String(w*mult)+"x"+juce::String(h*mult)+".png");juce::FileOutputStream out(f);out.setPosition(0);out.truncate();juce::PNGImageFormat png;pngs&=out.openedOk()&&png.writeImageToStream(image,out)&&image.getWidth()==w*mult;}check(pngs,"native editor renders at1x and2x with actual processed meters");editor.reset();p->releaseResources();}
}
void groupsTest(){
    product="GILLBUSS";auto a=std::make_unique<GillDynamicsProcessor>(DynKind::Buss),b=std::make_unique<GillDynamicsProcessor>(DynKind::Buss);
    for(int i=1;i<=8;++i)for(const char*field:{"drive","trim","bypass","noise"})a->setValue("g"+juce::String(i)+field,0,false);
    a->selectPreset(11,false);b->selectPreset(11,false);a->setValue("group",3,false);b->setValue("group",3,false);a->setValue("g3drive",10,false);a->setValue("g3trim",-3,false);b->syncGroups();check(b->value("g3drive")==10&&b->value("g3trim")==-3,"group controls mirror across two instances");prepare(*a);prepare(*b);check(render(*a,24000)==render(*b,24000),"same-group instances render identical shared processing");
    auto c=std::make_unique<GillDynamicsProcessor>(DynKind::Buss);c->selectPreset(11,false);c->setValue("group",0,false);prepare(*c);prepare(*b);check(render(*c,24000)!=render(*b,24000),"NONE excludes shared group processing");
    a->setValue("g3bypass",1,false);prepare(*b);auto bypass=render(*b,24000);bool exact=true;for(int i=0;i<24000;++i)exact&=std::abs(bypass[i]-(i<b->getLatencySamples()?0:voice(i-b->getLatencySamples(),48000)))<2e-6;check(exact,"remote group BYPASS is aligned and bypasses coloration and trim");
    juce::MemoryBlock state;a->getStateInformation(state);a->setValue("g3trim",2,false);a->setStateInformation(state.getData(),(int)state.getSize());b->syncGroups();check(b->value("g3trim")==-3,"saved group state restores shared values");
    a->selectPreset(4,false);check(a->value("g3trim")==-3&&a->value("group")==3,"factory presets preserve group assignment and shared controls");
    for(int i=1;i<=8;++i)for(const char*field:{"drive","trim","bypass","noise"})a->setValue("g"+juce::String(i)+field,0,false);
}
int main(){std::cout<<std::unitbuf;juce::ScopedJuceInitialiser_GUI gui;
    // Update06: exercise real LIVE/PRO host state, audio timing and UI.
    gill::testing::qualityRoutes([]{return std::make_unique<GillDynamicsProcessor>(DynKind::Vox);},[](bool ok,const std::string& why){check(ok,why);});
    gill::testing::qualityRoutes([]{return std::make_unique<GillDynamicsProcessor>(DynKind::Opta);},[](bool ok,const std::string& why){check(ok,why);});
    gill::testing::qualityRoutes([]{return std::make_unique<GillDynamicsProcessor>(DynKind::Buss);},[](bool ok,const std::string& why){check(ok,why);});
    gill::testing::qualityRoutes([]{return std::make_unique<GillDynamicsProcessor>(DynKind::Quad);},[](bool ok,const std::string& why){check(ok,why);});
    gill::testing::qualityRoutes([]{return std::make_unique<GillDynamicsProcessor>(DynKind::Stage);},[](bool ok,const std::string& why){check(ok,why);});
groupsTest();for(auto k:{DynKind::Vox,DynKind::Opta,DynKind::Buss,DynKind::Quad,DynKind::Stage}){metadata(k);routes(k);automation(k);ui(k);}std::ofstream o("dynamics-integration-report.json");o<<"{\"passed\":"<<(failures?"false":"true")<<",\"checks\":"<<checks<<",\"failures\":"<<failures<<",\"ui_edits\":"<<edits<<",\"presets_tested\":"<<presetsTested<<",\"audio_configurations\":"<<configs<<",\"failed_cases\":[";for(size_t i=0;i<errors.size();++i)o<<(i?",":"")<<'"'<<errors[i]<<'"';o<<"]}";std::cout<<"RESULT "<<checks<<" checks, "<<failures<<" failures, "<<edits<<" UI edits, "<<presetsTested<<" presets\n";return failures?1:0;}

