#include <juce_audio_utils/juce_audio_utils.h>
#include "Presets.h"
#include <cmath>
#include <cstring>
#include <fstream>
#include <iostream>
#include <set>
namespace{
int checks=0,failures=0;std::string product;std::set<std::string>classIds;
void check(bool ok,const std::string&m){++checks;if(!ok){++failures;std::cerr<<"FAIL "<<product<<" "<<m<<'\n';}}
struct Visitor final:juce::ExtensionsVisitor{juce::MemoryBlock data;void visitVST3Client(const VST3Client&c)override{data=c.getPreset();}};
void sync(juce::AudioPluginInstance&p){juce::MemoryBlock temp;p.getStateInformation(temp);}
std::unique_ptr<juce::AudioPluginInstance>create(juce::VST3PluginFormat&f,const juce::PluginDescription&d,double fs=48000){juce::String error;auto p=f.createInstanceFromDescription(d,fs,127,error);check(p!=nullptr,"factory creates native instance: "+error.toStdString());return p;}
void prepare(juce::AudioPluginInstance&p,double fs,int ch){p.setPlayConfigDetails(ch,ch,fs,127);p.prepareToPlay(fs,127);}
float sample(int i,double fs,int c){return static_cast<float>((.15*std::sin(2*juce::MathConstants<double>::pi*220*i/fs)+.04*std::sin(2*juce::MathConstants<double>::pi*1700*i/fs))*(c?-.65:1));}
std::vector<float>render(juce::AudioPluginInstance&p,int total,double fs,int ch,bool hostBypass=false){std::vector<float>out;out.reserve(total*ch);juce::AudioBuffer<float>b(ch,127);juce::MidiBuffer midi;for(int start=0;start<total;start+=127){int n=std::min(127,total-start);b.setSize(ch,n,false,false,true);for(int c=0;c<ch;++c)for(int i=0;i<n;++i)b.setSample(c,i,sample(start+i,fs,c));if(hostBypass)p.processBlockBypassed(b,midi);else p.processBlock(b,midi);for(int i=0;i<n;++i)for(int c=0;c<ch;++c)out.push_back(b.getSample(c,i));}return out;}
void clean(juce::AudioPluginInstance&p,DynKind k){auto defs=gilldyn::specs(k);for(size_t i=0;i<defs.size();++i){const auto&d=defs[i];float v=d.def;if(d.id=="comp"||d.id=="gain"||d.id=="reduction"||d.id=="output"||d.id=="drive"||d.id=="trim")v=0;if(d.id=="gate")v=-90;juce::NormalisableRange<float>r(d.lo,d.hi,d.step,d.skew);p.getParameters()[(int)i]->setValueNotifyingHost(r.convertTo0to1(v));}sync(p);}
void test(juce::VST3PluginFormat&f,const juce::File&bundle,DynKind kind){product=bundle.getFileNameWithoutExtension().toStdString();juce::OwnedArray<juce::PluginDescription>descriptions;f.findAllTypesForFile(descriptions,bundle.getFullPathName());check(descriptions.size()==1,"exactly one discoverable effect");if(descriptions.size()!=1)return;auto&d=*descriptions[0];auto p=create(f,d);if(!p)return;check(d.version=="0.1.0"&&d.manufacturerName=="GILLPRODUCTION"&&!d.isInstrument,"factory version manufacturer effect metadata");Visitor v;p->getExtensions(v);bool idGood=v.data.getSize()>=48&&std::memcmp(v.data.getData(),"VST3",4)==0;std::string id=idGood?std::string(static_cast<const char*>(v.data.getData())+8,32):"";check(idGood&&classIds.insert(id).second,"complete distinct VST3 class ID");std::cout<<product<<" FACTORY "<<id<<'\n';
 auto defs=gilldyn::specs(kind);check(p->getParameters().size()==(int)defs.size()+1,"all controls and program parameter exposed");check(p->getNumPrograms()==12,"twelve actual host programs");std::set<std::string>ids;for(int i=0;i<p->getParameters().size();++i){auto*param=p->getHostedParameter(i);check(param&&ids.insert(param->getParameterID().toStdString()).second,"distinct stable parameter ID");if(i<(int)defs.size())check(p->getParameters()[i]->getName(128).toStdString()==defs[i].name,"native parameter name and order");}
 prepare(*p,48000,2);for(int i=0;i<12;++i){p->setCurrentProgram(i);sync(*p);render(*p,254,48000,2);sync(*p);check(p->getCurrentProgram()==i&&p->getProgramName(i)==gilldyn::presets(kind)[i].name,"host factory preset selection");}
 p->setCurrentProgram(3);sync(*p);if(!p->getParameters().isEmpty()){const auto& def=defs.front();juce::NormalisableRange<float> range(def.lo,def.hi,def.step,def.skew);const float legal=range.convertTo0to1(range.snapToLegalValue(range.convertFrom0to1(.37f)));p->getParameters()[0]->setValueNotifyingHost(legal);}sync(*p);juce::MemoryBlock state;p->getStateInformation(state);auto q=create(f,d);if(q){q->setStateInformation(state.getData(),(int)state.getSize());sync(*q);bool same=q->getCurrentProgram()==p->getCurrentProgram();for(int i=0;i<(int)defs.size();++i){const auto pv=p->getParameters()[i]->getValue(),qv=q->getParameters()[i]->getValue();if(std::abs(qv-pv)>=1e-6)std::cout<<product<<" STATE DIAG "<<defs[i].id<<" source="<<pv<<" restored="<<qv<<"\n";same&=std::abs(qv-pv)<1e-6;}check(same,"opaque VST3 state restores every parameter and preset");p->releaseResources();prepare(*p,48000,2);prepare(*q,48000,2);check(render(*p,24000,48000,2)==render(*q,24000,48000,2),"opaque recalled state renders exactly the same audio");q->releaseResources();}p->releaseResources();p.reset();
 for(double fs:{44100.,48000.,96000.,192000.})for(int ch:{1,2})for(int mode=0;mode<3;++mode){auto a=create(f,d,fs);if(!a)continue;clean(*a,kind);if(mode==1){a->getBypassParameter()->setValueNotifyingHost(1);sync(*a);}prepare(*a,fs,ch);int expected=kind==DynKind::Vox?(int)std::ceil(fs*.00075):kind==DynKind::Buss?24:0;check(a->getLatencySamples()==expected,"latency reported correctly before audio");auto audio=render(*a,10000,fs,ch,mode==2);bool aligned=true;for(int i=0;i<10000;++i)for(int c=0;c<ch;++c)aligned&=std::abs(audio[i*ch+c]-(i<expected?0:sample(i-expected,fs,c)))<2e-6f;check(aligned,"neutral or native/host bypass mono/stereo is latency aligned");a->releaseResources();}
}
}
int main(int argc,char**argv){if(argc!=2)return 2;juce::ScopedJuceInitialiser_GUI gui;juce::VST3PluginFormat format;const char*names[]{"GILLVOX","GILLOPTA","GILLBUSS","GILLQUAD","GILLSTAGE"};for(int i=0;i<5;++i)test(format,juce::File(juce::String(argv[1])).getChildFile(juce::String(names[i])+"_artefacts/Release/VST3/"+names[i]+".vst3"),static_cast<DynKind>(i));std::ofstream out("dynamics-vst3-host-report.json");out<<"{\"passed\":"<<(failures?"false":"true")<<",\"checks\":"<<checks<<",\"failures\":"<<failures<<",\"unique_factory_ids\":"<<classIds.size()<<"}";std::cout<<"RESULT "<<checks<<" checks "<<failures<<" failures\n";return failures?1:0;}



