#include "../Source/PluginProcessor.h"
#include <cstdio>
#include <cmath>
static int checks=0,failures=0;void check(bool ok,const char*s,double x=0){++checks;if(!ok)++failures;std::printf("%s %s %.9g\n",ok?"PASS":"FAIL",s,x);}
using namespace gill::creative;
struct Head:juce::AudioPlayHead{double seconds=0;juce::Optional<PositionInfo>getPosition()const override{PositionInfo p;p.setTimeInSeconds(seconds);p.setPpqPosition(seconds*2);p.setBpm(120);p.setIsPlaying(true);return p;}};
std::vector<float>render(Controls c,double rate,double bpm){Engine e(Kind::Phrase);e.prepare(rate);Plan p;p.count=1;p.durationBeats=4;p.durationSeconds=float(240/bpm);p.bpm=float(bpm);p.markers[0]={0,1,0,float(60/bpm),1};e.postPlan(p,true);const int count=int(rate*5);std::vector<float>l(count),r(count);const int impulse=int(rate*60/bpm*.98);l[impulse]=r[impulse]=.5f;Transport t;t.hasPPQ=true;t.bpm=bpm;for(int at=0;at<count;at+=127){const int n=std::min(127,count-at);t.ppq=at/rate*bpm/60;e.process(l.data()+at,r.data()+at,nullptr,nullptr,n,c,t);}l.insert(l.end(),r.begin(),r.end());return l;}
int main(){juce::ScopedJuceInitialiser_GUI init;Controls c;c.amount=1;c.mix=1;c.dry=0;c.delaySend=1;c.delayFeedback=.5f;c.reverbSend=1;c.pro=false;
 for(double fs:{44100.,48000.,96000.})for(double bpm:{83.,120.,173.}){c.delayRate=3;c.phraseExport=2;auto d=render(c,fs,bpm);const int count=int(fs*5),original=int(fs*60/bpm*.98),expected=original+int(std::round(fs*60/bpm*.5));int first=-1;for(int i=0;i<count;++i)if(std::abs(d[i])+std::abs(d[count+i])>1.e-6){first=i;break;}check(first==expected,"Delay throw arrives exactly on selected sample grid",first-expected);c.phraseExport=1;auto r=render(c,fs,bpm);c.phraseExport=0;auto both=render(c,fs,bpm);double error=0,wet=0;for(size_t i=0;i<d.size();++i){error=std::max(error,std::abs(double(d[i]+r[i]-both[i])));wet+=std::abs(d[i]);}check(error<1.e-6,"Independent hall and delay stems sum to combined effect",error);check(wet>.001,"Delay stem has real audio",wet);}
 GillCreativeProcessor p(CreativeKind::Phrase);check(p.getNumPrograms()==10,"Phrase has original six and four additional presets");check(p.apvts.getParameter("delaySend")!=nullptr,"Delay parameters exist only in Phrase");GillCreativeProcessor director(CreativeKind::Director),reply(CreativeKind::Reply);check(director.apvts.getParameter("delaySend")==nullptr&&reply.apvts.getParameter("delaySend")==nullptr,"Other Creative products retain their own parameter set");
 auto old=p.apvts.copyState();old.setProperty("schema",2,nullptr);old.setProperty("program",2,nullptr);for(int i=old.getNumChildren()-1;i>=0;--i){auto id=old.getChild(i)["id"].toString();if(id=="reverbSend"||id=="delaySend"||id=="delayFeedback"||id=="delayRate")old.removeChild(i,nullptr);}juce::MemoryBlock state;if(auto xml=old.createXml())juce::AudioProcessor::copyXmlToBinary(*xml,state);p.setValue("delaySend",100);p.setValue("reverbSend",0);p.setStateInformation(state.getData(),int(state.getSize()));check(p.value("reverbSend")==100&&p.value("delaySend")==0&&p.getCurrentProgram()==2,"Update10 state migrates to original hall-only sound");
 p.setValue("delaySend",83);p.setValue("delayRate",5);p.setValue("delayFeedback",61);p.getStateInformation(state);p.setCurrentProgram(0);p.setStateInformation(state.getData(),int(state.getSize()));check(p.value("delaySend")==83&&p.value("delayRate")==5&&p.value("delayFeedback")==61,"New delay settings survive project recall");
 const auto folder=juce::File::getCurrentWorkingDirectory().getChildFile("phrase-delay-evidence");folder.createDirectory();
#if JUCE_WINDOWS
 _putenv_s("GILL_CREATIVE_AUDIO_ROOT",folder.getFullPathName().toRawUTF8());
#else
 setenv("GILL_CREATIVE_AUDIO_ROOT",folder.getFullPathName().toRawUTF8(),1);
#endif
 Head head;p.setPlayHead(&head);p.prepareToPlay(48000,512);p.setValue("delaySend",80);p.setValue("reverbSend",100);p.setValue("delayFeedback",35);p.setValue("delayRate",3);p.setValue("mix",65);p.startLearn();juce::AudioBuffer<float>audio(2,512);juce::MidiBuffer midi;
 for(int block=0;block<300;++block){head.seconds=block*512/48000.;for(int i=0;i<512;++i){double t=head.seconds+i/48000.,phase=std::fmod(t,1.);float x=phase>.10&&phase<.70?float(.18*std::sin(2*pi*173*t)):0;audio.setSample(0,i,x);audio.setSample(1,i,x);}p.processBlock(audio,midi);}p.stopLearn();audio.clear();head.seconds+=512/48000.;p.processBlock(audio,midi);
 for(int i=0;i<500&&!p.canRender();++i)juce::Thread::sleep(10);check(p.canRender(),"Real Phrase recording ready for separate exports");
 std::vector<std::vector<float>>stems;for(int part:{1,2,0}){check(p.renderEffects(true,part),"Actual WAV stem render starts",part);for(int i=0;i<2000&&p.renderer.busy();++i)juce::Thread::sleep(10);const auto file=p.renderer.file();check(file.existsAsFile()&&file.getFileName().contains(part==1?"-REVERB-":part==2?"-DELAY-":"-FX-"),"Separate exported WAV has correct stem identity",part);juce::WavAudioFormat format;std::unique_ptr<juce::AudioFormatReader>reader(format.createReaderFor(file.createInputStream().release(),true));if(!reader){check(false,"Exported WAV readable");continue;}juce::AudioBuffer<float>samples(2,int(reader->lengthInSamples));check(reader->read(&samples,0,samples.getNumSamples(),0,true,true),"Real exported stem samples readable");double energy=0;std::vector<float>v;for(int ch=0;ch<2;++ch)for(int i=0;i<samples.getNumSamples();++i){const float x=samples.getSample(ch,i);v.push_back(x);energy+=x*x;}check(energy>.01,"Exported stem is audible",energy);stems.push_back(std::move(v));}
 if(stems.size()==3){check(stems[0].size()==stems[1].size()&&stems[1].size()==stems[2].size(),"Matching capture/tail lengths at this delay setting");if(stems[0].size()==stems[2].size()&&stems[1].size()==stems[2].size()){double error=0;for(size_t i=0;i<stems[2].size();++i)error=std::max(error,std::abs(double(stems[0][i]+stems[1][i]-stems[2][i])));check(error<1.e-5,"Actual independently exported WAVs sum to combined wet render",error);}}
 p.setPlayHead(nullptr);std::printf("RESULT %d checks %d failures\n",checks,failures);return failures?1:0;}
