#include "PluginProcessor.h"
#include "PluginEditor.h"
#include <cstdlib>
namespace {
const char*names[]{"GILLSILK","GILLSPARK","GILLSTRIP","GILLGOLD","GILLDIVE"};
bool numeric(const juce::var&v,double&d){const auto s=v.toString().trim();if(s.isEmpty())return false;auto*start=s.toRawUTF8();char*end=nullptr;d=std::strtod(start,&end);return end!=start&&*end=='\0'&&std::isfinite(d);}
}
GillFinishProcessor::GillFinishProcessor(FinishKind k):AudioProcessor(BusesProperties().withInput("INPUT",juce::AudioChannelSet::stereo(),true).withOutput("OUTPUT",juce::AudioChannelSet::stereo(),true)),kind(k),definitions(gillfinish::specs(k)),programs(gillfinish::presets(k)),apvts(*this,nullptr,juce::String(names[static_cast<int>(k)])+"_STATE",layout(k)){for(size_t i=0;i<definitions.size();++i)values[i]=apvts.getRawParameterValue(definitions[i].id);selectPreset(0,false);}
juce::AudioProcessorValueTreeState::ParameterLayout GillFinishProcessor::layout(FinishKind k){juce::AudioProcessorValueTreeState::ParameterLayout l;for(const auto&d:gillfinish::specs(k)){if(d.choices.empty())l.add(std::make_unique<juce::AudioParameterFloat>(juce::ParameterID{d.id,1},d.name,juce::NormalisableRange<float>(d.lo,d.hi,d.step,d.skew),d.def));else if(juce::String(d.id)=="bypass"||juce::String(d.id)=="delta"||juce::String(d.id)=="sync")l.add(std::make_unique<juce::AudioParameterBool>(juce::ParameterID{d.id,1},d.name,d.def>.5f));else{juce::StringArray a;for(auto c:d.choices)a.add(c);l.add(std::make_unique<juce::AudioParameterChoice>(juce::ParameterID{d.id,1},d.name,a,juce::roundToInt(d.def)));}}return l;}
const juce::String GillFinishProcessor::getName()const{return names[static_cast<int>(kind)];}
float GillFinishProcessor::value(const juce::String&id)const{auto*p=apvts.getRawParameterValue(id);const auto v=p?p->load():0;return std::isfinite(v)?v:0;}
float GillFinishProcessor::at(const char*id)const{for(size_t i=0;i<definitions.size();++i)if(std::strcmp(id,definitions[i].id)==0){const auto v=values[i]->load(std::memory_order_relaxed);return std::isfinite(v)?v:definitions[i].def;}return 0;}
void GillFinishProcessor::setValue(const juce::String&id,float v,bool gesture){if(auto*p=apvts.getParameter(id)){if(gesture)p->beginChangeGesture();p->setValueNotifyingHost(p->convertTo0to1(v));if(gesture)p->endChangeGesture();}}
bool GillFinishProcessor::isBusesLayoutSupported(const BusesLayout&l)const{auto o=l.getMainOutputChannelSet();return(o==juce::AudioChannelSet::mono()||o==juce::AudioChannelSet::stereo())&&o==l.getMainInputChannelSet();}
void GillFinishProcessor::update(bool queryHost){
    float bpm=at("bpm");bool available=false;if(queryHost)if(auto*h=getPlayHead())if(auto pos=h->getPosition())if(auto v=pos->getBpm())if(std::isfinite(*v)&&*v>=20&&*v<=300){bpm=static_cast<float>(*v);available=true;}if(bpm<20)bpm=120;tempo=bpm;hostTempo=available;
    if(kind==FinishKind::Silk){gillfinish::SilkParameters p;p.depth=at("depth");p.sensitivity=at("sensitivity");p.lowHz=at("low");p.highHz=std::max(p.lowHz,at("high"));p.attackMs=at("attack");p.releaseMs=at("release");p.mix=at("mix")*.01f;p.outputDb=at("output");silk.setParameters(p);}
    else if(kind==FinishKind::Spark){gillfinish::SparkParameters p;p.depth=at("depth");p.sensitivity=at("sensitivity");p.lowHz=at("low");p.highHz=std::max(p.lowHz,at("high"));p.attackMs=at("attack");p.decayMs=at("release");p.mix=at("mix")*.01f;p.outputDb=at("output");p.mode=juce::roundToInt(at("mode"));spark.setParameters(p);}
    else if(kind==FinishKind::Gold){const float lows[]{20,30,60,100},highs[]{3000,4000,5000,8000,10000,12000,16000},cuts[]{5000,10000,20000};gillfinish::GoldParameters p;p.lowBoost=at("lowboost");p.lowCut=at("lowcut");p.lowHz=lows[juce::jlimit(0,3,juce::roundToInt(at("lowfreq")))];p.highBoost=at("highboost");p.highCut=at("highcut");p.highHz=highs[juce::jlimit(0,6,juce::roundToInt(at("highfreq")))];p.cutHz=cuts[juce::jlimit(0,2,juce::roundToInt(at("cutfreq")))];p.bandwidth=at("bandwidth");p.mix=at("mix")*.01f;p.outputDb=at("output");gold.setParameters(p);}
    else if(kind==FinishKind::Dive){gillfinish::DiveParameters p;p.depth=at("depth");p.resonance=at("resonance");p.motion=at("motion");p.rateHz=at("rate");if(at("sync")>.5f){const float beats[]{.25f,.5f,1,2,4,8};p.rateHz=bpm/60/beats[juce::jlimit(0,5,juce::roundToInt(at("division")))];}p.envelope=at("envelope");p.mix=at("mix")*.01f;p.outputDb=at("output");dive.setParameters(p);}
    else{gillfinish::StripParameters p;p.inputDb=at("input");p.bass=at("bass");p.treble=at("treble");p.compress=at("compress");p.deess=at("deess");p.space=at("space");p.echo=at("echo");p.width=at("width");p.outputDb=at("output");p.style=juce::roundToInt(at("style"));p.bpm=bpm;strip.setParameters(p);}
}
void GillFinishProcessor::prepareToPlay(double rate,int block){const bool good=std::isfinite(rate)&&rate>=8000&&rate<=192000;rateSupported=good;const auto fs=good?rate:48000.;uiRate=fs;const int ch=juce::jlimit(1,2,getTotalNumOutputChannels());update();
    if(kind==FinishKind::Silk){silk.prepare(fs,block,ch);latency=silk.latencySamples();}else if(kind==FinishKind::Spark){spark.prepare(fs,block,ch);latency=spark.latencySamples();}else if(kind==FinishKind::Gold){gold.prepare(fs,block,ch);latency=0;}else if(kind==FinishKind::Dive){dive.prepare(fs,block,ch);latency=0;}else{strip.prepare(fs,block,ch);latency=0;}update();for(auto&r:dry)r.assign(static_cast<size_t>(latency+1),0);dryPosition=0;setLatencySamples(latency);bypassFade.reset(fs,.005);bypassFade.setCurrentAndTargetValue(!good||at("bypass")>.5f?1.f:0.f);deltaFade.reset(fs,.005);deltaFade.setCurrentAndTargetValue(at("delta")>.5f?1.f:0.f);inputPeak=outputPeak=reduction=0;}
void GillFinishProcessor::releaseResources(){silk.reset();spark.reset();gold.reset();dive.reset();strip.reset();inputPeak=outputPeak=reduction=0;}
void GillFinishProcessor::process(juce::AudioBuffer<float>&b,bool bypass){juce::ScopedNoDenormals nd;const int ch=std::min(2,b.getNumChannels()),n=b.getNumSamples();if(ch==0||n==0)return;for(int c=getTotalNumInputChannels();c<b.getNumChannels();++c)b.clear(c,0,n);update(true);bypassFade.setTargetValue(bypass||!rateSupported.load()||at("bypass")>.5f?1.f:0.f);deltaFade.setTargetValue(at("delta")>.5f?1.f:0.f);float inPeak=0,outPeak=0;
    for(int start=0;start<n;start+=128){const int count=std::min(128,n-start);std::array<float*,2>ptr{};std::array<std::array<float,128>,2>original{};for(int c=0;c<ch;++c)ptr[c]=b.getWritePointer(c,start);
        for(int i=0;i<count;++i){for(int c=0;c<ch;++c){const float x=static_cast<float>(gillfinish::bounded(ptr[c][i],-100,100));ptr[c][i]=x;inPeak=std::max(inPeak,std::abs(x));dry[c][dryPosition]=x;original[c][i]=dry[c][(dryPosition+1)%dry[c].size()];}dryPosition=(dryPosition+1)%dry[0].size();}
        if(kind==FinishKind::Silk)silk.process(ptr.data(),count,ch);else if(kind==FinishKind::Spark)spark.process(ptr.data(),count,ch);else if(kind==FinishKind::Gold)gold.process(ptr.data(),count,ch);else if(kind==FinishKind::Dive)dive.process(ptr.data(),count,ch);else strip.process(ptr.data(),count,ch);
        for(int i=0;i<count;++i){const float bp=bypassFade.getNextValue(),de=deltaFade.getNextValue();for(int c=0;c<ch;++c){const float w=std::isfinite(ptr[c][i])?ptr[c][i]:0.f,wet=w+de*(original[c][i]-2*w);ptr[c][i]=bp>=1?original[c][i]:wet+bp*(original[c][i]-wet);outPeak=std::max(outPeak,std::abs(ptr[c][i]));}}
    }
    const float decay=static_cast<float>(std::exp(-n/(uiRate.load()*.12)));inputPeak=std::max(inPeak,inputPeak.load()*decay);outputPeak=std::max(outPeak,outputPeak.load()*decay);
    reduction=kind==FinishKind::Silk?silk.reductionDb():kind==FinishKind::Spark?spark.reductionDb():kind==FinishKind::Strip?strip.reductionDb():0;cutoff=kind==FinishKind::Dive?dive.cutoffHz():0;
    if(kind==FinishKind::Silk||kind==FinishKind::Spark){const juce::SpinLock::ScopedTryLockType lock(graphLock);if(lock.isLocked())display=kind==FinishKind::Silk?silk.reductionView():spark.reductionView();}
}
std::array<float,128> GillFinishProcessor::graph()const{const juce::SpinLock::ScopedLockType lock(graphLock);return display;}
void GillFinishProcessor::processBlock(juce::AudioBuffer<float>&b,juce::MidiBuffer&m){m.clear();process(b,false);}void GillFinishProcessor::processBlockBypassed(juce::AudioBuffer<float>&b,juce::MidiBuffer&m){m.clear();process(b,true);}
void GillFinishProcessor::selectPreset(int i,bool gesture){i=juce::jlimit(0,getNumPrograms()-1,i);currentProgram=i;for(const auto&d:definitions)if(juce::String(d.id)!="bypass"&&juce::String(d.id)!="delta"&&juce::String(d.id)!="bpm")setValue(d.id,d.def,gesture);for(const auto&v:programs[static_cast<size_t>(i)].values)setValue(v.first,v.second,gesture);}
bool GillFinishProcessor::presetMatches()const{const auto&p=programs[static_cast<size_t>(juce::jlimit(0,static_cast<int>(programs.size())-1,currentProgram.load()))];for(const auto&d:definitions){const juce::String id(d.id);if(id=="bypass"||id=="delta"||id=="bpm")continue;float v=d.def;for(const auto&x:p.values)if(id==x.first)v=x.second;if(std::abs(value(id)-v)>.02)return false;}return true;}
void GillFinishProcessor::getStateInformation(juce::MemoryBlock&out){auto s=apvts.copyState();s.setProperty("version",1,nullptr);s.setProperty("program",currentProgram.load(),nullptr);if(auto x=s.createXml())copyXmlToBinary(*x,out);}
void GillFinishProcessor::setStateInformation(const void*data,int bytes){if(!data||bytes<=0||bytes>1024*1024)return;if(auto x=getXmlFromBinary(data,bytes))if(x->hasTagName(apvts.state.getType())){auto incoming=juce::ValueTree::fromXml(*x),clean=apvts.copyState();bool changed=false;for(auto child:incoming){const auto id=child.getProperty("id").toString();auto*p=apvts.getParameter(id);double v=0;if(!p||!numeric(child.getProperty("value"),v))continue;auto target=clean.getChildWithProperty("id",id);if(target.isValid()){const auto&r=p->getNormalisableRange();target.setProperty("value",r.snapToLegalValue(static_cast<float>(std::clamp(v,static_cast<double>(r.start),static_cast<double>(r.end)))),nullptr);changed=true;}}if(changed)apvts.replaceState(clean);double v=0;if(numeric(incoming.getProperty("program"),v))currentProgram=juce::jlimit(0,getNumPrograms()-1,static_cast<int>(std::clamp(v,0.,static_cast<double>(getNumPrograms()-1))));}}
juce::AudioProcessorEditor*GillFinishProcessor::createEditor(){return new GillFinishEditor(*this);}
