#include "../Source/RestorationDSP.h"
#define gillrestoration legacy_restoration
#include "latency-v03-baseline/RestorationDSP.h"
#undef gillrestoration
#include <cstdio>
#include <cstring>
#include <fstream>
#include <vector>
#include <filesystem>
#include <string>
#include <limits>
#include <chrono>
#include <type_traits>
namespace latency_probe {
inline std::int64_t position=0,farthest=-99999;inline std::uint64_t accesses=0,violations=0;
inline void write(std::int64_t n){position=n;}
inline void read(std::int64_t n){if(n>=0){++accesses;farthest=std::max(farthest,n-position);if(n>position||position-n>=8192)++violations;}}
}
#define gillrestoration probed_restoration
#include "RestorationDSP-instrumented-v03.h"
#undef gillrestoration
namespace {
constexpr double pi=3.14159265358979323846;
int checks=0,failures=0;std::uint64_t comparisons=0,configurations=0;double maxError=0;
void check(bool yes,const char*label,double metric=0){++checks;failures+=!yes;std::printf("%s %-82s %.10g\n",yes?"PASS":"FAIL",label,metric);}
float random(std::uint32_t&s){s=s*1664525U+1013904223U;return static_cast<float>((s>>8)*(2./16777215.)-1.);}
int expected(double fs,int mode){const int legacy=static_cast<int>(std::ceil(fs*(mode?.008:.004))),gap=std::max(2,static_cast<int>(std::ceil(fs*(mode?.00035:.00065)))),stride=std::max(1,static_cast<int>(std::lround(fs/48000)));return std::min(legacy,gap+41*stride+2);}
template<class T>std::vector<T> fixture(int count,double fs,int mode){std::vector<T>x(static_cast<size_t>(count));std::uint32_t seed=471+mode;for(int i=0;i<count;++i){const double time=i/fs,fade=std::min(1.,i/(fs*.01));x[static_cast<size_t>(i)]=static_cast<T>(fade*(.13*std::sin(2*pi*211*time)+.045*std::sin(2*pi*1193*time)+.005*random(seed)));}const int gap=std::max(2,static_cast<int>(std::ceil(fs*(mode?.00035:.00065))));for(int length:{1,2,gap-1,gap,gap+1}){const int at=320+length*9;for(int i=0;i<length&&at+i<count;++i)x[static_cast<size_t>(at+i)]+=static_cast<T>(.4);}x[static_cast<size_t>(count/2)]+=static_cast<T>(.7);return x;}
template<class T,class D,class M>std::vector<T> render(D&e,M mode,const std::vector<T>&input,double amount,double fs,int block,int channels=1,bool automation=false,int advance=0){e.prepare(fs,mode);e.setAmount(amount);const int latency=e.getLatencySamples();std::vector<T>left=input,right=input;left.resize(input.size()+static_cast<size_t>(latency));right.resize(left.size());for(auto&x:right)x*=static_cast<T>(-.71);int at=0;std::uint32_t seed=917;while(at<static_cast<int>(left.size())){int n=automation?1:block>0?block:1+static_cast<int>((seed=seed*1664525U+1013904223U)%521);n=std::min(n,static_cast<int>(left.size())-at);if(automation){const int t=at+advance;const double a=t<4000?.55:t<6400?0:t<9300?1:t<13000?.07:t<18000?.81:.32;e.setAmount(a);}T*data[]{left.data()+at,right.data()+at};e.process(data,channels,n);at+=n;}left.erase(left.begin(),left.begin()+latency);if(channels==2)for(size_t i=static_cast<size_t>(latency);i<right.size();++i)left.push_back(right[i]);return left;}
template<class T>bool compare(const std::vector<T>&a,const std::vector<T>&b){if(a.size()!=b.size())return false;bool same=true;for(size_t i=0;i<a.size();++i){++comparisons;same=same&&a[i]==b[i];maxError=std::max(maxError,std::abs(static_cast<double>(a[i])-static_cast<double>(b[i])));}return same;}
std::vector<float> readWave(const std::filesystem::path&p){std::ifstream f(p,std::ios::binary);char tag[4];std::uint32_t size=0;f.read(tag,4);f.read(reinterpret_cast<char*>(&size),4);f.read(tag,4);std::vector<float>x;int format=0,bits=0,channels=0;while(f.read(tag,4)){f.read(reinterpret_cast<char*>(&size),4);if(std::memcmp(tag,"fmt ",4)==0){std::vector<char>b(size);f.read(b.data(),size);std::uint16_t v=0;std::memcpy(&v,b.data(),2);format=v;std::memcpy(&v,b.data()+2,2);channels=v;std::memcpy(&v,b.data()+14,2);bits=v;}else if(std::memcmp(tag,"data",4)==0){x.resize(size/4);f.read(reinterpret_cast<char*>(x.data()),size);}else f.seekg(size,std::ios::cur);if(size&1)f.seekg(1,std::ios::cur);}if(format!=3||bits!=32||channels!=1||x.empty())throw std::runtime_error("Expected frozen mono float32 WAV: "+p.string());return x;}
void saveRaw(const std::filesystem::path&p,const std::vector<float>&x){std::ofstream f(p,std::ios::binary);f.write(reinterpret_cast<const char*>(x.data()),static_cast<std::streamsize>(x.size()*sizeof(float)));}
void proof(){bool preserved=true,bounded=true;int minimumMargin=99999;for(int fs=8000;fs<=192000;++fs)for(int mode=0;mode<2;++mode){const int old=static_cast<int>(std::ceil(fs*(mode?.008:.004))),now=expected(fs,mode),gap=std::max(2,static_cast<int>(std::ceil(fs*(mode?.00035:.00065)))),stride=std::max(1,static_cast<int>(std::lround(fs/48000.)));for(int j=0;j<12;++j){const int oldOffset=std::min((8+3*j)*stride,old-gap-2),newOffset=std::min((8+3*j)*stride,now-gap-2);preserved=preserved&&oldOffset==newOffset;const int future=gap+newOffset+1;minimumMargin=std::min(minimumMargin,now-future);bounded=bounded&&future<now&&now+newOffset+2<8192;}}check(preserved,"All integer rates8k..192k retain all24 context points in both modes");check(bounded&&minimumMargin>=1,"All integer rates: maximum future access strictly precedes write, ring bounds safe",minimumMargin);}
void rangeMatrix(){bool exact=true;for(int mode=0;mode<2;++mode)for(double fs:{8000.,11025.,22050.,32000.,44100.,48000.,88200.,96000.,192000.}){const auto input=fixture<float>(2048,fs,mode);legacy_restoration::RestorationEngine old;gillrestoration::RestorationEngine now;for(int amount=0;amount<=1000;++amount){const int blocks[]{1,17,127,511,4096,-1};const int block=blocks[amount%6];const auto a=render(old,static_cast<legacy_restoration::Mode>(mode),input,amount*.001,fs,block),b=render(now,static_cast<gillrestoration::Mode>(mode),input,amount*.001,fs,block);exact=compare(a,b)&&exact;++configurations;}std::printf("MATRIX %s fs=%.0f amount0..100step0.1 old=%d new=%d exact=%d\n",mode?"DECRACKLE":"DECLICK",fs,old.getLatencySamples(),now.getLatencySamples(),exact?1:0);}check(exact,"Sample-aligned old/new bit identity for every0.1% Amount at nine rates",maxError);}
void precisionBlocks(){bool exact=true,impulse=true;for(int mode=0;mode<2;++mode)for(double fs:{8000.,32000.,44100.,48000.,96000.,192000.})for(int channels:{1,2}){legacy_restoration::RestorationEngine old;gillrestoration::RestorationEngine now;const auto input=fixture<double>(18000,fs,mode);for(int block:{1,17,64,127,257,511,4096,-1}){const auto a=render(old,static_cast<legacy_restoration::Mode>(mode),input,.731,fs,block,channels),b=render(now,static_cast<gillrestoration::Mode>(mode),input,.731,fs,block,channels);exact=compare(a,b)&&exact;++configurations;}now.prepare(fs,static_cast<gillrestoration::Mode>(mode));now.setAmount(0);const int latency=now.getLatencySamples();std::vector<double>a(static_cast<size_t>(latency+500)),b=a,dry=a;a[0]=.25;double*p[]{a.data(),b.data()},*dp[]{dry.data(),nullptr};now.process(p,channels,static_cast<int>(a.size()),dp);impulse=impulse&&latency==expected(fs,mode);for(int i=0;i<static_cast<int>(a.size());++i)impulse=impulse&&a[static_cast<size_t>(i)]==(i==latency?.25:0)&&a[static_cast<size_t>(i)]==dry[static_cast<size_t>(i)];}check(exact,"Double mono/stereo and eight block patterns preserve aligned baseline exactly",maxError);check(impulse,"New impulse delay and supplied host-bypass dry are bit-exact at six rates");}
void audioFixtures(const std::filesystem::path&root){bool exact=true;std::filesystem::create_directories("latency-v03-results");for(int mode=0;mode<2;++mode){const std::string name=mode?"DECRACKLE":"DECLICK";for(const auto&file:std::vector<std::string>{"dry_48k.wav",name+"-corrupted.wav","mouth-click-trains.wav"}){const auto input=readWave(root/"fixtures"/file);legacy_restoration::RestorationEngine old;gillrestoration::RestorationEngine now;for(double amount:{0.,.01,.55,1.}){const auto a=render(old,static_cast<legacy_restoration::Mode>(mode),input,amount,48000,127,2),b=render(now,static_cast<gillrestoration::Mode>(mode),input,amount,48000,-1,2);exact=compare(a,b)&&exact;++configurations;if(amount==.55){saveRaw(std::filesystem::path("latency-v03-results")/(name+"-"+file+"-old-aligned.f32"),a);saveRaw(std::filesystem::path("latency-v03-results")/(name+"-"+file+"-new-aligned.f32"),b);}}}}check(exact,"Frozen full speech/corruption/mouth-click fixtures: baseline and new identical",maxError);}
void automation(){bool compensated=true;double unchangedClockError=0;for(int mode=0;mode<2;++mode)for(double fs:{8000.,48000.,192000.}){const auto input=fixture<double>(24000,fs,mode);legacy_restoration::RestorationEngine old;gillrestoration::RestorationEngine now;old.prepare(fs,static_cast<legacy_restoration::Mode>(mode));now.prepare(fs,static_cast<gillrestoration::Mode>(mode));const int advance=old.getLatencySamples()-now.getLatencySamples();const auto a=render(old,static_cast<legacy_restoration::Mode>(mode),input,.55,fs,1,2,true),b=render(now,static_cast<gillrestoration::Mode>(mode),input,.55,fs,1,2,true,advance);compensated=compare(a,b)&&compensated;const auto different=render(now,static_cast<gillrestoration::Mode>(mode),input,.55,fs,1,2,true);for(size_t i=0;i<a.size();++i)unchangedClockError=std::max(unchangedClockError,std::abs(a[i]-different[i]));}check(compensated,"Audio-aligned Amount automation preserves old processing with explicit time offset",maxError);std::printf("METRIC unchanged-wall-clock automation max difference %.10g (timing change, not static equivalence)\n",unchangedClockError);}
void runtimeReadProof(){bool finite=true;for(int mode=0;mode<2;++mode)for(double fs:{8000.,11025.,22050.,32000.,44100.,48000.,88200.,96000.,192000.}){probed_restoration::RestorationEngine probe;const auto input=fixture<double>(22000,fs,mode);const auto out=render(probe,static_cast<probed_restoration::Mode>(mode),input,1,fs,-1,2);for(double x:out)finite=finite&&std::isfinite(x);}check(finite&&latency_probe::violations==0,"Instrumented real raw() accesses: no future or overwritten-ring reads",static_cast<double>(latency_probe::accesses));check(latency_probe::farthest<0,"Farthest instrumented read is strictly before current write",static_cast<double>(latency_probe::farthest));}
}
int main(){const auto start=std::chrono::steady_clock::now();std::printf("C++17; pointer bits %zu; baseline frozen before production edit\n",sizeof(void*)*8);try{proof();rangeMatrix();precisionBlocks();audioFixtures("latency-v03-baseline");automation();runtimeReadProof();}catch(const std::exception&e){check(false,e.what());}const double seconds=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();std::printf("RESULT %d checks %d failures; %llu compared samples; %llu signal configurations; %.3fs\n",checks,failures,static_cast<unsigned long long>(comparisons),static_cast<unsigned long long>(configurations),seconds);std::ofstream json("latency-v03-report.json");json<<"{\"passed\":"<<(failures?"false":"true")<<",\"checks\":"<<checks<<",\"failures\":"<<failures<<",\"compared_samples\":"<<comparisons<<",\"signal_configurations\":"<<configurations<<",\"maximum_aligned_error\":"<<maxError<<",\"instrumented_reads\":"<<latency_probe::accesses<<",\"out_of_range_reads\":"<<latency_probe::violations<<",\"farthest_read_relative_to_write\":"<<latency_probe::farthest<<",\"seconds\":"<<seconds<<"}\n";return failures?1:0;}
