#include "../Source/TuneDSP.h"
#define gill gill_v020
#include "TuneDSP-v020-reference.h"
#undef gill
#include <chrono>
#include <complex>
#include <cstdio>
#include <random>
#include <vector>
constexpr double pi=3.14159265358979323846,fs=48000;
int failures=0,checks=0;
void check(bool ok,const char* text,double value=0){++checks;std::printf("%s %s %.8g\n",ok?"PASS":"FAIL",text,value);if(!ok)++failures;}
std::vector<float> voice(int kind){const int length=96000;std::vector<float> x(length);double phase=0;const double amplitudes[]{.35,.27,.18,.13,.07};for(int n=0;n<length;++n){const double t=n/fs;const double hz=kind==0?230:kind==1?220*std::exp2((20+30*std::sin(2*pi*5*t))/1200):kind==2?(t<1?230:272):kind==4?220*std::exp2(1.0/1200):kind==5?82.40688923*std::exp2((20+25*std::sin(2*pi*5*t))/1200):220;phase+=2*pi*hz/fs;double v=0;for(int h=1;h<=5;++h)v+=amplitudes[h-1]*std::sin(phase*h);x[n]=static_cast<float>(v*.4);}return x;}
template<class D>std::vector<float> render(D& dsp,const std::vector<float>&x,int block,int channels=1){auto a=x,b=x;for(auto& v:b)v=-v;for(int at=0;at<static_cast<int>(x.size());at+=block){float* p[]{a.data()+at,b.data()+at};dsp.process(p,channels,std::min(block,static_cast<int>(x.size())-at));}if(channels==2){double error=0;for(size_t i=0;i<a.size();++i)error=std::max(error,std::abs(static_cast<double>(a[i]+b[i])));check(error<1e-6,"antiphase stereo remains phase coherent",error);}return a;}
double residue(const std::vector<float>&y,double f){const int at=48000,length=48000;double all=0,harmonic=0;for(int i=0;i<length;++i)all+=y[at+i]*y[at+i];for(int h=1;h<=30&&h*f<20000;++h){std::complex<double> s{};for(int i=0;i<length;++i)s+=static_cast<double>(y[at+i])*std::polar(1.,-2*pi*h*f*i/fs);harmonic+=2*std::norm(s)/length;}return 10*std::log10(std::max(1e-15,all-harmonic)/all);}
double localHz(const std::vector<float>& y,int start,double expected){const int lo=static_cast<int>(fs/expected*.9),hi=static_cast<int>(fs/expected*1.1),length=1536;std::vector<double>d(hi+2);int best=lo;for(int lag=lo;lag<=hi;++lag){for(int i=0;i<length;++i){const double diff=y[start+i]-y[start+i+lag];d[lag]+=diff*diff;}if(d[lag]<d[best])best=lag;}if(best==lo||best==hi)return 0;const double a=d[best-1],b=d[best],c=d[best+1];return fs/(best+.5*(a-c)/(a-2*b+c));}
double centsRms(const std::vector<float>&y,int latency,double expected=220){double sum=0;int count=0;for(int start=24000+latency;start+2000<static_cast<int>(y.size());start+=480){const double f=localHz(y,start,expected);if(f<=0)return 999;const double cents=1200*std::log2(f/expected);sum+=cents*cents;++count;}return std::sqrt(sum/count);}
double maximumStep(const std::vector<float>&y,int a,int b){double result=0;for(int i=a+1;i<b;++i)result=std::max(result,std::abs(static_cast<double>(y[i]-y[i-1])));return result;}
void setup(gill::TuneDSP&d,int quality,int block=127,float mix=100){d.setQualityMode(quality);d.prepare(fs,block,1);d.setParameters(9,2,0,0,mix);}
double toneLevel(const std::vector<float>&x,double hz){const int length=24000,start=static_cast<int>(x.size())-length;std::complex<double> s{};for(int i=0;i<length;++i)s+=static_cast<double>(x[start+i])*std::polar(1.,-2*pi*hz*i/fs);return 2*std::abs(s)/length;}
void resamplerQuality(int quality){gill::TuneLiveDSP dsp;dsp.prepare(fs,1,quality==0?2048:768,quality==0);constexpr double sourceHz=210,targetHz=220;const float shift=static_cast<float>(12*std::log2(targetHz/sourceHz));std::vector<float> out(48000);std::array<float,2> a{},b{};for(int i=0;i<48000;++i){a[0]=static_cast<float>(.2*std::sin(2*pi*sourceHz*i/fs)+.2*std::sin(2*pi*sourceHz*110*i/fs)+.1*std::sin(2*pi*sourceHz*80*i/fs));dsp.processSample(a,b,sourceHz,shift,true);out[i]=b[0];}const double alias=20*std::log10(toneLevel(out,23800)/.2),upper=20*std::log10(toneLevel(out,17600)/.1);std::printf("RESAMPLER %s upper-vocal17600Hz gain %.5f dB folded23800Hz %.5f dB relative\n",quality==0?"STUDIO":"LIVE",upper,alias);check(alias<(quality==0?-65:-35),"bandlimited pitch-up contains above-Nyquist source harmonic",alias);check(std::abs(upper)<(quality==0?.1:2),"high vocal harmonic remains within declared interpolation passband",upper);}
int main(){
    for(int quality=0;quality<2;++quality){std::printf("MODE %s\n",quality==0?"STUDIO":"LIVE");resamplerQuality(quality);const auto x=voice(0);gill::TuneDSP d;setup(d,quality);auto y=render(d,x,127);gill_v020::TuneDSP old;old.prepare(fs,127,1);old.setParameters(9,2,0,0,100);auto previous=render(old,x,127);
        const double oldResidual=residue(previous,220),newResidual=residue(y,220);std::printf("METRIC 230-to220 five-partial old %.4f new %.4f dB outside target harmonic grid\n",oldResidual,newResidual);check(newResidual<-35&&newResidual<oldResidual-15,"steady hard correction removes measured off-grid pitch residue",newResidual);const double error=centsRms(y,d.latencySamples());check(error<1,"steady230Hz voice corrected to220Hz with sub-cent mean pitch error",error);
        for(int block:{1,4096}){gill::TuneDSP other;setup(other,quality,block);auto z=render(other,x,block);check(y==z,"actual output sample-exact across 1/127/4096 host blocks");}
        gill::TuneDSP vib;setup(vib,quality);auto v=render(vib,voice(1),127);const double vibratoError=centsRms(v,vib.latencySamples());check(vibratoError<8,"HUMANIZE0 suppresses 5-Hz vibrato on a harmonic vocal",vibratoError);std::printf("METRIC vibrato off-grid %.4f dB\n",residue(v,220));
        gill::TuneDSP small;setup(small,quality);auto smallOut=render(small,voice(4),127);check(centsRms(smallOut,small.latencySamples())<.08,"one-cent detuning is corrected rather than hidden by unity bypass",centsRms(smallOut,small.latencySamples()));
        gill::TuneDSP low;setup(low,quality);auto lowOut=render(low,voice(5),127);check(centsRms(lowOut,low.latencySamples(),82.40688923)<10,"low82Hz vocal vibrato remains controlled with short LIVE latency",centsRms(lowOut,low.latencySamples(),82.40688923));
        gill::TuneDSP jump;setup(jump,quality);const auto stepped=voice(2);auto j=render(jump,stepped,127);const double step=maximumStep(j,45000+jump.latencySamples(),58000+jump.latencySamples());check(step<.12,"note transition stays bounded without large sample click",step);
        gill::TuneDSP neutral;setup(neutral,quality);auto original=voice(3),unity=render(neutral,original,127);bool exact=true;for(int i=24000;i<static_cast<int>(unity.size());++i)exact=exact&&unity[i]==original[i-neutral.latencySamples()];check(exact,"already correct voiced220Hz remains exact delayed original after settling");
        gill::TuneDSP stereo;stereo.setQualityMode(quality);stereo.prepare(fs,127,2);stereo.setParameters(9,2,0,0,100);render(stereo,x,127,2);
        std::mt19937 random(987);std::uniform_real_distribution<float> noise(-.07f,.07f);auto noisy=voice(0);for(int i=38400;i<57600;++i)noisy[i]=noise(random);gill::TuneDSP consonant;setup(consonant,quality);auto clean=render(consonant,noisy,127);double delta=0;for(int i=42000+consonant.latencySamples();i<54000+consonant.latencySamples();++i)delta=std::max(delta,std::abs(static_cast<double>(clean[i]-noisy[i-consonant.latencySamples()])));check(delta==0,"middle of unvoiced consonant/noise segment returns to exact delayed dry",delta);
        gill::TuneDSP mixed;setup(mixed,quality,127,50);auto half=render(mixed,x,127);double mixError=0;for(int i=0;i<static_cast<int>(x.size());++i){const double dry=i>=mixed.latencySamples()?x[i-mixed.latencySamples()]:0;mixError=std::max(mixError,std::abs(half[i]-(dry+.5*(y[i]-dry))));}check(mixError<2e-7,"50percent mix follows latency-aligned independent dry/wet reference",mixError);
        gill::TuneDSP bench;bench.setQualityMode(quality);bench.prepare(fs,128,2);bench.setParameters(9,2,0,0,100);const auto start=std::chrono::steady_clock::now();render(bench,x,128,2);const double seconds=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();std::printf("BENCH %s stereo48k/128 two-second harmonic voice %.5fs %.3fpercent realtime latency%d\n",quality==0?"STUDIO":"LIVE",seconds,seconds/2*100,bench.latencySamples());
    }
    std::printf("RESULT %d checks %d failures\n",checks,failures);return failures?1:0;
}
