#include "PluginProcessor.h"
#include "PluginEditor.h"
#include <cstdlib>
#include <cstring>
namespace {
const char*ids[]{"amount","time","tone","width","mix","dry","level","beats","start","end","bpm","voices","syllables","rhythm","style","bypass","gillQuality"};
const char*presets[7][6]={
 {"QUICK DROP","SLOW VINYL","TAPE START","HOOK BRAKE","HALF BEAT","LONG DECAY"},
 {"PHONE INTRO","WALKIE TALKIE","BROKEN SIGNAL","DISTANT RADIO","CLEAR CALL","HARD TRANSMISSION"},
 {"SOFT WHISPER","DARK GHOST","BRIGHT BREATH","WIDE SHADOW","ONLY GHOST","HAUNTED HOOK"},
 {"FALLING WORDS","RISING ADLIB","FIFTH TRAIL","DOTTED SPIRAL","TRIPLET DESCENT","ONLY TRAILS"},
 {"LOW ROBOT","METAL EDGE","BRIGHT CIRCUIT","SUBTLE ANDROID","BROKEN VOICE","ONLY METAL"},
 {"TRAP PICKUP","DOUBLE SPEED","TRIPLET BUILD","SHORT STUTTER","WIDE HOOK","SLOW CLIMB"},
 {"SMALL GANG","TRAP HOOK","STADIUM","DEEP CHANT","BRIGHT CROWD","LAZY CREW"}};
}
GillMotionProcessor::GillMotionProcessor(MotionKind k):AudioProcessor(BusesProperties().withInput("INPUT",juce::AudioChannelSet::stereo(),true).withOutput("OUTPUT",juce::AudioChannelSet::stereo(),true)),Thread("GILL MOTION render"),kind(k),apvts(*this,nullptr,juce::String(gill::motion::name(k))+"_STATE",layout(k)),engine(k){for(int i=0;i<17;++i)raw[i]=apvts.getRawParameterValue(ids[i]);setCurrentProgram(0);}
GillMotionProcessor::~GillMotionProcessor(){signalThreadShouldExit();generation++;stopThread(-1);}
juce::AudioProcessorValueTreeState::ParameterLayout GillMotionProcessor::layout(MotionKind k){juce::AudioProcessorValueTreeState::ParameterLayout p;auto f=[&](const char*id,const char*n,float lo,float hi,float step,float def){p.add(std::make_unique<juce::AudioParameterFloat>(juce::ParameterID{id,1},n,juce::NormalisableRange<float>(lo,hi,step),def));};
 const char*amount[]{"CURVE","DRIVE","BREATH","PITCH MOTION","DEPTH","RISE","HUMAN"};const char*time[]{"CHARACTER","CHARACTER","CHARACTER","FEEDBACK","CARRIER","CHARACTER","TIMING SPREAD"};
 f("amount",amount[int(k)],0,100,.1f,65);f("time",time[int(k)],0,k==MotionKind::Trail?75.f:100.f,.1f,50);f("tone","TONE",0,100,.1f,60);f("width","WIDTH",0,100,.1f,80);f("mix","EFFECT",0,100,.1f,70);f("dry","DIRECT",0,100,.1f,100);f("level","OUTPUT",-30,0,.1f,-6);f("beats","LENGTH BEATS",.25,16,.25,4);f("start","SOURCE IN",0,99,.1f,0);f("end","SOURCE OUT",1,100,.1f,100);f("bpm","MANUAL BPM",20,400,.1f,120);
 p.add(std::make_unique<juce::AudioParameterInt>(juce::ParameterID{"voices",1},"PEOPLE",4,24,12));p.add(std::make_unique<juce::AudioParameterInt>(juce::ParameterID{"syllables",1},"SYLLABLES",1,3,2));p.add(std::make_unique<juce::AudioParameterChoice>(juce::ParameterID{"rhythm",1},"GRID",juce::StringArray{"1/16 T","1/16","1/8 T","1/8","1/8 D","1/4","1/2"},3));
 const juce::StringArray styles[]{ {"BRAKE","START","BRAKE"},{"PHONE","WALKIE","BROKEN"},{"WHISPER","DARK","BRIGHT"},{"DOWN","UP","FIFTH"},{"LOW","MID","HIGH"},{"EVEN","ACCELERATE","END ROLL"},{"BALANCED","DEEP","BRIGHT"} };
 p.add(std::make_unique<juce::AudioParameterChoice>(juce::ParameterID{"style",1},"STYLE",styles[int(k)],0));p.add(std::make_unique<juce::AudioParameterBool>(juce::ParameterID{"bypass",1},"BYPASS",false));p.add(gill::qualityParameter(1));return p;}
float GillMotionProcessor::value(const char*id)const{for(int i=0;i<17;++i)if(std::strcmp(id,ids[i])==0){const float v=raw[i]->load();return std::isfinite(v)?v:0;}return 0;}
void GillMotionProcessor::setValue(const char*id,float x){if(!std::isfinite(x))return;if(auto*p=apvts.getParameter(id)){p->beginChangeGesture();p->setValueNotifyingHost(p->convertTo0to1(x));p->endChangeGesture();}}
bool GillMotionProcessor::isBusesLayoutSupported(const BusesLayout&b)const{const auto c=b.getMainInputChannelSet();return (c==juce::AudioChannelSet::mono()||c==juce::AudioChannelSet::stereo())&&c==b.getMainOutputChannelSet();}
gill::motion::Settings GillMotionProcessor::settings()const{gill::motion::Settings s;s.amount=value("amount")*.01f;s.time=value("time")*.01f;s.tone=value("tone")*.01f;s.width=value("width")*.01f;s.mix=value("mix")*.01f;s.dry=value("dry")*.01f;s.level=value("level");s.beats=value("beats");s.start=value("start")*.01f;s.end=value("end")*.01f;s.style=int(value("style"));s.rhythm=int(value("rhythm"));s.syllables=int(value("syllables"));s.voices=int(value("voices"));s.bpm=hostTempo?tempo.load():value("bpm");s.pro=quality.isPro();s.bypass=value("bypass")>.5f;return s;}
void GillMotionProcessor::prepareToPlay(double rate,int){signalThreadShouldExit();generation++;stopThread(-1);supported=std::isfinite(rate)&&rate>=8000&&rate<=192000;sampleRateView=supported?rate:48000;capture.prepare(sampleRateView);if(!captured()&&gill::motion::designer(kind))capture.arm();engine.prepare(sampleRateView);previewRate=std::min(48000.,sampleRateView.load());for(auto&v:preview)v.assign(size_t(previewRate*106),0);previewState=0;previewCommand=0;previewing=false;setLatencySamples(0);hadPosition=wasPlaying=false;startThread();}
void GillMotionProcessor::releaseResources(){previewCommand=2;capture.finish();}
void GillMotionProcessor::arm(){std::lock_guard<std::mutex>l(mutex);source.reset();rendered.reset();failed=false;generation++;capture.arm();previewCommand=2;}
void GillMotionProcessor::processBlock(juce::AudioBuffer<float>&b,juce::MidiBuffer&){process(b,false);}
void GillMotionProcessor::processBlockBypassed(juce::AudioBuffer<float>&b,juce::MidiBuffer&){process(b,true);}
void GillMotionProcessor::process(juce::AudioBuffer<float>&b,bool hostBypass){juce::ScopedNoDenormals guard;const int n=b.getNumSamples(),channels=std::min(2,b.getNumChannels());if(!supported||n==0||channels==0)return;auto s=settings();s.bypass=s.bypass||hostBypass;bool playing=true,host=false,known=false;std::int64_t position=0;bool tempoKnown=false;
 if(auto*h=getPlayHead())if(auto t=h->getPosition()){host=true;playing=t->getIsPlaying();if(auto p=t->getTimeInSamples()){position=*p;known=true;}if(auto bpm=t->getBpm())if(std::isfinite(*bpm)&&*bpm>=20&&*bpm<=400){tempo=*bpm;tempoKnown=true;s.bpm=*bpm;}}
 hostTempo=tempoKnown;if(!tempoKnown)s.bpm=value("bpm");if((wasPlaying&&!playing)||(known&&hadPosition&&playing&&position!=nextPosition))engine.reset();wasPlaying=playing;hadPosition=known;nextPosition=position+(playing?n:0);
 if(!isNonRealtime())capture.process(b.getReadPointer(0),channels>1?b.getReadPointer(1):nullptr,n,playing,host,position,known,s.bpm,s.syllables,kind!=MotionKind::Stutter,!s.bypass);
 if(hostBypass){int old=3;previewState.compare_exchange_strong(old,2);previewing=false;previewCommand=0;return;}engine.process(b.getWritePointer(0),channels>1?b.getWritePointer(1):nullptr,n,s);
 const int cmd=previewCommand.exchange(0);if(s.bypass||isNonRealtime()){int old=3;previewState.compare_exchange_strong(old,2);previewing=false;}
 if(cmd==2&&previewState==3)previewStop=std::max(1,int(sampleRateView*.01));if(cmd==1&&!s.bypass&&!isNonRealtime()){int old=2;if(previewState.compare_exchange_strong(old,3)){previewPosition=0;previewStop=0;previewing=true;}}
 if(previewState.load(std::memory_order_acquire)==3){const double advance=previewRate/sampleRateView;const int stopFade=std::max(1,int(sampleRateView*.01));for(int i=0;i<n;++i){if(previewPosition>=previewCount-1){previewState.store(2,std::memory_order_release);previewing=false;break;}float f=float(std::min({1.,previewPosition/(previewRate*.006),(previewCount-1-previewPosition)/(previewRate*.006)}));if(previewStop>0)f*=float(previewStop)/stopFade;const float a=gill::motion::sample(preview[0],previewPosition,false),c=gill::motion::sample(preview[1],previewPosition,false);for(int ch=0;ch<channels;++ch){const float wet=channels==1?(a+c)*.5f:ch==0?a:c;b.setSample(ch,i,b.getSample(ch,i)*(1-f)+wet*f);}previewPosition+=advance;if(previewStop>0&&--previewStop==0){previewState.store(2,std::memory_order_release);previewing=false;break;}}}
}
std::shared_ptr<const gill::motion::Clip>GillMotionProcessor::captured()const{std::lock_guard<std::mutex>l(mutex);return source;}
std::shared_ptr<const gill::motion::Render>GillMotionProcessor::result()const{std::lock_guard<std::mutex>l(mutex);return rendered;}
bool GillMotionProcessor::publishPreview(const gill::motion::Render&r){int old=previewState.load();if(old==1||old==3||!previewState.compare_exchange_strong(old,1))return false;previewCount=std::min(int(preview[0].size()),int(std::round(r.left.size()*previewRate/r.rate)));for(int i=0;i<previewCount;++i){preview[0][i]=gill::motion::sample(r.left,i*r.rate/previewRate,false);preview[1][i]=gill::motion::sample(r.right,i*r.rate/previewRate,false);}previewState.store(2,std::memory_order_release);return true;}
void GillMotionProcessor::run(){unsigned seen=generation.load();auto current=captured();gill::motion::Settings last;bool dirty=bool(current),pending=false;while(!threadShouldExit()){if(seen!=generation){seen=generation;current=captured();dirty=bool(current);pending=false;}
 const unsigned takeToken=generation;gill::motion::Clip take;if(capture.take(take)){auto next=std::make_shared<gill::motion::Clip>(std::move(take));std::lock_guard<std::mutex>l(mutex);if(takeToken==generation){source=next;current=next;dirty=true;}}
 auto now=settings();if(current&&(dirty||!(now==last))){const auto token=generation.load();auto made=std::make_shared<gill::motion::Render>();rendering=true;failed=false;bool ok=false;try{ok=gill::motion::render(kind,*current,now,*made,[&]{return threadShouldExit()||generation!=token||!(settings()==now);});}catch(const std::exception&){ok=false;}
 if(ok){std::lock_guard<std::mutex>l(mutex);if(token==generation){rendered=made;last=now;dirty=false;pending=true;}}else if(token==generation&&settings()==now){std::lock_guard<std::mutex>l(mutex);rendered.reset();failed=true;dirty=false;last=now;previewCommand=2;}rendering=false;}
 if(pending){auto r=result();if(r&&publishPreview(*r))pending=false;}wait(40);}}
juce::String GillMotionProcessor::statusText()const{if(capture.status()==gill::motion::Capture::Armed)return "ARMED - PLAY YOUR VOCAL";if(capture.status()==gill::motion::Capture::Recording)return "CAPTURING - STOP OR FINISH TO KEEP TAKE";if(rendering)return "RENDERING YOUR EFFECT";if(failed)return "ADJUST SOURCE IN / OUT OR RECAPTURE";if(result())return "READY - AUDITION OR DRAG WAV";return gill::motion::designer(kind)?"ARM + PLAY - SOURCE PASSES THROUGH":"LIVE EFFECT - ARM TO CAPTURE A WAV";}
juce::File GillMotionProcessor::exportWav(juce::String&error,const juce::File&overrideFolder){auto r=result();if(!r||rendering){error="Render the effect first.";return{};}if(exportedRender.lock()==r&&exported.existsAsFile())return exported;auto folder=overrideFolder==juce::File{}?juce::File::getSpecialLocation(juce::File::userDocumentsDirectory).getChildFile("Jill Plugins").getChildFile(getName()+" Takes"):overrideFolder;if(folder.createDirectory().failed()){error="Export folder is not writable.";return{};}
 auto file=folder.getNonexistentChildFile(getName()+"-"+juce::Time::getCurrentTime().formatted("%Y%m%d-%H%M%S"),".wav");juce::StringPairArray metadata;const auto start=r->endsAtOnset?r->onset-std::int64_t(r->left.size()):r->onset;if(r->anchored&&start>=0)metadata.set(juce::WavAudioFormat::bwavTimeReference,juce::String(start));juce::WavAudioFormat wav;auto stream=file.createOutputStream();std::unique_ptr<juce::AudioFormatWriter>writer(stream?wav.createWriterFor(stream.release(),r->rate,2,24,metadata,0):nullptr);if(!writer){error="Cannot create WAV.";return{};}const float*channels[]{r->left.data(),r->right.data()};const bool good=writer->writeFromFloatArrays(channels,2,int(r->left.size()))&&writer->flush();writer.reset();if(!good){file.deleteFile();error="WAV write failed.";return{};}file.withFileExtension(".txt").replaceWithText(getName()+"\n"+(r->endsAtOnset?"Align the END to the source onset.":"Align the START to the source onset.")+"\nSource position: "+(r->anchored?juce::String(double(r->onset)/r->rate,6)+" seconds":"unknown - place manually")+"\nTempo: "+juce::String(r->bpm,3)+" BPM\n");exported=file;exportedRender=r;return file;}
const juce::String GillMotionProcessor::getProgramName(int i){return presets[int(kind)][std::clamp(i,0,5)];}
void GillMotionProcessor::setCurrentProgram(int i){i=std::clamp(i,0,5);setValue("amount",i==0?55:i==1?75:i==2?85:i==3?35:i==4?65:95);setValue("time",i==0?35:i==1?55:i==2?65:i==3?48:i==4?25:70);setValue("tone",i==1?32:i==2?78:i==5?45:60);setValue("width",i==0?60:i==3?100:i==4?95:80);setValue("mix",i==4||i==5?100:70);setValue("dry",i==4||i==5||gill::motion::designer(kind)?0:100);setValue("style",kind==MotionKind::Brake?(i==2?1:0):kind==MotionKind::Stutter?(i==1||i==4?1:i==2?2:0):i%3);setValue("beats",i==3?1:i==4?.5f:i==5?8:4);setValue("rhythm",i==2||i==4?2:i==3?4:i==5?5:3);setValue("voices",i==0?6:i==1?12:i==2?24:i==3?10:16);setValue("syllables",i==3?1:i==4?3:2);setValue("level",-6);setValue("bypass",0);for(int j=0;j<17;++j)presetValues[j]=raw[j]->load();program=i;}
void GillMotionProcessor::getStateInformation(juce::MemoryBlock&out){auto state=apvts.copyState();state.setProperty("schema",1,nullptr);state.setProperty("program",program.load(),nullptr);if(auto c=captured()){juce::MemoryOutputStream audio;audio.writeDouble(c->rate);audio.writeDouble(c->bpm);audio.writeInt64(c->onset);audio.writeBool(c->anchored);audio.writeInt(int(c->left.size()));for(size_t i=0;i<c->left.size();++i){audio.writeFloat(c->left[i]);audio.writeFloat(c->right[i]);}state.setProperty("capture",audio.getMemoryBlock().toBase64Encoding(),nullptr);}if(auto xml=state.createXml())copyXmlToBinary(*xml,out);}
void GillMotionProcessor::setStateInformation(const void*data,int size){if(!data||size<=0||size>32*1024*1024)return;auto xml=getXmlFromBinary(data,size);if(!xml||!xml->hasTagName(getName()+"_STATE"))return;auto state=juce::ValueTree::fromXml(*xml);if(!state.isValid()||int(state.getProperty("schema",0))!=1)return;juce::StringArray ids;for(auto child:state){if(!child.hasType("PARAM"))return;auto id=child["id"].toString();auto*p=apvts.getParameter(id);if(!p||ids.contains(id))return;ids.add(id);auto str=child["value"].toString();char*end=nullptr;double v=std::strtod(str.toRawUTF8(),&end);auto range=p->getNormalisableRange();if(str.isEmpty()||!end||*end||!std::isfinite(v)||v<range.start-.001||v>range.end+.001||(p->isDiscrete()&&v!=std::floor(v)))return;}if(ids.size()!=getParameters().size())return;
 std::shared_ptr<gill::motion::Clip>restore;auto encoded=state.getProperty("capture").toString();if(encoded.isNotEmpty()){juce::MemoryBlock bytes;if(!bytes.fromBase64Encoding(encoded)||bytes.getSize()<29||bytes.getSize()>20*1024*1024)return;juce::MemoryInputStream audio(bytes,false);restore=std::make_shared<gill::motion::Clip>();restore->rate=audio.readDouble();restore->bpm=audio.readDouble();restore->onset=audio.readInt64();restore->anchored=audio.readBool();int count=audio.readInt();if(!std::isfinite(restore->rate)||restore->rate<8000||restore->rate>192000||!std::isfinite(restore->bpm)||restore->bpm<20||restore->bpm>400||count<2||count>restore->rate*12.1||audio.getNumBytesRemaining()!=count*8LL)return;restore->left.resize(count);restore->right.resize(count);for(int i=0;i<count;++i){restore->left[i]=audio.readFloat();restore->right[i]=audio.readFloat();if(!std::isfinite(restore->left[i])||!std::isfinite(restore->right[i])||std::abs(restore->left[i])>16||std::abs(restore->right[i])>16)return;}}
 state.removeProperty("capture",nullptr);setCurrentProgram(std::clamp(int(state.getProperty("program",0)),0,5));apvts.replaceState(state);for(auto child:state)if(auto*p=apvts.getParameter(child["id"].toString()))p->setValueNotifyingHost(p->convertTo0to1(float(child["value"])));program=std::clamp(int(state.getProperty("program",0)),0,5);previewCommand=2;capture.finish();{std::lock_guard<std::mutex>l(mutex);source=restore;rendered.reset();generation++;}}
juce::AudioProcessorEditor*GillMotionProcessor::createEditor(){return new GillMotionEditor(*this);}

bool GillMotionProcessor::presetMatches()const{for(int i=0;i<17;++i)if(i!=8&&i!=9&&i!=10&&i!=16&&std::abs(raw[i]->load()-presetValues[i].load())>.011f)return false;return true;}
