#include "../Source/PluginProcessor.h"
#include "../Source/PluginEditor.h"
#include <cstdio>
#include <random>
#include <cstdlib>
#include <new>
static thread_local bool countAllocations=false;static thread_local int allocationCount=0;
void*operator new(std::size_t n){if(countAllocations)++allocationCount;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](std::size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}void operator delete(void*p,std::size_t)noexcept{std::free(p);}void operator delete[](void*p,std::size_t)noexcept{std::free(p);}
#if JUCE_MAC
extern "C" void gillInitialiseMacTestApplication();
#endif
namespace {
int checks=0,failures=0;void check(bool good,const char*message){++checks;if(!good)++failures;std::printf("%s %s\n",good?"PASS":"FAIL",message);std::fflush(stdout);}
template<class F>bool waitFor(F f,int milliseconds=60000){auto deadline=juce::Time::getMillisecondCounter()+milliseconds;while(juce::Time::getMillisecondCounter()<deadline){if(f())return true;juce::Thread::sleep(10);}return f();}
std::vector<float>tone(double hz,double seconds,double fs=12000){std::vector<float>x(std::size_t(std::llround(seconds*fs)));for(std::size_t i=0;i<x.size();++i)x[i]=float(.2*std::sin(2*juce::MathConstants<double>::pi*hz*i/fs)+.06*std::sin(4*juce::MathConstants<double>::pi*hz*i/fs));return x;}
juce::File fixture(const juce::File&dir,const juce::String&name,double seconds,double fs=48000,bool lateOnly=false){auto file=dir.getChildFile(name);auto out=file.createOutputStream();out->setPosition(0);out->truncate();juce::WavAudioFormat wav;std::unique_ptr<juce::AudioFormatWriter>w(wav.createWriterFor(out.release(),fs,2,24,{},0));juce::AudioBuffer<float>b(2,4096);auto size=juce::int64(std::llround(seconds*fs));for(juce::int64 offset=0;offset<size;offset+=4096){int n=int(std::min<juce::int64>(4096,size-offset));for(int i=0;i<n;++i){double t=(offset+i)/fs;float x=lateOnly&&t<seconds-2?0:float(.2*std::sin(2*juce::MathConstants<double>::pi*220*t)+.06*std::sin(4*juce::MathConstants<double>::pi*220*t));b.setSample(0,i,x);b.setSample(1,i,x*.8f);}w->writeFromAudioSampleBuffer(b,0,n);}return file;}
std::unique_ptr<juce::AudioFormatReader>read(const juce::File&file){juce::WavAudioFormat wav;auto stream=file.createInputStream();return stream?std::unique_ptr<juce::AudioFormatReader>(wav.createReaderFor(stream.release(),true)):nullptr;}
double renderedPitch(const juce::File&file){auto reader=read(file);if(!reader)return 0;juce::AudioBuffer<float>b(2,int(reader->lengthInSamples));reader->read(&b,0,b.getNumSamples(),0,true,true);std::vector<float>mono;for(double i=reader->sampleRate*.4;i<reader->sampleRate*1.4;i+=reader->sampleRate/12000)mono.push_back(b.getSample(0,int(i)));auto p=gill::note::analyse(mono,mono.size()/12000.);std::vector<float>m;for(auto f:p.frames)if(f.confidence>.8)m.push_back(f.midi);return gill::note::median(m);}
double pitchSpread(const juce::File&file){auto reader=read(file);if(!reader)return 100;juce::AudioBuffer<float>b(2,int(reader->lengthInSamples));reader->read(&b,0,b.getNumSamples(),0,true,true);std::vector<float>mono;for(double i=0;i<reader->lengthInSamples;i+=reader->sampleRate/12000)mono.push_back(b.getSample(0,int(i)));auto p=gill::note::analyse(mono,mono.size()/12000.);std::vector<float>m;for(std::size_t i=20;i+20<p.frames.size();++i)if(p.frames[i].confidence>.8)m.push_back(p.frames[i].midi);if(m.empty())return 100;float centre=gill::note::median(m);double sum=0;for(auto v:m)sum+=(v-centre)*(v-centre);return std::sqrt(sum/m.size());}
bool bounds(juce::Component&root,juce::Component&c){for(auto*child:c.getChildren())if(child->isVisible()&&(!root.getLocalBounds().contains(root.getLocalArea(child,child->getLocalBounds()))||!bounds(root,*child)))return false;return true;}
juce::Component*named(juce::Component&root,const juce::String&name){if(root.getName()==name)return &root;for(auto*c:root.getChildren())if(auto*found=named(*c,name))return found;return nullptr;}
bool keyboardSafe(juce::Component&root){if(dynamic_cast<juce::TextEditor*>(&root))return true;if(root.getWantsKeyboardFocus()||root.getMouseClickGrabsKeyboardFocus())return false;for(auto*c:root.getChildren())if(!keyboardSafe(*c))return false;return true;}
struct PlayHead:juce::AudioPlayHead{bool playing=false;juce::int64 sample=0;juce::Optional<PositionInfo>getPosition()const override{PositionInfo p;p.setIsPlaying(playing);p.setTimeInSamples(sample);return p;}};
}
int main(){
#if JUCE_MAC
gillInitialiseMacTestApplication();
#endif
juce::ScopedJuceInitialiser_GUI gui;using namespace gill::note;auto dir=juce::File::getCurrentWorkingDirectory().getChildFile("test-audio");dir.createDirectory();
#if JUCE_WINDOWS
_putenv_s("GILL_NOTE_AUDIO_ROOT",dir.getChildFile("cache").getFullPathName().toRawUTF8());
#else
setenv("GILL_NOTE_AUDIO_ROOT",dir.getChildFile("cache").getFullPathName().toRawUTF8(),1);
#endif
for(double frequency:{60.,82.4069,110.,220.,329.6276,440.,880.,987.7666}){auto x=tone(frequency,1);auto p=analyse(x,1);std::vector<float>m;for(std::size_t i=10;i+10<p.frames.size();++i)if(p.frames[i].confidence>.8)m.push_back(p.frames[i].midi);float measured=median(m);std::printf("frequency %.3f measured %.5f expected %.5f\n",frequency,measured,midiFor(frequency));check(m.size()>70&&std::abs(measured-midiFor(frequency))<.08f,"Monophonic harmonic pitch accuracy within eight cents");check(p.notes.size()==1,"Sustained note remains one editable region");}
{std::vector<float>x(48000);for(int part=0;part<3;++part){auto n=tone(part==0?220:part==1?261.6256:329.6276,.7);std::copy(n.begin(),n.end(),x.begin()+12000*part+1200);}auto p=analyse(x,4);check(p.notes.size()==3,"Three separated notes yield three regions");if(p.notes.size()==3){check(std::abs(p.notes[0].start-.1)<.05&&std::abs(p.notes[2].end-2.8)<.05,"Note boundaries within fifty milliseconds");check(std::abs(p.notes[1].detected-60)<.08,"Middle note is C4");}std::mt19937 random(41);std::uniform_real_distribution<float>d(-.04f,.04f);for(auto&v:x)v=d(random);check(analyse(x,4).notes.empty(),"Noise is not presented as stable notes");}
{Plan p;p.duration=300;p.frames.resize(30000,{57,1,.1});p.notes.push_back({0,298,299,57,60,0,1});check(shiftAt(p,298.5)==3&&shiftAt(p,297)==0&&shiftAt(p,300)==0,"Manual region reaches end of five-minute timeline only");check(snap(61,0,1)==60&&snap(63.2f,0,2)==63,"Scale snapping uses major and minor intervals");}
auto owner=std::make_unique<GillNoteProcessor>();auto&p=*owner;p.setPlayConfigDetails(2,2,48000,127);p.prepareToPlay(48000,127);check(p.getName()=="GILLNOTE"&&p.getLatencySamples()==0,"Product identity and zero reported latency");juce::MidiBuffer midi;
for(double fs:{8000.,44100.,48000.,96000.,192000.})for(bool live:{true,false}){p.prepareToPlay(fs,127);p.setValue("gillQuality",live?0:1);juce::AudioBuffer<float>b(2,127);for(int c=0;c<2;++c)for(int i=0;i<127;++i)b.setSample(c,i,float(.1*std::sin(i*.19)));auto before=b;allocationCount=0;countAllocations=true;p.processBlock(b,midi);countAllocations=false;bool same=true;for(int c=0;c<2;++c)for(int i=0;i<127;++i)same=same&&b.getSample(c,i)==before.getSample(c,i);check(same&&p.getLatencySamples()==0&&allocationCount==0,"Idle LIVE/PRO exact dry, zero PDC and zero audio allocations");p.processBlockBypassed(b,midi);check(b.getSample(1,83)==before.getSample(1,83),"Host bypass is exact dry");}
p.prepareToPlay(48000,127);auto input=fixture(dir,"original.wav",2);p.engine.importFile(input);check(waitFor([&]{return p.engine.state==Engine::Ready&&p.engine.exportFile().existsAsFile();}),"WAV import analyses and renders a real take");auto plan=p.engine.plan();check(plan.notes.size()==1&&std::abs(plan.notes[0].detected-57)<.1,"Imported A3 identified correctly");auto original=p.engine.exportFile();auto before=read(input),neutral=read(original);bool exact=before&&neutral&&before->lengthInSamples==neutral->lengthInSamples;if(exact){juce::AudioBuffer<float>a(2,96000),b(2,96000);before->read(&a,0,96000,0,true,true);neutral->read(&b,0,96000,0,true,true);for(int c=0;c<2;++c)for(int i=0;i<96000;++i)exact=exact&&a.getSample(c,i)==b.getSample(c,i);}check(exact,"Neutral export retains every source sample and exact duration");
if(!plan.notes.empty()){auto note=plan.notes[0];note.target+=3;auto old=p.engine.completedRevision.load();p.engine.edit(note);check(p.engine.exportFile()==juce::File{},"Editing invalidates obsolete exported result");p.engine.render();check(waitFor([&]{return p.engine.completedRevision>old&&p.engine.state==Engine::Ready;}),"Pitch edit produces current asynchronous render");auto exported=p.engine.exportFile();auto rendered=read(exported);check(rendered&&rendered->lengthInSamples==96000&&rendered->numChannels==2,"Pitch render duration and channel count are exact");double actual=renderedPitch(exported);std::printf("rendered midi %.5f\n",actual);check(std::abs(actual-60)<.12,"Actual rendered audio transposes A3 to C4");bool finite=true;if(rendered){juce::AudioBuffer<float>b(2,96000);rendered->read(&b,0,96000,0,true,true);for(int c=0;c<2;++c)for(int i=0;i<96000;++i)finite=finite&&std::isfinite(b.getSample(c,i));}check(finite,"Rendered stereo audio is finite");
 juce::MemoryBlock saved;p.getStateInformation(saved);auto restored=std::make_unique<GillNoteProcessor>();restored->prepareToPlay(48000,127);restored->setStateInformation(saved.getData(),int(saved.getSize()));check(waitFor([&]{return restored->engine.state==Engine::Ready&&restored->engine.exportFile().existsAsFile();}),"Owned audio cache and edits restore from project state");check(std::abs(restored->engine.plan().notes[0].target-60)<.1,"Project recall retains edited target pitch");check(restored->engine.exportFile()!=exported&&exported.existsAsFile(),"Recall preserves every previously exported WAV");p.engine.undo();check(std::abs(p.engine.plan().notes[0].target-57)<.1,"Undo restores original pitch");p.engine.redo();check(std::abs(p.engine.plan().notes[0].target-60)<.1,"Redo restores edited pitch");
 auto blank=std::make_unique<GillNoteProcessor>();juce::MemoryBlock empty;blank->getStateInformation(empty);restored->setStateInformation(empty.getData(),int(empty.getSize()));check(restored->engine.exportFile()==juce::File{}&&restored->engine.saved().token.isEmpty(),"Empty recall detaches prior audio and export immediately");check(waitFor([&]{return restored->engine.state==Engine::Idle&&restored->engine.plan().notes.empty();}),"Empty recall clears old note regions");
}
{p.engine.render();check(waitFor([&]{return p.engine.exportFile().existsAsFile();}),"Redo is rendered before audition");p.engine.audition(.2);check(waitFor([&]{return p.engine.previewing.load();}),"Disk audition fills its bounded FIFO");juce::AudioBuffer<float>b(2,127);b.clear();allocationCount=0;countAllocations=true;p.engine.process(b,false,false,0,false,false);countAllocations=false;check(b.getMagnitude(0,127)>.01f&&allocationCount==0,"PRO audition outputs rendered audio without callback allocations");for(int c=0;c<2;++c)for(int i=0;i<127;++i)b.setSample(c,i,.125f);p.engine.process(b,false,false,0,true,false);check(b.getSample(0,65)==.125f&&!p.engine.previewing,"LIVE immediately cancels preview and is exact dry");p.engine.audition(.2);check(waitFor([&]{return p.engine.previewing.load();}),"Audition restarts after LIVE interruption");p.engine.process(b,false,false,0,false,true);check(b.getSample(0,65)==.125f&&!p.engine.previewing,"Host bypass cancels preview without altering the source");
 auto n=p.engine.plan().notes[0];n.start=.25;n.end=1.75;n.strength=.75f;p.engine.edit(n);auto edited=p.engine.plan();check(std::abs(edited.notes[0].start-.25)<1.e-9&&std::abs(edited.notes[0].end-1.75)<1.e-9&&edited.notes[0].strength==.75f,"Correction strength and editable region boundaries persist");check(shiftAt(edited,.1)==0&&shiftAt(edited,1.9)==0,"Boundary edits leave surrounding audio unshifted");p.engine.setFormants(false);check(p.engine.exportFile()==juce::File{},"Changed render settings invalidate obsolete export");
}
check(!Engine::validToken("../../source.wav")&&!Engine::validToken("C:/audio.wav"),"State cannot read arbitrary audio paths");
{auto full=fixture(dir,"five-minutes.wav",300,8000,true);p.engine.importFile(full);check(waitFor([&]{return p.engine.state==Engine::Ready&&p.engine.exportFile().existsAsFile();},90000),"Full five-minute transfer analyses and exports");auto fullplan=p.engine.plan();check(fullplan.duration==300&&!fullplan.notes.empty()&&fullplan.notes.back().end>299.9,"Detected notes extend to end of five-minute source");auto r=read(p.engine.exportFile());check(r&&r->lengthInSamples==2400000,"Five-minute WAV exports all 2,400,000 source frames");
 auto n=fullplan.notes.back();n.target+=2;p.engine.edit(n);p.engine.render();check(waitFor([&]{return p.engine.state==Engine::Rendering;}),"Long offline render enters worker state");n.target+=3;p.engine.edit(n);p.engine.render();check(waitFor([&]{return p.engine.state==Engine::Ready&&p.engine.exportFile().existsAsFile();}),"Concurrent edit cancels obsolete render and publishes latest request");check(std::abs(p.engine.plan().notes.back().target-n.target)<.001f,"Concurrent render retains latest note target");
 n.target+=1;p.engine.edit(n);p.engine.render();check(waitFor([&]{return p.engine.state==Engine::Rendering;}),"Second render starts for reset-race regression");p.engine.clear();check(p.engine.exportFile()==juce::File{}&&p.engine.saved().token.isEmpty(),"Clear immediately detaches a rendering document");check(waitFor([&]{return p.engine.state==Engine::Idle&&p.engine.plan().frames.empty();}),"Worker cancels render before clearing document");
 p.engine.restore("11111111111111111111111111111111",0,{});check(waitFor([&]{return p.engine.state==Engine::Error;}),"Missing owned cache is explicitly reported");check(p.engine.exportFile()==juce::File{}&&p.engine.plan().notes.empty(),"Missing source cannot expose a previous render or notes");}
{auto file=dir.getChildFile("vibrato.wav");auto stream=file.createOutputStream();stream->setPosition(0);stream->truncate();juce::WavAudioFormat wav;std::unique_ptr<juce::AudioFormatWriter>w(wav.createWriterFor(stream.release(),48000,2,24,{},0));juce::AudioBuffer<float>b(2,96000);double phase=0;for(int i=0;i<96000;++i){double midi=57+.45*std::sin(2*juce::MathConstants<double>::pi*2*i/48000);phase+=2*juce::MathConstants<double>::pi*frequencyFor(float(midi))/48000;float sample=float(.2*std::sin(phase));b.setSample(0,i,sample);b.setSample(1,i,sample);}w->writeFromAudioSampleBuffer(b,0,96000);w.reset();p.engine.importFile(file);check(waitFor([&]{return p.engine.state==Engine::Ready&&p.engine.exportFile().existsAsFile();}),"Vibrato source is captured as an editable take");auto notes=p.engine.plan().notes;check(notes.size()==1,"Natural half-semitone vibrato is retained inside one note");for(auto n:notes){n.strength=1;p.engine.edit(n);}p.engine.render();check(waitFor([&]{return p.engine.state==Engine::Ready&&p.engine.exportFile().existsAsFile();}),"Full pitch correction renders successfully");double originalSpread=pitchSpread(file),correctedSpread=pitchSpread(p.engine.exportFile());std::printf("pitch spread original %.5f corrected %.5f\n",originalSpread,correctedSpread);check(correctedSpread<originalSpread*.6,"Actual correction audio reduces within-note pitch variation");}

{PlayHead host;host.sample=48000*17;host.playing=false;p.setPlayHead(&host);p.prepareToPlay(48000,256);p.engine.arm();check(waitFor([&]{return p.engine.state==Engine::Armed;}),"Capture arms without playing");juce::AudioBuffer<float>b(2,256);b.clear();p.processBlock(b,midi);check(p.engine.capturedSeconds==0,"Stopped transport records no audio");host.playing=true;for(int block=0;block<200;++block){for(int i=0;i<256;++i){float x=float(.2*std::sin(2*juce::MathConstants<double>::pi*220*(block*256+i)/48000));b.setSample(0,i,x);b.setSample(1,i,x);}auto original=b;allocationCount=0;countAllocations=true;p.processBlock(b,midi);countAllocations=false;if(block==50)check(allocationCount==0&&b.getSample(0,40)==original.getSample(0,40),"Active capture stays dry and allocates nothing in audio callback");host.sample+=256;if(block%16==0)juce::Thread::sleep(1);}p.engine.stop();p.processBlock(b,midi);check(waitFor([&]{return p.engine.state==Engine::Ready&&p.engine.exportFile().existsAsFile();}),"Transport capture finalises to editable notes");check(std::abs(p.engine.plan().start-17)<1.e-9&&p.engine.plan().duration>1,"Capture retains original song timeline anchor");p.setPlayHead(nullptr);}
{std::unique_ptr<juce::AudioProcessorEditor>editor(p.createEditor());check(editor->getWidth()==864&&editor->getHeight()==560&&bounds(*editor,*editor),"Compact PRISM editor controls remain inside rectangle");check(keyboardSafe(*editor),"Plugin controls preserve DAW Space/Return keyboard ownership");
 if(auto*roll=named(*editor,"NOTE ROLL")){auto plan=p.engine.plan();check(!plan.notes.empty(),"Real detected notes populate editor at first paint");if(!plan.notes.empty()){auto note=plan.notes[0];float low=std::floor(std::min(55.f,note.detected-4)),high=std::ceil(std::max(70.f,note.detected+4)),height=float(roll->getHeight()-29)/(high-low+1);juce::Point<float>down(43+float((note.start+note.end)*.5/2)*(roll->getWidth()-49),roll->getHeight()-6-(note.target-low+.5f)*height);auto now=juce::Time::getCurrentTime();auto event=[&](juce::Point<float>position,bool dragging){return juce::MouseEvent(juce::Desktop::getInstance().getMainMouseSource(),position,juce::ModifierKeys(juce::ModifierKeys::leftButtonModifier),1,0,0,0,0,roll,roll,now,down,now,1,dragging);};roll->mouseDown(event(down,false));roll->mouseDrag(event(down.translated(0,-3*height),true));roll->mouseUp(event(down.translated(0,-3*height),true));check(std::abs(p.engine.plan().notes[0].target-note.target-3)<.001,"Actual piano-roll drag changes pitch by three semitones");}}
for(float scale:{1.f,1.5f,2.f}){auto img=editor->createComponentSnapshot(editor->getLocalBounds(),true,scale);auto file=juce::File::getCurrentWorkingDirectory().getChildFile("GILLNOTE-UI-"+juce::String(img.getWidth())+"x"+juce::String(img.getHeight())+".png");auto stream=file.createOutputStream();if(stream){stream->setPosition(0);stream->truncate();}juce::PNGImageFormat png;check(stream&&png.writeImageToStream(img,*stream),"Native editor screenshot rendered at scale");}
 // This visual evidence consumes the real, pitch-edited render through the
 // processor. No note, meter or playhead values are invented for the image.
 p.engine.render();
 check(waitFor([&]{return p.engine.state==Engine::Ready&&p.engine.exportFile().existsAsFile();}),"Edited piano-roll take renders before electric preview evidence");
 p.audition(.35);
 check(waitFor([&]{return p.engine.previewing.load();}),"Actual audition is ready for electric note display");
 juce::AudioBuffer<float>previewAudio(2,256);previewAudio.clear();p.processBlock(previewAudio,midi);
 const double firstTime=p.engine.previewSeconds.load();
 check(p.engine.previewing&&previewAudio.getMagnitude(0,256)>.01f&&firstTime>.35&&firstTime<.37&&p.getLatencySamples()==0,"Electric preview uses audible rendered samples and their actual sample clock");
 juce::Timer::callPendingTimersSynchronously();
 auto firstImage=editor->createComponentSnapshot(editor->getLocalBounds());
 auto writePreview=[&](const juce::Image&image,const char*name){auto file=juce::File::getCurrentWorkingDirectory().getChildFile(name);auto stream=file.createOutputStream();if(stream){stream->setPosition(0);stream->truncate();}juce::PNGImageFormat png;return stream&&png.writeImageToStream(image,*stream);};
 check(writePreview(firstImage,"GILLNOTE-UI-AUDITION-864x560.png"),"Native electric note image saved during processed audition");
 for(int i=0;i<32;++i){previewAudio.clear();p.processBlock(previewAudio,midi);if((i&7)==0)juce::Thread::sleep(1);}
 const double secondTime=p.engine.previewSeconds.load();juce::Timer::callPendingTimersSynchronously();
 auto secondImage=editor->createComponentSnapshot(editor->getLocalBounds());int changedPixels=0;
 if(auto*roll=named(*editor,"NOTE ROLL")){auto region=editor->getLocalArea(roll,roll->getLocalBounds());for(int y=region.getY();y<region.getBottom();++y)for(int x=region.getX();x<region.getRight();++x)if(firstImage.getPixelAt(x,y)!=secondImage.getPixelAt(x,y))++changedPixels;}
 check(p.engine.previewing&&secondTime>firstTime+.16&&changedPixels>100,"Illuminated piano-roll playhead advances only after processing more preview audio");
 check(writePreview(secondImage,"GILLNOTE-UI-AUDITION-LATER-864x560.png"),"Second native electric note image records the later audible position");
 std::printf("Electric preview positions %.6f -> %.6f seconds; changed roll pixels %d; output peak %.6f\n",firstTime,secondTime,changedPixels,previewAudio.getMagnitude(0,256));
 p.engine.stopAudition();
}
std::printf("GILLNOTE: %d checks, %d failures\n",checks,failures);return failures?1:0;
}
