#include "PluginProcessor.h"
#include "PluginEditor.h"
#include <cstdlib>
#include <set>
using namespace gill::mix07;
namespace {
const char*presets[]{"KEEP MY BALANCE","RAP FRONT","HOOK STACK","ADLIB SPACE","GENTLE RESET"};
void nameCopy(char*dest,const juce::String&name){auto text=name.trim().substring(0,48);while(text.getNumBytesAsUTF8()>95)text=text.dropLastCharacters(1);std::memset(dest,0,96);std::memcpy(dest,text.toRawUTF8(),text.getNumBytesAsUTF8());}
RoleHint namedHint(const char*name,const LearnedTrack*audio=nullptr){const auto s=juce::String::fromUTF8(name).toUpperCase();Role r=Role::automatic;int matches=0;auto match=[&](bool yes,Role role){if(yes){r=role;++matches;}};
 match(s.contains("MAIN")||s.contains("LEAD")||s.contains("HAUPT"),Role::main);match(s.contains("DOUBLE")||s.contains("DUB")||s.contains("LAYER"),Role::doubleVoice);match(s.contains("ADLIB")||s.contains("AD-LIB"),Role::adlib);match(s.contains("BEAT")||s.contains("INSTRUMENTAL"),Role::beat);
 if(matches==1){bool consistent=audio&&audio->active>=50;if(consistent&&r!=Role::beat)consistent=audio->voiced>audio->active*.35;if(consistent&&r==Role::beat)consistent=audio->voiced<audio->active*.35;return{r,consistent?.85f:.65f,consistent};}if(matches>1)return{};return audio?audioHint(*audio):RoleHint{};
}
}
juce::AudioProcessorValueTreeState::ParameterLayout GillMixProcessor::layout(GillMixKind k){juce::AudioProcessorValueTreeState::ParameterLayout p;p.add(gill::qualityParameter());p.add(std::make_unique<juce::AudioParameterBool>(juce::ParameterID{"bypass",1},"BYPASS",false));if(k==GillMixKind::link)p.add(std::make_unique<GillLinkGainParameter>());else{auto add=[&](const char*id,const char*name,float lo,float hi,float def){p.add(std::make_unique<juce::AudioParameterFloat>(juce::ParameterID{id,1},name,juce::NormalisableRange<float>(lo,hi,.1f),def));};add("changeLimit","CHANGE LIMIT",0,6,3);add("doubleOffset","DOUBLE OFFSET",-18,6,-6);add("adlibOffset","ADLIB OFFSET",-18,6,-9);add("beatOffset","BEAT OFFSET",-18,6,-2);}return p;}
GillMixProcessor::GillMixProcessor(GillMixKind k):AudioProcessor(BusesProperties().withInput("INPUT",juce::AudioChannelSet::stereo(),true).withOutput("OUTPUT",juce::AudioChannelSet::stereo(),true)),kind(k),apvts(*this,nullptr,k==GillMixKind::master?"GILLMIX_STATE":"GILLLINK_STATE",layout(k)),quality(*this,apvts),bus(k==GillMixKind::master){local.persistent=newId();local.session=newId();nameCopy(local.name,k==GillMixKind::master?"MY MIX":"LINK");gainParameter=dynamic_cast<GillLinkGainParameter*>(apvts.getParameter("trackLevel"));bypassRaw=apvts.getRawParameterValue("bypass");service();startTimer(40);}
GillMixProcessor::~GillMixProcessor(){stopTimer();}
bool GillMixProcessor::isBusesLayoutSupported(const BusesLayout&l)const{const auto c=l.getMainOutputChannelSet();return(c==juce::AudioChannelSet::mono()||c==juce::AudioChannelSet::stereo())&&c==l.getMainInputChannelSet();}
void GillMixProcessor::prepareToPlay(double rate,int){audio.prepare(rate,gainParameter&&!(bypassRaw&&bypassRaw->load()>.5f)?gainParameter->value.db():0);setLatencySamples(0);}
float GillMixProcessor::parameter(const char*id)const noexcept{auto*p=apvts.getRawParameterValue(id);return p?p->load(std::memory_order_relaxed):0;}
void GillMixProcessor::setParameter(const char*id,float v){if(auto*p=apvts.getParameter(id)){p->beginChangeGesture();p->setValueNotifyingHost(p->convertTo0to1(v));p->endChangeGesture();}}
template<class T>void GillMixProcessor::process(juce::AudioBuffer<T>&buffer,bool bypass){AudioContext c{};if(auto*head=getPlayHead())if(auto pos=head->getPosition()){if(auto n=pos->getTimeInSamples()){c.position=*n;c.positionValid=true;}c.playing=pos->getIsPlaying();}audio.process(buffer.getArrayOfWritePointers(),buffer.getNumChannels(),buffer.getNumSamples(),gainParameter?gainParameter->value.db():0,bypass||(bypassRaw&&bypassRaw->load(std::memory_order_relaxed)>.5f),c,kind==GillMixKind::link,quality.isPro());}
void GillMixProcessor::processBlock(juce::AudioBuffer<float>&b,juce::MidiBuffer&){process(b,false);}void GillMixProcessor::processBlock(juce::AudioBuffer<double>&b,juce::MidiBuffer&){process(b,false);}void GillMixProcessor::processBlockBypassed(juce::AudioBuffer<float>&b,juce::MidiBuffer&){process(b,true);}void GillMixProcessor::processBlockBypassed(juce::AudioBuffer<double>&b,juce::MidiBuffer&){process(b,true);}
LocalState GillMixProcessor::localSnapshot()const{const std::lock_guard<std::mutex>lock(modelMutex);auto s=local;s.gain=gainParameter?gainParameter->value.snapshot():0;return s;}
void GillMixProcessor::setLocalName(const juce::String&name){const std::lock_guard<std::mutex>lock(modelMutex);char next[96]{};nameCopy(next,name);if(std::strcmp(next,local.name)!=0){std::memcpy(local.name,next,96);++local.metadataRevision;}}
void GillMixProcessor::setLocalRole(Role r){const std::lock_guard<std::mutex>lock(modelMutex);local.role=static_cast<uint32_t>(r);local.manualRole=r!=Role::automatic;++local.metadataRevision;}
void GillMixProcessor::setLocalLock(bool b){const std::lock_guard<std::mutex>lock(modelMutex);local.locked=b;++local.metadataRevision;}
void GillMixProcessor::newIdentity(){const std::lock_guard<std::mutex>lock(modelMutex);local.persistent=newId();local.session=newId();local.controller={};pendingPicks={};++local.epoch;bus.invalidate(local.epoch);++local.metadataRevision;restoreSerial.fetch_add(1);}
void GillMixProcessor::disconnect(){bus.disconnect(bus.runtimeId());audio.requestLearn(0);status="NOT CONNECTED";}
void GillMixProcessor::updateTrackProperties(const TrackProperties&p){if(p.name){const std::lock_guard<std::mutex>lock(modelMutex);if(juce::String(local.name)=="LINK"){nameCopy(local.name,*p.name);++local.metadataRevision;}}}
void GillMixProcessor::handleCommand(const Command&c){
 if(!gainParameter||!c.transaction)return;
 if(cachedAck.transaction==c.transaction&&cachedAck.phase==c.phase){bus.acknowledge(cachedAck);return;}
 bool changed=false;Ack ack{c.transaction,0,0,c.phase,Status::conflict,0,0};
 {
  const std::lock_guard<std::mutex>lock(modelMutex);ack.gain=gainParameter->value.snapshot();ack.metadata=local.metadataRevision;ack.role=local.role;
  const auto&r=c.change;
  if(nowMs()>c.deadline)ack.status=Status::timedOut;
  else if(local.epoch!=r.target.epoch||restoring.load()||!bus.commandActive(c))ack.status=Status::recalled;
  else if(!local.locked&&ack.gain==r.expectedGain&&local.metadataRevision==r.expectedMetadata&&std::isfinite(r.newDb)&&r.newDb>=-24&&r.newDb<=6&&r.newRole<=4&&std::abs(r.newDb-GainValue::decode(ack.gain))<=r.limit+.011f){
   if(c.phase==Phase::prepare)ack.status=Status::ready;
   else if(c.phase==Phase::commit&&gainParameter->value.compareSet(r.expectedGain,r.newDb,ack.gain)){local.role=r.newRole;local.manualRole=r.manualRole;++local.metadataRevision;ack.metadata=local.metadataRevision;ack.role=local.role;ack.status=Status::applied;changed=true;}
  }
 }
 if(changed){gainParameter->beginChangeGesture();gainParameter->publish();gainParameter->endChangeGesture();}
 cachedAck=ack;bus.acknowledge(ack);
}
GillMixProcessor::Pick*GillMixProcessor::pick(Id id,bool create){for(auto&p:picks)if(p.id==id)return&p;if(create)for(auto&p:picks)if(!p.id){p.id=id;return&p;}return nullptr;}
void GillMixProcessor::chooseTrack(Id id,bool b){if(txPhase){status="WAIT FOR CURRENT APPLY";return;}const std::lock_guard<std::mutex>lock(modelMutex);if(auto*p=pick(id,true))p->selected=b;proposalCount=0;}
void GillMixProcessor::chooseRole(Id id,Role r){if(txPhase){status="WAIT FOR CURRENT APPLY";return;}{const std::lock_guard<std::mutex>lock(modelMutex);if(auto*p=pick(id,true)){p->role=static_cast<uint32_t>(r);p->manual=r!=Role::automatic;}}proposalCount=0;if(!learning&&analysisCount&&txPhase==0)finishProposal();}
void GillMixProcessor::lockTrack(Id id,bool b){if(txPhase){status="WAIT FOR CURRENT APPLY";return;}const std::lock_guard<std::mutex>lock(modelMutex);if(auto*p=pick(id,true))p->locked=b;proposalCount=0;}
void GillMixProcessor::refreshTracks(){const auto d=bus.discover();if(d.status!=Status::ok)return;tracks.clear();for(int i=0;i<d.count;++i){TrackView view;view.row=d.rows[static_cast<size_t>(i)];const auto*p=pick(view.row.local.persistent);view.selected=p&&p->selected;view.locked=view.row.local.locked||(p&&p->locked);view.confirmed=(p&&p->manual)||view.row.local.manualRole;view.role=static_cast<Role>(p&&p->manual?p->role:view.row.local.role);if(view.role==Role::automatic){const LearnedTrack*a=nullptr;for(int j=0;j<analysisCount;++j)if(analysis[static_cast<size_t>(j)].runtime==view.row.address.runtime)a=&analysis[static_cast<size_t>(j)].learned;const auto hint=namedHint(view.row.local.name,a);view.role=hint.role;view.confidence=hint.confidence;view.confirmed=hint.high;}else view.confidence=view.confirmed?1.f:.5f;
  for(int j=0;j<proposalCount;++j)if(proposal[static_cast<size_t>(j)].target.runtime==view.row.address.runtime){view.hasProposal=true;view.proposedDb=proposal[static_cast<size_t>(j)].newDb;}tracks.push_back(view);
 }}
void GillMixProcessor::connectSelected(){std::array<Address,maxLinks>addresses{};int n=0;for(const auto&t:tracks)if(t.selected){if(n>=maxLinks){status="MAXIMUM 64 LINKS";return;}addresses[static_cast<size_t>(n++)]=t.row.address;}status=statusText(bus.connect(addresses.data(),n));refreshTracks();}
void GillMixProcessor::startLearn(){if(kind!=GillMixKind::master||txPhase)return;analysisCount=proposalCount=0;learnedTime=0;refreshTracks();for(const auto&t:tracks)if(t.row.owner==bus.runtimeId()&&t.row.reachable&&!t.row.duplicate&&analysisCount<maxLinks){auto&a=analysis[static_cast<size_t>(analysisCount++)];a=Analysis{};a.runtime=t.row.address.runtime;a.baseGain=t.row.local.gain;a.baseMetadata=t.row.local.metadataRevision;a.cursor=bus.telemetryCursor(a.runtime);}
 if(!analysisCount){status="CONNECT LINKS FIRST";return;}learnId=bus.beginLearn();learning=learnId!=0;learnStarted=nowMs();status=learning?"PLAY MAIN + BEAT / LEARNING":"CONNECTION BUSY";
}
void GillMixProcessor::stopLearn(){if(!learning)return;learning=false;bus.stopLearn();finishProposal();}
void GillMixProcessor::finishProposal(){
 refreshTracks();proposalSettings={parameter("changeLimit"),parameter("doubleOffset"),parameter("adlibOffset"),parameter("beatOffset")};proposalCount=0;int mainIndex=-1,mainCount=0,beatIndex=-1;
 for(int i=0;i<analysisCount;++i){const auto&a=analysis[static_cast<size_t>(i)];for(const auto&t:tracks)if(t.row.address.runtime==a.runtime&&t.confirmed){if(t.role==Role::main){mainIndex=i;++mainCount;}if(t.role==Role::beat)beatIndex=i;}}
 if(mainCount!=1){status="CONFIRM ONE MAIN ANCHOR";return;}if(beatIndex<0){status="CONFIRM A BEAT ROLE";return;}
 const auto&main=analysis[static_cast<size_t>(mainIndex)];const auto&beat=analysis[static_cast<size_t>(beatIndex)];const auto&ml=main.learned;const auto&bl=beat.learned;
 const double common=ml.rate&&ml.rate==bl.rate?static_cast<double>(std::min(ml.end,bl.end)-std::max(ml.begin,bl.begin))/ml.rate:0;
 if(!ml.aligned||!bl.aligned||common<8||ml.active<100||bl.active<100){status="NEED 8s ALIGNED MAIN + BEAT";return;}
 const float anchor=ml.activeLevel()+GainValue::decode(main.baseGain);
 for(const auto&t:tracks){if(!t.selected||!t.confirmed||t.locked||!t.row.reachable||t.row.duplicate||t.row.owner!=bus.runtimeId())continue;const Analysis*a=nullptr;for(int i=0;i<analysisCount;++i)if(analysis[static_cast<size_t>(i)].runtime==t.row.address.runtime)a=&analysis[static_cast<size_t>(i)];if(!a||!a->learned.aligned||a->learned.active<25||a->baseGain!=t.row.local.gain||a->baseMetadata!=t.row.local.metadataRevision)continue;
  Change c{};c.target=t.row.address;c.binding=t.row.binding;c.expectedGain=t.row.local.gain;c.expectedMetadata=t.row.local.metadataRevision;c.beforeDb=GainValue::decode(c.expectedGain);c.beforeRole=t.row.local.role;c.beforeManualRole=t.row.local.manualRole;c.newRole=static_cast<uint32_t>(t.role);c.manualRole=t.confirmed;c.limit=parameter("changeLimit");
  float target=anchor;if(t.role==Role::doubleVoice)target+=parameter("doubleOffset");if(t.role==Role::adlib)target+=parameter("adlibOffset");if(t.role==Role::beat)target+=parameter("beatOffset");
  c.newDb=getCurrentProgram()==0||t.role==Role::main?c.beforeDb:correction(c.beforeDb,a->learned.activeLevel()+c.beforeDb,target,c.limit);if(proposalCount<maxLinks)proposal[static_cast<size_t>(proposalCount++)]=c;
 }
 status=proposalCount?"PREVIEW READY / APPLY WHEN READY":"CHECK ROLES / CHANGED LEVELS";refreshTracks();
}
void GillMixProcessor::beginTransaction(const Change*rows,int n,bool isUndo){if(txPhase){status="WAIT FOR CURRENT APPLY";return;}const auto result=bus.prepare(rows,n,transactionId);if(result!=Status::ok){status=statusText(result);return;}std::copy_n(rows,n,transaction.begin());transactionCount=n;txPhase=1;txIsUndo=isUndo;txStarted=nowMs();status="PREPARING";}
void GillMixProcessor::apply(){const std::array<float,4>settings{parameter("changeLimit"),parameter("doubleOffset"),parameter("adlibOffset"),parameter("beatOffset")};if(settings!=proposalSettings){finishProposal();status="UPDATED PREVIEW / PRESS APPLY";return;}if(canApply())beginTransaction(proposal.data(),proposalCount);}
void GillMixProcessor::undo(){if(canUndo())beginTransaction(undoRows.data(),undoCount,true);}
void GillMixProcessor::manualGain(Id runtime,float db){for(const auto&t:tracks)if(t.row.address.runtime==runtime){Change c{};c.target=t.row.address;c.binding=t.row.binding;c.expectedGain=t.row.local.gain;c.expectedMetadata=t.row.local.metadataRevision;c.beforeDb=GainValue::decode(c.expectedGain);c.newDb=db;c.beforeRole=c.newRole=t.row.local.role;c.manualRole=c.beforeManualRole=t.row.local.manualRole;c.limit=30;beginTransaction(&c,1);return;}}
void GillMixProcessor::serviceTransaction(){if(!txPhase)return;const auto d=bus.discover();if(d.status!=Status::ok)return;int ready=0,applied=0,errors=0;std::array<Change,maxLinks>nextUndo{};int nextCount=0;
 for(int i=0;i<transactionCount;++i){const auto&c=transaction[static_cast<size_t>(i)];const Row*row=nullptr;for(int j=0;j<d.count;++j)if(d.rows[static_cast<size_t>(j)].address.runtime==c.target.runtime)row=&d.rows[static_cast<size_t>(j)];if(!row||!row->reachable){++errors;continue;}const auto&a=row->ack;if(a.transaction!=transactionId||a.phase!=(txPhase==1?Phase::prepare:Phase::commit))continue;if(a.status==Status::ready)++ready;else if(a.status==Status::applied){++applied;auto undo=c;undo.expectedGain=a.gain;undo.expectedMetadata=a.metadata;undo.beforeDb=c.newDb;undo.newDb=c.beforeDb;undo.beforeRole=c.newRole;undo.newRole=c.beforeRole;undo.manualRole=c.beforeManualRole;undo.beforeManualRole=c.manualRole;undo.limit=30;nextUndo[static_cast<size_t>(nextCount++)]=undo;}else ++errors;}
 if(txPhase==1&&ready==transactionCount){const auto r=bus.commit(transactionId);if(r==Status::ok){txPhase=2;txStarted=nowMs();status="APPLYING";return;}if(r!=Status::busy){status=statusText(r);txPhase=0;return;}}
 if((txPhase==1&&errors)||(txPhase==2&&applied+errors==transactionCount)||nowMs()-txStarted>3500){if(txPhase==2&&applied){undoRows=nextUndo;undoCount=nextCount;}if(txIsUndo&&applied==transactionCount)undoCount=0;status=txPhase==2&&applied==transactionCount?"APPLIED / REPLAY TO CHECK MASTER":("PARTIAL / "+juce::String(applied)+" OF "+juce::String(transactionCount));txPhase=0;proposalCount=0;refreshTracks();}
}
void GillMixProcessor::service(){
 quality.pollOnMessageThread();if(restoring.load())return;consumeProgram();
 if(restoreSerial.load()!=seenRestore){seenRestore=restoreSerial.load();{const std::lock_guard<std::mutex>lock(modelMutex);picks=pendingPicks;}learning=false;txPhase=0;proposalCount=undoCount=0;cachedAck={};status="RESTORED / CONNECT SELECTED";audio.requestLearn(0);}
 if(lastService&&nowMs()-lastService>10000){bus.disconnect(bus.runtimeId());cachedAck={};}lastService=nowMs();
 std::array<TelemetryFrame,64>frames{};int n=0;while(n<64&&audio.pop(frames[static_cast<size_t>(n)]))++n;const auto poll=bus.service(localSnapshot(),frames.data(),n);
 if(kind==GillMixKind::link){if(poll.connected){const std::lock_guard<std::mutex>lock(modelMutex);local.session=poll.session;local.controller=poll.controller;}audio.requestLearn(poll.connected?poll.learn:0);status=poll.connected?"CONNECTED":statusText(poll.status);if(poll.command.transaction)handleCommand(poll.command);if(gainParameter)gainParameter->publish();return;}
 if(poll.status==Status::ambiguous){learning=false;txPhase=proposalCount=undoCount=0;status="DUPLICATE SESSION / NEW SESSION";refreshTracks();return;}
 if(status=="DUPLICATE SESSION / NEW SESSION")status="READY / CONNECT SELECTED";
 if(learning){for(int i=0;i<analysisCount;++i){auto&a=analysis[static_cast<size_t>(i)];bool lost=false;const int count=bus.readTelemetry(a.runtime,a.cursor,frames.data(),64,lost);if(lost)a.learned.aligned=false;for(int j=0;j<count;++j)if(frames[static_cast<size_t>(j)].learn==learnId)a.learned.add(frames[static_cast<size_t>(j)]);learnedTime=std::max(learnedTime,a.learned.seconds());}if(learnedTime>=19.9||nowMs()-learnStarted>22000)stopLearn();}
 refreshTracks();serviceTransaction();
}
const juce::String GillMixProcessor::getProgramName(int i){return kind==GillMixKind::master?presets[std::clamp(i,0,4)]:"LOCAL LEVEL";}
void GillMixProcessor::setCurrentProgram(int i){if(kind!=GillMixKind::master)return;program.store(std::clamp(i,0,4)|8,std::memory_order_release);if(auto*mm=juce::MessageManager::getInstanceWithoutCreating();mm&&mm->isThisTheMessageThread())consumeProgram();}
void GillMixProcessor::consumeProgram(){auto next=program.load(std::memory_order_acquire);if((next&8)&&program.compare_exchange_strong(next,next&7))applyProgram(next&7);}
void GillMixProcessor::applyProgram(int i){constexpr float offsets[5][4]{{3,-6,-9,-2},{3,-6,-9,-2},{3,-3,-8,-2},{3,-6,-12,-2},{1,-6,-9,-2}};const char*ids[]{"changeLimit","doubleOffset","adlibOffset","beatOffset"};for(int p=0;p<4;++p)setParameter(ids[p],offsets[i][p]);proposalCount=0;}
void GillMixProcessor::getStateInformation(juce::MemoryBlock&out){auto state=apvts.copyState();const auto l=localSnapshot();if(gainParameter)state.getChildWithProperty("id","trackLevel").setProperty("value",GainValue::decode(l.gain),nullptr);state.setProperty("schema",1,nullptr);state.setProperty("uuid",juce::String(idText(l.persistent)),nullptr);state.setProperty("session",juce::String(idText(l.session)),nullptr);state.setProperty("controller",juce::String(idText(l.controller)),nullptr);state.setProperty("name",juce::String::fromUTF8(l.name),nullptr);state.setProperty("role",static_cast<int>(l.role),nullptr);state.setProperty("manual",static_cast<bool>(l.manualRole),nullptr);state.setProperty("locked",static_cast<bool>(l.locked),nullptr);const auto savedProgram=program.load();state.setProperty("program",savedProgram&7,nullptr);if(savedProgram&8){constexpr float offsets[5][4]{{3,-6,-9,-2},{3,-6,-9,-2},{3,-3,-8,-2},{3,-6,-12,-2},{1,-6,-9,-2}};const char*ids[]{"changeLimit","doubleOffset","adlibOffset","beatOffset"};for(int p=0;p<4;++p)state.getChildWithProperty("id",ids[p]).setProperty("value",offsets[savedProgram&7][p],nullptr);}std::array<Pick,64>savedPicks;{const std::lock_guard<std::mutex>lock(modelMutex);savedPicks=restoreSerial.load()!=seenRestore?pendingPicks:picks;}if(kind==GillMixKind::master)for(const auto&p:savedPicks)if(p.id){juce::ValueTree row("PICK");row.setProperty("id",juce::String(idText(p.id)),nullptr);row.setProperty("role",static_cast<int>(p.role),nullptr);row.setProperty("manual",p.manual,nullptr);row.setProperty("selected",p.selected,nullptr);row.setProperty("locked",p.locked,nullptr);state.addChild(row,-1,nullptr);}if(auto xml=state.createXml())copyXmlToBinary(*xml,out);}
void GillMixProcessor::setStateInformation(const void*data,int bytes){if(!data||bytes<1||bytes>131072)return;const auto xml=getXmlFromBinary(data,bytes);if(!xml||!xml->hasTagName(apvts.state.getType()))return;auto state=juce::ValueTree::fromXml(*xml);if(static_cast<int>(state["schema"])!=1)return;const auto uuid=parseId(state["uuid"].toString().toStdString()),session=parseId(state["session"].toString().toStdString());if(!uuid||!session)return;const int role=state["role"],pg=state["program"];if(role<0||role>4||pg<0||pg>4||state["name"].toString().getNumBytesAsUTF8()>95)return;std::set<juce::String>seen;std::array<Pick,64>nextPicks{};int count=0;for(const auto&child:state){if(child.hasType("PICK")){if(kind!=GillMixKind::master||count>=64)return;auto&p=nextPicks[static_cast<size_t>(count++)];p.id=parseId(child["id"].toString().toStdString());p.role=static_cast<uint32_t>(static_cast<int>(child["role"]));p.manual=child["manual"];p.selected=child["selected"];p.locked=child["locked"];if(!p.id||p.role>4)return;for(int j=0;j<count-1;++j)if(nextPicks[static_cast<size_t>(j)].id==p.id)return;continue;}if(!child.hasType("PARAM"))return;const auto id=child["id"].toString();auto*p=apvts.getParameter(id);if(!p||!seen.insert(id).second)return;const auto text=child["value"].toString();char*end=nullptr;const double value=std::strtod(text.toRawUTF8(),&end);const auto range=p->getNormalisableRange();if(text.isEmpty()||!end||*end||!std::isfinite(value)||value<range.start-.001||value>range.end+.001)return;if((id=="bypass"||id=="gillQuality")&&value!=std::floor(value))return;}
 if(seen.size()!=static_cast<size_t>(getParameters().size()))return;
 restoring.store(true);{const std::lock_guard<std::mutex>lock(modelMutex);local.persistent=uuid;local.session=session;local.controller=parseId(state["controller"].toString().toStdString());++local.epoch;bus.invalidate(local.epoch);++local.metadataRevision;local.role=static_cast<uint32_t>(role);local.manualRole=static_cast<bool>(state["manual"]);local.locked=static_cast<bool>(state["locked"]);nameCopy(local.name,state["name"].toString());while(state.getChildWithName("PICK").isValid())state.removeChild(state.getChildWithName("PICK"),nullptr);apvts.replaceState(state);
 // APVTS may skip a write when its snapped cache equals the state, although
 // the host parameter still contains a fractional Boolean/choice value.
 for(const auto&child:state)if(child.hasType("PARAM"))if(auto*p=apvts.getParameter(child["id"].toString()))p->setValueNotifyingHost(p->convertTo0to1(static_cast<float>(child["value"])));
 pendingPicks=nextPicks;program.store(pg);restoreSerial.fetch_add(1);}restoring.store(false);
}
juce::AudioProcessorEditor*GillMixProcessor::createEditor(){return new GillMixEditor(*this);}
