#include "PluginEditor.h"
#include "BinaryData.h"
using namespace gill::mix07;
namespace {
class MixLook final:public juce::LookAndFeel_V4 {
public:
 MixLook(){const juce::Colour ink(0xff34281d),cream(0xffeee4d0),accent(0xff849783);setColour(juce::Slider::textBoxTextColourId,ink);setColour(juce::Slider::textBoxBackgroundColourId,cream);setColour(juce::Slider::textBoxOutlineColourId,accent.withAlpha(.5f));setColour(juce::ComboBox::backgroundColourId,cream);setColour(juce::ComboBox::textColourId,ink);setColour(juce::ComboBox::arrowColourId,ink);setColour(juce::ComboBox::outlineColourId,accent);setColour(juce::TextEditor::backgroundColourId,cream);setColour(juce::TextEditor::textColourId,ink);setColour(juce::TextEditor::outlineColourId,accent);setColour(juce::PopupMenu::backgroundColourId,cream);setColour(juce::PopupMenu::textColourId,ink);setColour(juce::PopupMenu::highlightedBackgroundColourId,accent);}
 juce::Font getTextButtonFont(juce::TextButton&,int)override{return juce::Font(juce::FontOptions(11,juce::Font::bold));}
 juce::Font getComboBoxFont(juce::ComboBox&)override{return juce::Font(juce::FontOptions(11));}
 void drawButtonBackground(juce::Graphics&g,juce::Button&b,const juce::Colour&,bool over,bool down)override{const juce::Colour face=b.getButtonText().startsWith("LEARN")||b.getButtonText().startsWith("STOP")?juce::Colour(0xffc4a376):juce::Colour(0xffeee4d0);gill::material::panel(g,b.getLocalBounds().toFloat().reduced(1),b.isEnabled()?face:face.darker(.45f),6,down);if(over&&b.isEnabled()){g.setColour(juce::Colours::white.withAlpha(.1f));g.fillRoundedRectangle(b.getLocalBounds().toFloat().reduced(1),6);}b.setColour(juce::TextButton::textColourOffId,juce::Colour(0xff34281d));}
 void drawLinearSlider(juce::Graphics&g,int x,int y,int w,int h,float position,float,float,juce::Slider::SliderStyle,juce::Slider&)override{const float cy=y+h*.5f;gill::material::panel(g,{float(x),cy-4,float(w),8},juce::Colour(0xff29251f),4,true);g.setColour(juce::Colour(0xff91a08b));g.fillRoundedRectangle(float(x),cy-2,std::max(0.f,position-x),4,2);gill::material::disc(g,juce::Rectangle<float>(15,15).withCentre({position,cy}));}
};
}

GillMixEditor::GillMixEditor(GillMixProcessor&p):AudioProcessorEditor(p),processor(p),quality(p.apvts,p){
 look=std::make_unique<MixLook>();setLookAndFeel(look.get());wood=juce::ImageCache::getFromMemory(BinaryData::core_reference_png,BinaryData::core_reference_pngSize);
 setSize(p.kind==GillMixKind::master?760:360,p.kind==GillMixKind::master?480:210);setResizable(false,false);
 addAndMakeVisible(quality);addAndMakeVisible(status);addAndMakeVisible(inMeter);addAndMakeVisible(outMeter);
 for(auto*l:{&status,&inMeter,&outMeter,&title,&limitTitle})l->setColour(juce::Label::textColourId,juce::Colour(0xfff2e5cd));
 status.setFont(juce::FontOptions(12));status.setJustificationType(juce::Justification::centredLeft);
 if(p.kind==GillMixKind::master){
  addAndMakeVisible(name);name.setText(juce::String::fromUTF8(p.localSnapshot().name));name.setTooltip("Session name. Connections are explicit and scoped to this controller.");name.onReturnKey=[this]{processor.setLocalName(name.getText());name.giveAwayKeyboardFocus();};name.onFocusLost=[this]{processor.setLocalName(name.getText());};
  addAndMakeVisible(identity);identity.setButtonText("NEW SESSION");identity.setTooltip("Create a new session identity and remove this controller's previous remote authority. Local LINK levels stay unchanged.");identity.onClick=[this]{processor.newIdentity();processor.service();};
  for(auto*b:{&connect,&learn,&apply,&undo}){addAndMakeVisible(b);b->setColour(juce::TextButton::buttonColourId,juce::Colour(0xffd4bea0));b->setColour(juce::TextButton::textColourOffId,juce::Colour(0xff281b11));}
  learn.setTitle("LEARN / STOP");connect.onClick=[this]{processor.connectSelected();};learn.onClick=[this]{if(processor.isLearning())processor.stopLearn();else processor.startLearn();};apply.onClick=[this]{processor.apply();};undo.onClick=[this]{processor.undo();};
  addAndMakeVisible(list);list.setRowHeight(33);list.setColour(juce::ListBox::backgroundColourId,juce::Colour(0xff241d17));list.setTooltip("Keep selected FL track faders at 0 dB. Put LINK last on each source; adjust levels in LINK. Tick a link, CONNECT SELECTED, then click its row for role, lock or level. Do not also link a bus carrying the same source.");
  addAndMakeVisible(preset);for(int i=0;i<5;++i)preset.addItem(p.getProgramName(i),i+1);preset.setSelectedId(p.getCurrentProgram()+1,juce::dontSendNotification);preset.onChange=[this]{processor.setCurrentProgram(preset.getSelectedId()-1);};
  addAndMakeVisible(limit);limit.setSliderStyle(juce::Slider::LinearHorizontal);limit.setTextBoxStyle(juce::Slider::TextBoxRight,false,60,22);limit.setTextValueSuffix(" dB");limitAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.apvts,"changeLimit",limit);addAndMakeVisible(limitTitle);limitTitle.setText("CHANGE LIMIT",juce::dontSendNotification);
  const char* ids[]{"doubleOffset","adlibOffset","beatOffset"};const char* labels[]{"DOUBLE","ADLIB","BEAT"};
  for(size_t i=0;i<3;++i){addAndMakeVisible(offsets[i]);addAndMakeVisible(offsetLabels[i]);offsets[i].setSliderStyle(juce::Slider::LinearHorizontal);offsets[i].setTextBoxStyle(juce::Slider::TextBoxRight,false,58,21);offsets[i].setTextValueSuffix(" dB");offsetLabels[i].setText(labels[i],juce::dontSendNotification);offsetLabels[i].setFont(juce::FontOptions(11));offsetLabels[i].setColour(juce::Label::textColourId,juce::Colour(0xfff2e5cd));offsetAttachments[i]=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.apvts,ids[i],offsets[i]);}

 }else{
  addAndMakeVisible(name);name.setText(juce::String::fromUTF8(p.localSnapshot().name));name.onReturnKey=[this]{processor.setLocalName(name.getText());name.giveAwayKeyboardFocus();};name.onFocusLost=[this]{processor.setLocalName(name.getText());};name.setTooltip("Track name is a hint, never a session identity.");
  addAndMakeVisible(role);for(int i=0;i<=4;++i)role.addItem(roleName(static_cast<Role>(i)),i+1);role.onChange=[this]{if(!updating)processor.setLocalRole(static_cast<Role>(role.getSelectedId()-1));};
  addAndMakeVisible(lock);lock.onClick=[this]{if(!updating)processor.setLocalLock(lock.getToggleState());};lock.setColour(juce::ToggleButton::textColourId,juce::Colour(0xfff2e5cd));
  addAndMakeVisible(gain);gain.setSliderStyle(juce::Slider::LinearHorizontal);gain.setTextBoxStyle(juce::Slider::TextBoxRight,false,78,25);gainAttachment=std::make_unique<juce::AudioProcessorValueTreeState::SliderAttachment>(p.apvts,"trackLevel",gain);
  addAndMakeVisible(identity);addAndMakeVisible(disconnect);identity.onClick=[this]{processor.newIdentity();};disconnect.onClick=[this]{processor.disconnect();};identity.setTooltip("Give this explicitly selected copy a new persistent ID. Existing binding is removed.");
 }
 timerCallback();startTimer(100);
}
GillMixEditor::~GillMixEditor(){stopTimer();list.setModel(nullptr);setLookAndFeel(nullptr);}
void GillMixEditor::paint(juce::Graphics&g){const auto r=getLocalBounds().toFloat();g.fillAll(juce::Colour(0xff291f17));if(wood.isValid()){g.drawImage(wood,0,0,getWidth(),getHeight(),950,285,170,805);g.setColour(juce::Colour(0xff382416).withAlpha(.58f));g.fillAll();g.drawImage(wood,21,17,40,28,224,146,174,122);}g.setColour(juce::Colour(0xffecdfc5).withAlpha(.65f));g.drawRoundedRectangle(r.reduced(3),17,2);g.setColour(juce::Colours::black.withAlpha(.45f));g.drawRoundedRectangle(r.reduced(7),13,1);g.setColour(juce::Colour(0xfff4e8d1));g.setFont(juce::FontOptions(processor.kind==GillMixKind::master?24.f:19.f,juce::Font::bold));g.drawText(processor.getName(),73,13,getWidth()-210,32,juce::Justification::centredLeft);
 if(processor.kind==GillMixKind::master){g.setFont(juce::FontOptions(11));g.setColour(juce::Colour(0xffd4bda1));g.drawText("SELECT / TRACK",22,132,230,18,juce::Justification::centredLeft);g.drawText("ROLE",274,132,110,18,juce::Justification::centredLeft);g.drawText("LEVEL",413,132,85,18,juce::Justification::centredLeft);g.drawText("PROPOSAL",515,132,210,18,juce::Justification::centredLeft);g.drawText("TRACK FADERS 0 DB / LEVELS VIA GILLLINK",22,450,470,18,juce::Justification::centredLeft);}
}
void GillMixEditor::resized(){quality.setBounds(getWidth()-130,18,110,26);if(processor.kind==GillMixKind::master){name.setBounds(278,19,198,26);identity.setBounds(488,19,123,26);preset.setBounds(22,66,211,28);limitTitle.setBounds(255,64,110,28);limit.setBounds(370,66,185,27);connect.setBounds(567,64,171,31);list.setBounds(22,154,716,264);for(int i=0;i<3;++i){offsetLabels[static_cast<size_t>(i)].setBounds(22+i*240,100,59,24);offsets[static_cast<size_t>(i)].setBounds(81+i*240,101,172,22);}status.setBounds(22,426,410,22);learn.setBounds(459,438,86,28);apply.setBounds(555,438,86,28);undo.setBounds(651,438,86,28);inMeter.setBounds(572,132,80,18);outMeter.setBounds(657,132,80,18);}else{name.setBounds(22,60,174,26);role.setBounds(206,60,130,26);gain.setBounds(22,98,245,28);lock.setBounds(275,101,62,24);status.setBounds(22,137,255,20);identity.setBounds(20,169,72,23);disconnect.setBounds(103,169,108,23);inMeter.setBounds(218,161,119,19);outMeter.setBounds(218,181,119,19);}}
int GillMixEditor::getNumRows(){return static_cast<int>(processor.tracks.size());}
void GillMixEditor::paintListBoxItem(int row,juce::Graphics&g,int width,int height,bool selected){if(row<0||row>=getNumRows())return;const auto&t=processor.tracks[static_cast<size_t>(row)];g.fillAll(juce::Colour(selected?0xff4c3d2d:row%2?0xff30271f:0xff28211b));g.setColour(juce::Colour(t.row.reachable?0xffe6d6bb:0xff927d65));g.drawRoundedRectangle(8,11,14,14,3,1);if(t.selected){g.fillRoundedRectangle(11,14,8,8,2);}g.setFont(juce::FontOptions(13));g.drawText(juce::String::fromUTF8(t.row.local.name),33,1,210,height-2,juce::Justification::centredLeft);g.setFont(juce::FontOptions(12));const auto role=juce::String(roleName(t.role))+(t.confirmed?(t.confidence<.99f?" / HIGH":""):" / CHECK");g.drawText(t.row.duplicate?"DUPLICATE ID":role,252,1,120,height-2,juce::Justification::centredLeft);g.drawText(juce::String(GainValue::decode(t.row.local.gain),1)+" dB",391,1,93,height-2,juce::Justification::centredLeft);g.drawText(t.hasProposal?juce::String(t.proposedDb,1)+" dB":t.locked?"LOCKED":t.row.owner==processor.bus.runtimeId()?"CONNECTED":"AVAILABLE",493,1,width-500,height-2,juce::Justification::centredLeft);}
void GillMixEditor::listBoxItemClicked(int row,const juce::MouseEvent&e){if(row<0||row>=getNumRows())return;const auto&t=processor.tracks[static_cast<size_t>(row)];if(e.x<28){processor.chooseTrack(t.row.local.persistent,!t.selected);processor.service();list.repaint();}else editTrack(row);}
void GillMixEditor::editTrack(int row){const auto t=processor.tracks[static_cast<size_t>(row)];juce::PopupMenu menu;for(int i=0;i<=4;++i)menu.addItem(10+i,roleName(static_cast<Role>(i)),true,t.role==static_cast<Role>(i));menu.addSeparator();menu.addItem(30,t.locked?"UNLOCK PROPOSAL":"LOCK PROPOSAL");menu.addItem(40,"LEVEL -1 dB",t.row.owner==processor.bus.runtimeId());menu.addItem(41,"LEVEL +1 dB",t.row.owner==processor.bus.runtimeId());menu.addItem(42,"DISCONNECT",t.row.owner==processor.bus.runtimeId());juce::Component::SafePointer<GillMixEditor>safe(this);menu.showMenuAsync(juce::PopupMenu::Options(),[safe,t](int result){if(!safe)return;if(result>=10&&result<=14)safe->processor.chooseRole(t.row.local.persistent,static_cast<Role>(result-10));if(result==30)safe->processor.lockTrack(t.row.local.persistent,!t.locked);if(result==40||result==41)safe->processor.manualGain(t.row.address.runtime,std::clamp(GainValue::decode(t.row.local.gain)+(result==40?-1.f:1.f),-24.f,6.f));if(result==42)safe->processor.bus.disconnect(t.row.address.runtime);safe->processor.service();safe->list.repaint();});}
void GillMixEditor::timerCallback(){updating=true;if(!name.hasKeyboardFocus(true))name.setText(juce::String::fromUTF8(processor.localSnapshot().name),false);if(processor.kind==GillMixKind::master)preset.setSelectedId(processor.getCurrentProgram()+1,juce::dontSendNotification);status.setText(processor.status,juce::dontSendNotification);const auto db=[](float x){return juce::String(x>1e-6f?20*std::log10(x):-120.f,1);};inMeter.setText("IN "+db(processor.meterIn()),juce::dontSendNotification);outMeter.setText("OUT "+db(processor.meterOut()),juce::dontSendNotification);if(processor.kind==GillMixKind::master){list.updateContent();list.repaint();apply.setEnabled(processor.canApply());undo.setEnabled(processor.canUndo());learn.setButtonText(processor.isLearning()?"STOP "+juce::String(processor.learnedSeconds(),0)+"s":"LEARN");}else{const auto s=processor.localSnapshot();role.setSelectedId(static_cast<int>(s.role)+1,juce::dontSendNotification);lock.setToggleState(s.locked,juce::dontSendNotification);}updating=false;}
