#include "../Source/FormDSP.h"
#include <cstdio>
#include "../Source/AlignDSP.h"
#include <cstdio>
#include <random>
#include <chrono>
#include <cstdlib>
#include <new>
#include <limits>
#include <fstream>
static bool allocationWatch=false;static size_t allocations=0;
void*operator new(size_t n){if(allocationWatch)++allocations;if(void*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}
void*operator new[](size_t n){return::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}void operator delete(void*p,size_t)noexcept{std::free(p);}void operator delete[](void*p,size_t)noexcept{std::free(p);}
using namespace gillnext;constexpr double pi=3.14159265358979323846;
int checks=0,failures=0;void check(bool ok,const char*s,double a=0,double b=0){++checks;if(!ok)++failures;std::printf("%s %s %.9g %.9g\n",ok?"PASS":"FAIL",s,a,b);}
std::vector<float>vowel(double fs,double hz,double seconds){std::vector<float>x(size_t(fs*seconds));for(size_t i=0;i<x.size();++i){double v=0;for(int h=1;h*hz<fs*.42&&h<100;++h){const double f=h*hz,envelope=.15+3*std::exp(-std::pow((f-500)/140,2))+2*std::exp(-std::pow((f-1500)/230,2))+.8*std::exp(-std::pow((f-2800)/400,2));v+=envelope/std::sqrt(double(h))*std::sin(2*pi*f*i/fs);}x[i]=float(v*.07);}return x;}
struct Render{std::vector<float>y;int latency=0;};
Render form(const std::vector<float>&x,double fs,FormParameters p,int block=127){FormDSP dsp;dsp.prepare(fs,block,1);dsp.setParameters(p);Render r{x,dsp.latencySamples()};for(int i=0;i<int(x.size());i+=block){float*data[]{r.y.data()+i};allocationWatch=true;dsp.process(data,1,std::min(block,int(x.size())-i));allocationWatch=false;}return r;}
double pitch(const std::vector<float>&x,double fs,double expected){const int start=int(x.size()-fs*.3),len=int(fs*.2),lo=int(fs/expected*.85),hi=int(fs/expected*1.15);std::vector<double>d(hi+2);int best=lo;for(int lag=lo;lag<=hi;++lag){for(int n=0;n<len;++n){const double v=x[start+n]-x[start+n+lag];d[lag]+=v*v;}if(d[lag]<d[best])best=lag;}if(best==lo||best==hi)return 0;return fs/(best+.5*(d[best-1]-d[best+1])/(d[best-1]-2*d[best]+d[best+1]));}
double amplitude(const std::vector<float>&x,double fs,double hz){const int len=int(fs*.5),start=int(x.size())-len;std::complex<double>s{};for(int n=0;n<len;++n)s+=double(x[start+n])*std::polar(1.,-2*pi*hz*n/fs);return 2*std::abs(s)/len;}
double formantPeak(const std::vector<float>&x,double fs,double f0,double lo,double hi){double best=0,hz=0;for(int h=1;h*f0<hi;++h){if(h*f0<lo)continue;const double a=amplitude(x,fs,h*f0)*std::sqrt(double(h));if(a>best){best=a;hz=h*f0;}}return hz;}
double error(const std::vector<float>&a,const std::vector<float>&b,int start=0){double e=0;for(size_t n=start;n<std::min(a.size(),b.size());++n)e=std::max(e,std::abs(double(a[n]-b[n])));return e;}
std::vector<float>phrase(double fs,const std::vector<double>&onsets,double frequency=150){const int length=int(fs*3);std::vector<float>x(length);for(size_t word=0;word<onsets.size();++word){const double start=onsets[word];for(int n=std::max(0,int(start*fs));n<length;++n){const double t=n/fs-start;if(t>.22)break;const double envelope=(1-std::exp(-t/.007))*std::exp(-t/.065)*(1-.3*std::cos(pi*std::min(1.,t/.22)));double v=std::sin(2*pi*frequency*n/fs)+.5*std::sin(4*pi*frequency*n/fs)+.2*std::sin(6*pi*frequency*n/fs);x[n]+=float(.2*envelope*v*(.7+.1*(word%3)));}}return x;}
double envelopeError(const std::vector<float>&a,const std::vector<float>&b,int hop){double e=0;for(int n=0;n+hop<int(a.size());n+=hop){double x=0,y=0;for(int j=0;j<hop;++j){x+=a[n+j]*a[n+j];y+=b[n+j]*b[n+j];}e+=std::pow(std::sqrt(x/hop)-std::sqrt(y/hop),2);}return e;}
int main(){const auto start=std::chrono::steady_clock::now();
 for(double fs:{44100.,48000.,96000.}){const auto x=vowel(fs,120,1.5);for(float semitones:{-12.f,-7.f,0.f,7.f,12.f}){FormParameters p;p.pitchSemitones=semitones;p.preserveTransients=false;auto r=form(x,fs,p);const double expected=120*std::exp2(semitones/12),hz=pitch(r.y,fs,expected),cents=hz>0?1200*std::log2(hz/expected):999;check(std::abs(cents)<8,"FORM actual pitch shift follows semitone ratio",cents,semitones);bool finite=true;for(float s:r.y)finite=finite&&std::isfinite(s);check(finite,"FORM output finite");if(semitones==0){double e=0;for(int n=r.latency;n<int(x.size());++n)e=std::max(e,std::abs(double(r.y[n]-x[n-r.latency])));check(e==0,"FORM neutral is exact delayed original",e,r.latency);}}
 FormParameters off;off.pitchSemitones=7;off.formantSemitones=-4;off.mix=0;auto dry=form(x,fs,off);double e=0;for(int n=dry.latency;n<int(x.size());++n)e=std::max(e,std::abs(double(dry.y[n]-x[n-dry.latency])));check(e==0,"FORM mix0 is exact aligned dry",e,dry.latency);
 }
 {const double fs=48000;const auto x=vowel(fs,120,2);for(float semitones:{-6.f,6.f}){FormParameters p;p.formantSemitones=semitones;p.preserveTransients=false;const auto y=form(x,fs,p);const double hz=pitch(y.y,fs,120);check(std::abs(1200*std::log2(hz/120))<5,"FORM formant-only shift preserves fundamental",hz);const double f=formantPeak(y.y,fs,120,240,semitones<0?650:1000);check(semitones<0?f<480:f>600,"FORM first measured resonance moves independently of pitch",f,semitones);}
 FormParameters a;a.pitchSemitones=7;a.formantSemitones=-6;a.link=true;a.preserveTransients=false;FormParameters b=a;b.link=false;b.formantSemitones=7;const auto ya=form(x,fs,a),yb=form(x,fs,b);check(ya.y==yb.y,"FORM LINK follows pitch for actual spectral envelope");
 FormParameters p;p.pitchSemitones=5;p.formantSemitones=-3;p.preserveTransients=false;const auto one=form(x,fs,p,1);for(int block:{127,4096}){const auto many=form(x,fs,p,block);check(one.y==many.y,"FORM sample exact across host block sizes");}
 p.mix=50;const auto half=form(x,fs,p);double e=0;for(int n=0;n<int(x.size());++n){const double d=n>=half.latency?x[n-half.latency]:0;e=std::max(e,std::abs(half.y[n]-(d+.5*(one.y[n]-d))));}check(e<1e-7,"FORM dry/wet matches independent latency-aligned reference",e);
 }
 check(allocations==0,"FORM processing performs no heap allocations",double(allocations));
 {constexpr double fs=48000;const std::vector<double>times{.20,.61,1.03,1.52,2.04,2.55};const auto guide=phrase(fs,times);for(double offset:{-.12,.08,.20}){auto moved=times;for(auto&t:moved)t+=offset;const auto dub=phrase(fs,moved);auto aligned=AlignDSP::align({guide},{dub},fs,{100,250});check(aligned.success,"ALIGN finds isolated vocal phrase shift",aligned.confidence);const double before=envelopeError(guide,dub,240),after=aligned.success?envelopeError(guide,aligned.audio[0],240):999;check(after<before*.25,"ALIGN improves actual output onset-envelope alignment",after,before);bool bounded=true,ordered=true;for(size_t i=0;i<aligned.mapping.size();++i){const auto&p=aligned.mapping[i];bounded=bounded&&std::abs(p.sourceSeconds-p.outputSeconds)<=.250001;if(i)ordered=ordered&&p.sourceSeconds>aligned.mapping[i-1].sourceSeconds;}check(bounded&&ordered,"ALIGN warp is monotone and within maximum shift");}
 auto shifted=times;for(size_t i=0;i<shifted.size();++i)shifted[i]+=(i%2?.06:-.04);const auto dub=phrase(fs,shifted);const auto aligned=AlignDSP::align({guide},{dub},fs,{100,120});const double before=envelopeError(guide,dub,240),after=aligned.success?envelopeError(guide,aligned.audio[0],240):999;std::printf("ALIGN local confidence %.5f status %s\n",aligned.confidence,aligned.message.c_str());check(aligned.success&&after<before*.6,"ALIGN local timing variation improves",after,before);
 const auto off=AlignDSP::align({guide},{dub},fs,{0,120});check(off.success&&off.audio[0]==dub,"ALIGN tightness0 exactly preserves the double");const auto zero=AlignDSP::align({guide},{dub},fs,{100,0});check(zero.success&&zero.audio[0]==dub,"ALIGN maxShift0 exactly preserves the double");
 auto right=dub;for(auto&v:right)v=-v;const auto stereo=AlignDSP::align({guide},{dub,right},fs,{100,120});double anti=0;if(stereo.success)for(size_t i=0;i<dub.size();++i)anti=std::max(anti,std::abs(double(stereo.audio[0][i]+stereo.audio[1][i])));check(stereo.success&&anti==0,"ALIGN one warp preserves antiphase stereo",anti);
 std::vector<float>silence(48000);const auto empty=AlignDSP::align({silence},{silence},fs,{100,120});check(!empty.success&&empty.audio[0]==silence,"ALIGN silence is retained without false success");check(!AlignDSP::align({}, {dub},fs,{}).success,"ALIGN rejects missing guide");
 }
 std::printf("RESULT %d checks %d failures elapsed %.3fs\n",checks,failures,std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count());return failures?1:0;}
