#define main FormAlignOriginalMain
#include "FormAlignTests.cpp"
#undef main
double crossingPitch(const std::vector<float>&x,double fs){std::vector<double>periods;double previous=-1;for(size_t n=1;n<x.size();++n)if(x[n-1]<=0&&x[n]>0){const double now=n-1+(-x[n-1])/(x[n]-x[n-1]);if(previous>=0){const double period=now-previous;if(period>fs/190&&period<fs/110)periods.push_back(period);}previous=now;}if(periods.size()<10)return 0;std::sort(periods.begin(),periods.end());return fs/periods[periods.size()/2];}
int main(){
 for(double hz:{75.,180.,330.})for(float shift:{-12.f,7.f,12.f}){const auto x=vowel(48000,hz,1.5);FormParameters p;p.pitchSemitones=shift;p.preserveTransients=false;const auto y=form(x,48000,p);const double target=hz*std::exp2(shift/12),actual=pitch(y.y,48000,target);const double cents=actual>0?1200*std::log2(actual/target):999;check(std::abs(cents)<8,"FORM low/mid/high voice pitch remains accurate",cents,hz);}
 for(double fs:{8000.,22050.,44100.,48000.,96000.,192000.}){
  for(int channels:{1,2}){FormDSP d;d.prepare(fs,257,channels);FormParameters p;p.pitchSemitones=7;p.formantSemitones=-6;p.preserveTransients=false;d.setParameters(p);const int length=int(fs*.4);std::vector<float>a(length),b(length);std::mt19937 rng(674);std::uniform_real_distribution<float>random(-.1f,.1f);for(int n=0;n<length;++n){a[n]=random(rng);b[n]=-a[n];}a[100]=std::numeric_limits<float>::infinity();b[100]=std::numeric_limits<float>::quiet_NaN();
   for(int n=0;n<length;n+=127){p.pitchSemitones=float(((n/127)%25)-12);p.formantSemitones=float(12-((n/127)%25));p.mix=float((n/127)%101);p.link=(n/127)%7==0;d.setParameters(p);float*data[]{a.data()+n,b.data()+n};allocationWatch=true;d.process(data,channels,std::min(127,length-n));allocationWatch=false;}
   bool finite=true;double peak=0;for(int n=0;n<length;++n){finite=finite&&std::isfinite(a[n])&&(channels==1||std::isfinite(b[n]));peak=std::max(peak,std::abs(double(a[n])));}check(finite&&peak<=32,"FORM automating all controls is finite and bounded",peak,fs);
   d.reset();std::fill(a.begin(),a.end(),0.f);std::fill(b.begin(),b.end(),0.f);for(int n=0;n<length;n+=127){float*data[]{a.data()+n,b.data()+n};allocationWatch=true;d.process(data,channels,std::min(127,length-n));allocationWatch=false;}bool silent=true;for(int n=0;n<length;++n)silent=silent&&a[n]==0&&(channels==1||b[n]==0);check(silent,"FORM reset clears actual audio history");
  }
 }
 {const int length=144000;const auto x=vowel(48000,120,3);FormDSP d;d.prepare(48000,127,2);FormParameters p;p.pitchSemitones=7;p.formantSemitones=-3;p.preserveTransients=false;d.setParameters(p);auto a=x,b=x;for(auto&v:b)v=-v;for(int n=0;n<length;n+=127){float*data[]{a.data()+n,b.data()+n};d.process(data,2,std::min(127,length-n));}double e=0;for(int n=0;n<length;++n)e=std::max(e,std::abs(double(a[n]+b[n])));check(e<2e-5,"FORM linked stereo retains antiphase relationship",e);}
 {const double fs=48000;std::vector<float>x(72000);x[4800]=.5f;FormParameters p;p.pitchSemitones=7;p.preserveTransients=false;const auto no=form(x,fs,p);p.preserveTransients=true;const auto yes=form(x,fs,p);const int at=4800+yes.latency;const double off=std::abs(no.y[at]-.5),on=std::abs(yes.y[at]-.5);check(on<off,"FORM Transient Preservation retains aligned attack peak",on,off);}
 check(allocations==0,"FORM edge-case process calls allocate nothing",double(allocations));
 for(double fs:{22050.,44100.,48000.,96000.}){const std::vector<double>times{.20,.61,1.03,1.52,2.04,2.55};const auto guide=phrase(fs,times,150);auto timing=times;for(size_t n=0;n<timing.size();++n)timing[n]+=(n%2?.06:-.04);const auto dub=phrase(fs,timing,163);const auto a=AlignDSP::align({guide},{dub},fs,{100,120});check(a.success,"ALIGN independently sung pitch/timing variation accepted",a.confidence,fs);if(a.success){const double hz=crossingPitch(a.audio[0],fs);check(std::abs(1200*std::log2(hz/163))<8,"ALIGN WSOLA preserves double pitch while warping time",hz,fs);}
 const auto half=AlignDSP::align({guide},{dub},fs,{50,120});double halfShift=0,fullShift=0;if(a.success&&half.success){for(auto&p:a.mapping)fullShift=std::max(fullShift,std::abs(p.sourceSeconds-p.outputSeconds));for(auto&p:half.mapping)halfShift=std::max(halfShift,std::abs(p.sourceSeconds-p.outputSeconds));}check(a.success&&half.success&&halfShift<fullShift,"ALIGN Tightness reduces the applied timing movement",halfShift,fullShift);
 }
 {std::vector<float>silence(48000),tone(48000);for(int n=0;n<48000;++n)tone[n]=float(.1*std::sin(2*pi*150*n/48000));const auto r=AlignDSP::align({tone},{tone},48000,{});check(!r.success&&r.audio[0]==tone,"ALIGN steady tone is not misrepresented as a timing match");check(!AlignDSP::align({silence},{silence},std::numeric_limits<double>::quiet_NaN(),{}).success,"ALIGN rejects nonfinite sample rate");check(!AlignDSP::align({silence},{silence,tone,std::vector<float>(48000)},48000,{}).success,"ALIGN rejects unsupported channel layout");}
 std::printf("RESULT %d checks %d failures\n",checks,failures);return failures?1:0;
}
