#include "../../GILLCommon/QualityTests.h"
#include "../Source/PluginProcessor.h"
#include <cstdio>
#include <fstream>
#include <set>
#include <random>
#include <new>
#include <cstdlib>
static thread_local bool watch=false;static std::atomic<int>allocations{0};static int checks=0,failures=0;static juce::String product;
void*operator new(size_t n){if(watch)++allocations;if(auto*p=std::malloc(n?n:1))return p;throw std::bad_alloc();}void*operator new[](size_t n){return ::operator new(n);}void operator delete(void*p)noexcept{std::free(p);}void operator delete[](void*p)noexcept{std::free(p);}void operator delete(void*p,size_t)noexcept{std::free(p);}void operator delete[](void*p,size_t)noexcept{std::free(p);}
void check(bool ok,const juce::String&text,double x=0){++checks;if(!ok)++failures;std::printf("%s %s: %s %.9g\n",ok?"PASS":"FAIL",product.toRawUTF8(),text.toRawUTF8(),x);}
void tick(){juce::Thread::sleep(45);juce::Timer::callPendingTimersSynchronously();}
float input(int i,double fs,int c=0){return float(.14*std::sin(2*juce::MathConstants<double>::pi*(c?331.7:219.2)*i/fs)+.02*std::sin(2*juce::MathConstants<double>::pi*1531*i/fs));}
bool setup(GillNextProcessor&p,double fs,int block,int channels=2,bool side=false){auto l=p.getBusesLayout();l.inputBuses.set(0,channels==2?juce::AudioChannelSet::stereo():juce::AudioChannelSet::mono());l.outputBuses.set(0,l.inputBuses[0]);if(l.inputBuses.size()>1)l.inputBuses.set(1,side?juce::AudioChannelSet::stereo():juce::AudioChannelSet::disabled());const bool good=p.setBusesLayout(l);p.prepareToPlay(fs,block);return good;}
void fill(juce::AudioBuffer<float>&b,int at,double fs){for(int c=0;c<b.getNumChannels();++c)for(int i=0;i<b.getNumSamples();++i)b.setSample(c,i,input(at+i,fs,c%2));}
void basics(NextKind kind){auto p=std::make_unique<GillNextProcessor>(kind);product=p->getName();check(p->getNumPrograms()>=6,"usable factory presets available");std::set<std::string>ids;for(const auto&d:p->definitions)ids.insert(d.id);check(ids.size()==p->definitions.size(),"all parameter identifiers unique");
 for(double fs:{22050.,44100.,48000.,88200.,96000.,192000.})for(int channels:{1,2}){
  check(setup(*p,fs,127,channels),"mono/stereo host layout accepted");juce::AudioBuffer<float>b(channels,127);juce::MidiBuffer m;bool finite=true;for(int block=0;block<12;++block){fill(b,block*127,fs);watch=true;p->processBlock(b,m);watch=false;for(int c=0;c<channels;++c)for(int i=0;i<127;++i)finite&=std::isfinite(b.getSample(c,i))&&std::abs(b.getSample(c,i))<32.1f;}check(finite,"audio finite at supported sample rate");
  p->setValue("bypass",1,false);bool exact=true;for(int block=12;block<48;++block){fill(b,block*127,fs);watch=true;p->processBlock(b,m);watch=false;if(block>40)for(int c=0;c<channels;++c)for(int i=0;i<127;++i){const int source=block*127+i-p->getLatencySamples();exact&=b.getSample(c,i)==(source<0?0:input(source,fs,c));}}check(exact,"plugin bypass keeps sample-exact host delay");p->setValue("bypass",0,false);p->releaseResources();
 }
 setup(*p,48000,127);juce::AudioBuffer<float>b(2,127);juce::MidiBuffer m;bool presets=true;
 for(int i=0;i<p->getNumPrograms();++i){p->selectPreset(i,false);presets&=p->presetMatches();for(int block=0;block<5;++block){fill(b,block*127,48000);p->processBlock(b,m);for(int c=0;c<2;++c)for(int n=0;n<127;++n)presets&=std::isfinite(b.getSample(c,n));}}check(presets,"every factory preset matches its controls and processes finite audio");
 for(const auto&d:p->definitions)p->setValue(d.id,d.lo+(d.hi-d.lo)*.39f,false);juce::MemoryBlock state;p->getStateInformation(state);std::vector<float>saved;for(const auto&d:p->definitions)saved.push_back(p->value(d.id));for(const auto&d:p->definitions)p->setValue(d.id,d.def,false);p->setStateInformation(state.getData(),int(state.getSize()));bool restored=true;for(size_t i=0;i<saved.size();++i)if(p->definitions[i].id!="preview")restored&=saved[i]==p->value(p->definitions[i].id);check(restored,"saved parameter state recalls canonical values");
 auto before=p->value(p->definitions[0].id);const char bad[]{'x','y','z'};p->setStateInformation(bad,3);check(p->value(p->definitions[0].id)==before,"malformed state leaves current settings intact");
 p->selectPreset(0,false);std::mt19937 rng(42);bool finite=true;for(int block=0;block<80;++block){if(block%8==0)for(const auto&d:p->definitions)p->setValue(d.id,d.lo+(d.hi-d.lo)*(rng()%1001)/1000.f,false);fill(b,block*127,48000);watch=true;p->processBlock(b,m);watch=false;for(int c=0;c<2;++c)for(int n=0;n<127;++n)finite&=std::isfinite(b.getSample(c,n));}check(finite,"simultaneous parameter automation stays finite");
}
struct Components{std::vector<juce::Component*>all;void scan(juce::Component&c){all.push_back(&c);for(auto*child:c.getChildren())scan(*child);}};
juce::MouseEvent mouse(juce::Component&c,juce::Point<float>pt,juce::ModifierKeys mods=juce::ModifierKeys::leftButtonModifier,int clicks=1,bool dragged=false,juce::Point<float>start={}){auto now=juce::Time::getCurrentTime();return{juce::Desktop::getInstance().getMainMouseSource(),pt,mods,1,0,0,0,0,&c,&c,now,dragged?start:pt,now,clicks,dragged};}
void click(juce::Button&b){auto pt=b.getLocalBounds().getCentre().toFloat();juce::Component&c=b;c.mouseDown(mouse(c,pt));c.mouseUp(mouse(c,pt,juce::ModifierKeys()));tick();}
void ui(NextKind kind){auto p=std::make_unique<GillNextProcessor>(kind);product=p->getName();setup(*p,48000,127);auto e=std::unique_ptr<juce::AudioProcessorEditor>(p->createEditor());e->setVisible(true);tick();Components components;components.scan(*e);std::set<std::string>covered;
 for(auto*c:components.all){const auto id=c->getComponentID();auto*param=p->apvts.getParameter(id);if(auto*s=dynamic_cast<juce::Slider*>(c)){check(param!=nullptr,"visible slider has real parameter: "+id);if(!param)continue;covered.insert(id.toStdString());const auto&r=param->getNormalisableRange();check(s->isVisible()&&s->getWidth()>=40&&s->getHeight()>=22&&s->getMinimum()==r.start&&s->getMaximum()==r.end,"slider exposes full usable range: "+id);
   s->setValue(param->convertFrom0to1(.34f),juce::sendNotificationSync);check(std::abs(p->value(id)-float(s->getValue()))<.001f,"slider edit reaches audio parameter: "+id);const auto a=s->getLocalBounds().getCentre().toFloat();const float old=p->value(id);s->mouseDown(mouse(*s,a+juce::Point<float>(-20,0)));s->mouseDrag(mouse(*s,a+juce::Point<float>(20,-15),juce::ModifierKeys::leftButtonModifier,1,true,a+juce::Point<float>(-20,0)));s->mouseUp(mouse(*s,a,juce::ModifierKeys()));check(old!=p->value(id),"actual drag changes control: "+id);s->mouseDoubleClick(mouse(*s,a,juce::ModifierKeys::leftButtonModifier,2));check(std::abs(param->getValue()-param->getDefaultValue())<1e-6,"double click resets control: "+id);
  }else if(auto*l=dynamic_cast<juce::Label*>(c)){if(param&&l->isEditable()){covered.insert(id.toStdString());const auto wanted=param->getNormalisableRange().snapToLegalValue(param->convertFrom0to1(.31f));l->setText(juce::String(wanted,4),juce::sendNotificationSync);check(std::abs(p->value(id)-wanted)<.011f,"direct numeric display edits parameter: "+id);}}
  else if(auto*b=dynamic_cast<juce::Button*>(c)){if(param&&b->getClickingTogglesState()){covered.insert(id.toStdString());const float old=p->value(id);if(b->isEnabled()){click(*b);check(p->value(id)!=old,"actual toggle changes parameter: "+id);click(*b);}}}
  else if(auto*b=dynamic_cast<juce::ComboBox*>(c)){if(param){covered.insert(id.toStdString());b->setSelectedItemIndex(b->getNumItems()-1,juce::sendNotificationSync);check(p->value(id)==b->getNumItems()-1,"choice reaches processor: "+id);}else if(b->getName()=="PRESET"){b->setSelectedId(p->getNumPrograms(),juce::sendNotificationSync);check(p->getCurrentProgram()==p->getNumPrograms()-1&&p->presetMatches(),"preset footer restores selected sound");}}
 }
 if(kind==NextKind::Clean){int tested=0;for(auto*c:components.all)if(auto*b=dynamic_cast<juce::Button*>(c))if(b->getComponentID().startsWith("listen")){click(*b);if(p->value("listen")>0)++tested;click(*b);}check(tested==3,"all three individual LISTEN buttons audition removed components");if(tested==3)covered.insert("listen");}
 if(kind==NextKind::Form){for(auto*c:components.all)if(c->getComponentID()=="voicePad"){p->setValue("link",0,false);auto start=c->getLocalBounds().getCentre().toFloat(),end=start+juce::Point<float>(42,-25);c->mouseDown(mouse(*c,start));c->mouseDrag(mouse(*c,end,juce::ModifierKeys::leftButtonModifier,1,true,start));c->mouseUp(mouse(*c,end,juce::ModifierKeys()));check(p->value("pitch")!=0&&p->value("formant")!=0,"VOICE PAD drag changes pitch and formant independently");covered.insert("pitch");covered.insert("formant");}}
 bool complete=true;for(const auto&d:p->definitions)complete&=covered.count(d.id)>0;check(complete,"all declared parameters have editable UI controls");
 p->selectPreset(0,false);p->setValue("bypass",0,false);p->setValue("listen",0,false);p->setValue("link",0,false);juce::AudioBuffer<float>b(2,127);juce::MidiBuffer m;for(int i=0;i<50;++i){fill(b,i*127,48000);p->processBlock(b,m);}tick();const int w=e->getWidth(),h=e->getHeight();check(w<=760&&h<=460,"default editor is compact");for(int scale:{1,2}){e->setSize(w*scale,h*scale);tick();auto image=e->createComponentSnapshot(e->getLocalBounds());juce::FileOutputStream out(juce::File::getCurrentWorkingDirectory().getChildFile(product+"-UI-"+juce::String(w*scale)+"x"+juce::String(h*scale)+".png"));if(out.openedOk()){out.setPosition(0);out.truncate();}juce::PNGImageFormat png;check(out.openedOk()&&png.writeImageToStream(image,out),"native UI renders at requested scale");}
}
struct Head:juce::AudioPlayHead{std::int64_t sample=0;juce::Optional<PositionInfo>getPosition()const override{PositionInfo p;p.setTimeInSamples(sample);p.setIsPlaying(true);return p;}};
void workflows(){
 product="GILLPOCKET";auto pocket=std::make_unique<GillNextProcessor>(NextKind::Pocket);check(setup(*pocket,48000,127,2,true),"external mono/stereo vocal guide bus accepted");juce::AudioBuffer<float>b(4,127);juce::MidiBuffer m;for(int k=0;k<500;++k){fill(b,k*127,48000);pocket->processBlock(b,m);}check(pocket->sidechainActive&&pocket->reduction>0,"external guide triggers actual frequency-selective ducking");for(int k=0;k<600;++k){fill(b,k*127,48000);b.clear(2,0,127);b.clear(3,0,127);pocket->processBlock(b,m);}check(!pocket->sidechainActive&&pocket->reduction<.1f,"silent guide releases ducking");
 product="GILLFINISH";auto finish=std::make_unique<GillNextProcessor>(NextKind::Finish);setup(*finish,48000,127);b.setSize(2,127);finish->startLearn();for(int k=0;k<4700;++k){fill(b,k*127,48000);finish->processBlock(b,m);}check(finish->learnState==2&&finish->learnProgress>=1,"master learns a twelve-second full-mix passage");const auto before=finish->value("drive");finish->applyLearn();check(finish->learnState==3&&finish->value("drive")==finish->learnDrive,"apply uses the displayed master suggestion");finish->revertLearn();check(finish->value("drive")==before&&finish->learnState==2,"revert restores previous master settings");
 finish->setValue("comp",0,false);finish->setValue("stereoon",0,false);finish->setValue("limiteron",0,false);finish->setValue("drive",6,false);finish->setValue("match",1,false);for(int k=0;k<2500;++k){fill(b,k*127,48000);finish->processBlock(b,m);}const double ratio=finish->outputRms/finish->inputRms;check(std::abs(20*std::log10(ratio))<.12,"gain-matched comparison removes stationary loudness advantage",20*std::log10(ratio));
 product="GILLALIGN";auto align=std::make_unique<GillNextProcessor>(NextKind::Align);setup(*align,48000,127,2,true);Head head;align->setPlayHead(&head);b.setSize(4,127);align->capture(0);for(int k=0;k<400;++k){head.sample=k*127;fill(b,k*127,48000);for(int i=0;i<127;++i){const double phase=std::fmod((k*127+i)/48000.,.23);const float envelope=phase<.15?float(std::pow(std::sin(juce::MathConstants<double>::pi*phase/.15),2)):0;for(int c=0;c<4;++c)b.setSample(c,i,b.getSample(c,i)*envelope);}align->processBlock(b,m);}align->capture(0);align->processBlock(b,m);align->capture(1);for(int k=0;k<400;++k){head.sample=k*127;fill(b,k*127,48000);for(int i=0;i<127;++i){const double phase=std::fmod((k*127+i)/48000.,.23);const float envelope=phase<.15?float(std::pow(std::sin(juce::MathConstants<double>::pi*phase/.15),2)):0;for(int c=0;c<4;++c)b.setSample(c,i,b.getSample(c,i)*envelope);}align->processBlock(b,m);}align->capture(1);align->processBlock(b,m);check(align->guideSeconds>1&&align->doubleSeconds>1&&align->captureState==0,"guide and double captures stop at actual audio boundaries");align->alignTakes();align->processBlock(b,m);for(int i=0;i<600&&align->alignState==2;++i)juce::Thread::sleep(10);check(align->alignState==3,"offline alignment completes from the captured takes");align->setValue("preview",1,false);head.sample=10000;fill(b,10000,48000);align->processBlock(b,m);bool finite=true;for(int c=0;c<2;++c)for(int i=0;i<127;++i)finite&=std::isfinite(b.getSample(c,i));check(finite,"host-position-bound aligned preview returns finite audio");juce::MemoryBlock state;align->getStateInformation(state);check(state.getSize()<20000,"alignment stores an audio-file reference rather than large audio blobs");align->setPlayHead(nullptr);
}
int main(){juce::ScopedJuceInitialiser_GUI gui;
    // Update06: exercise real LIVE/PRO host state, audio timing and UI.
    gill::testing::qualityRoutes([]{return std::make_unique<GillNextProcessor>(NextKind::Ride);},[](bool ok,const std::string& why){check(ok,why.c_str());});
    gill::testing::qualityRoutes([]{return std::make_unique<GillNextProcessor>(NextKind::Clean);},[](bool ok,const std::string& why){check(ok,why.c_str());});
    gill::testing::qualityRoutes([]{return std::make_unique<GillNextProcessor>(NextKind::Pocket);},[](bool ok,const std::string& why){check(ok,why.c_str());});
    gill::testing::qualityRoutes([]{return std::make_unique<GillNextProcessor>(NextKind::Align);},[](bool ok,const std::string& why){check(ok,why.c_str());});
    gill::testing::qualityRoutes([]{return std::make_unique<GillNextProcessor>(NextKind::Form);},[](bool ok,const std::string& why){check(ok,why.c_str());});
    gill::testing::qualityRoutes([]{return std::make_unique<GillNextProcessor>(NextKind::Finish);},[](bool ok,const std::string& why){check(ok,why.c_str());});
for(auto k:{NextKind::Ride,NextKind::Clean,NextKind::Pocket,NextKind::Align,NextKind::Form,NextKind::Finish}){basics(k);ui(k);}workflows();check(allocations.load()==0,"all measured wrapper audio calls allocate no heap memory",allocations.load());std::printf("RESULT %d checks %d failures\n",checks,failures);std::ofstream json("next-integration-report.json");json<<"{\"checks\":"<<checks<<",\"failures\":"<<failures<<",\"audio_allocations\":"<<allocations.load()<<"}";return failures?1:0;}
